### ISSUE TITLE
Silent mode with Caffe Javacpp

### ISSUE THREAD

**Issue by elbahprom** [bytedeco/javacpp#100]
Hi everyone,

How to make Caffe silent (not displaying anything ?) It can be done in Python by setting os.environ['GLOG_minloglevel'] = '2' before import caffe, but how to do it in Java ?

Thank you in advance,

**Comment by saudet** [comment]
So, for reference, could you explain how have you solved this? Thanks!

**Comment by elbahprom** [comment]
Hi @saudet, I found a way to make it work by calling  "export GLOG_minloglevel=2" in the terminal (before running the IDE or javac). Same approach for setting the number of cores for parallel processing : export OPENBLAS_NUM_THREADS=8.
Best,
