### ISSUE TITLE
multi thread

### ISSUE THREAD

**Issue by dongguadan** [bytedeco/javacpp#101]
Excuse me. How can i do some  multi thread or mutex/cond coding in the javacpp?  Because i want to do some cahe mechanism for video transcoding.

**Comment by saudet** [comment]
We just need to do it in Java or C++ in the usual way. There's nothing
special about it.

**Comment by dongguadan** [comment]
oh! Thank you  very much!

**Comment by dongguadan** [comment]
oh ! thank you very much!
