### ISSUE TITLE
Random im2col JVM fatal error

### ISSUE THREAD

**Issue by elbahprom** [bytedeco/javacpp#107]
Hi,
I am having an annoying issue. Basically a JVM fatal error due to im2col that happens randomly : 
```
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007fa513840888, pid=28067, tid=140352475903744
JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode linux-amd64 compressed oops) Problematic frame:
 C  [libcaffe.so.1.0.0-rc3+0x2db888]  void caffe::im2col_cpu<float>(float const*, int, int, int, int, int, int, int, int, int, int, int, float*)+0x208
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

I have tried everything to solve it and no success so far. I expected this error to come from some mismatch dimensions in the data, but the error happens randomly with the SAME data, even on all-zeros arrays of fixed size. 

The way I use caffe for classification is like this : 
- I have a list of "samples" downloaded from Hbase (via an ApplicationMaster)
- this list of samples is called in a train method that has the following structure : 
1) Create Floatsolver object
2) Do some pre-processing on the data
3) Main training part :  there's a loop for epochs, where at each epoch I shuffle data, augment, copy data to float[] arrays etc, then call Solver.Step
4) After Solver.Step (for every epoch), I get netParameter (solver.net().ToProto(currentParameter);) to use it for validation. 
5) The best validation parameters are copied to another netParameter (bestParameter.CopyFrom(currentParameter);)
6) End of the epochs, copying some stuff and closing netparameters and solver.

Now, this fatal error happens inside Solver.Step during training, at random iterations. The problem doesn't come from the data because it also happens (randomly) with all 0s arrays of pre-defined fixed size.
For the same data, sometimes I don't get at all this error (so everything is fine), sometimes I get it. It's very annoying because it crashes containers on Hadoop and it would be really really great to fix this issue. 
I have tried everything with this bug, would be really nice if someone can figure out why it happens.
Thank you very much in advance.

**Comment by saudet** [comment]
You could try to set the `org.bytedeco.javacpp.nopointergc` to `true` just to make sure it's not an issue related to the garbage collector.

**Comment by elbahprom** [comment]
Thank you @saudet for your feedback. Where should I put this variable to true? Can I put it in the beginning of the the train function (like System.getProperty("org.bytedeco.javacpp.nopointergc", "true"); )? 
Thank you in advance

**Comment by saudet** [comment]
Try to make it your first statement in the main() method or on the command line: `-Dorg.bytedeco.javacpp.nopointergc=true`

**Comment by elbahprom** [comment]
Doesn't seem to fix the issue... but I have a feeling that is related to memory/gc thing. Do you have other suggestions? Here's the skeleton of the code if it might help : 

`NetParameter bestParameter = new NetParameter();
NetParameter currentParameter = new NetParameter();
...
for (int i = 1; i <= NUMBER_OF_EPOCHS; i++){
//Process data (data is a List<Sample> 
float[] dataFloat = new float[dim * trainSamplesSize];
float[] labelFloat = new float[trainSamplesSize];

//Fill float[] arrays with data

//Feed data/labels via FloatBuffer 
[...]
dataFloatBuffer.put(dataFloat);
labelFloatBuffer.put(labelFloat);
input1.Reset(dataFloatBuffer, labelFloatBuffer, (labelFloat.length));
(where FloatMemoryDataLayer is FloatMemoryDataLayer)

//Run for one epoch
solver.Step(numberOfIterations);
//Copy weights
solver.net().ToProto(currentParameter);
//Do validation with currentParameter
currentfscore = validate(samplesForValidation, currentParameter);
if(bestFscore < fscore){
bestFscore = currentfscore;
bestParameter.CopyFrom(currentParameter);
}

}//End of training/validation
}
`

Thank you in advance,

**Comment by saudet** [comment]
You could try to enabling the debug level of the logger with `org.bytedeco.javacpp.logger.debug` and see if anything fishy seems to be happening...

**Comment by elbahprom** [comment]
This is what I get just before the error, seems to me it's related to the gc... : 

`Registering org.bytedeco.javacpp.caffe$FloatNet[address=0x7f563d9ccc20,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f563d9ccc20,deallocatorAddress=0x7f567aeee2f0]]`
`Deallocating org.bytedeco.javacpp.caffe$FloatNet[address=0x7f563d9ccc20,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x7f563d9ccc20,deallocatorAddress=0x7f567aeee2f0]]`
`2016-06-10 15:32:48,241 [main] INFO  ClassificationClass - org.bytedeco.javacpp.nopointergc : true
[GC (Allocation Failure)  1071795K->236864K(1210880K), 0,0256240 secs]`

**Comment by saudet** [comment]
I don't see anything wrong with that, for example:
https://greencircle.vmturbo.com/community/products/blog/2016/02/12/understanding-gc-allocation-failure-messages-in-the-logs
Please try to find what is wrong. It might be a bug in Caffe that has nothing to do with Java or JavaCPP. And I won't be able to help if that is the case.

**Comment by elbahprom** [comment]
I think it comes from the way I put data in the floatMemoryDataLayer. So far it's done it like this : 

`ByteBuffer bufferData = ByteBuffer.allocateDirect(sizeOfFloat * (dataFloat.length));`
`bufferData.order(ByteOrder.nativeOrder());
`FloatBuffer dataFloatBuffer = bufferData.asFloatBuffer();`

`ByteBuffer bufferLabel = ByteBuffer.allocateDirect(sizeOfFloat * (labelFloat.length));`
`bufferLabel.order(ByteOrder.nativeOrder());`
`FloatBuffer labelFloatBuffer = bufferLabel.asFloatBuffer();`

`dataFloatBuffer.put(dataFloat);`
`labelFloatBuffer.put(labelFloat);`
`floatMemoryDataLayer.Reset(dataFloatBuffer, labelFloatBuffer, (labelFloat.length));`

I see that `floatMemoryDataLayer.Reset` can take directly float[], but how can I set the last integer argument?

**Comment by saudet** [comment]
What does the documentation of Caffe have to say about that argument?

**Comment by elbahprom** [comment]
Unfortunately, I couldn't find anything about that...

**Comment by saudet** [comment]
Also, unless you need to use Buffer or arrays for some reason, you shouldn't use those types. Use BytePointer, FloatPointer, etc.

**Comment by elbahprom** [comment]
Thank you @saudet. I solved the issue by calling `solver.net().layer_by_name(FloatMemoryDataLayer.class,...` directly instead of putting 'solver.net()' in separate variable. Basically, before, I was something like this : 
`FloatMemorDataLayer fmdl = solver.net().layer_by_name(FloatMemoryDataLayer.class, TRAIN_LAYER_NAME)`
Then using `fmdl`in the rest of the code, which was the wrong way. Now I just use `solver.net().layer_by_name(FloatMemoryDataLayer.class, TRAIN_LAYER_NAME)` directly and it fixed my issue. 
I also replaced the buffer thing with FloatPointer, which makes the code cleaner, thank you!

**Comment by saudet** [comment]
I see, `solver.net()` returns a shared pointer, while `layer_by_name()` does not, and references what is inside the net. So if we don't store the net somewhere permanent like in a class field, it might get garbage collected because JavaCPP cannot not know this. That is probably was is causing the crash.

**Comment by elbahprom** [comment]
Makes sense, thank you for the explanation!
