### ISSUE TITLE
Support generation of proper Java enums

### ISSUE THREAD

**Issue by jjzazuet** [bytedeco/javacpp#108]
Hi. Thanks for such an awesome project!

Now, I know that when instructed, SWIG supports code generation for proper Java 1.5 enums coming from C or C++ enum definitions.

http://www.swig.org/Doc3.0/SWIGDocumentation.html#Java_proper_enums

Is it possible to support this feature in JavaCpp?

Thanks!

**Comment by saudet** [comment]
Sure, but as usual someone needs to take the time to work on it. If this is something that is important enough for you, please do make a contribution and send a pull request. I will be happy to help with any issues you encounter.

**Comment by jjzazuet** [comment]
Sure thing. From what I can find in the code, it seems that the core modifications would need to happen inside the `Parser` class. I'll try to find the time and see if I can make a few changes. Thanks!

**Comment by jjzazuet** [comment]
By the way, I would *highly* recommend migrating the build system to Gradle, since it now offers facilities for working with native code bases. I understand that not everyone is using it, but I think it may pre-implement stuff that this project does through the code itself (e.g. creating fat jars with 3rd party libs, identifying platform information at runtime and managing the compiler invocation process for the native environment).

http://gradle.org/getting-started-native/

Let me know if you're interested in this and I can try to help.

Thanks!

**Comment by saudet** [comment]
Yes, I think most of modifications would take place in Parser.enumeration():
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/Parser.java#L2412

As for Gradle, we need to support other things like sbt as well, so we can't really migrate to Gradle. But we can provide those kinds of features via plugins and what not, and that would be most welcome. @lloydmeta is maintaining sbt-javacv and sbt-javacpp, so something like that for Gradle would be awesome. Others are interested: https://github.com/bytedeco/javacv/issues/395 And if it can help support Android Studio better, just for that it would be worth it IMO.

**Comment by saudet** [comment]
This feature has finally been added! Please let me know if you encounter any issues using it.

**Comment by saudet** [comment]
FYI, released with version 1.4.1. Enjoy!

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
