### ISSUE TITLE
Parser - ignore super class

### ISSUE THREAD

**Issue by jo-m** [bytedeco/javacpp#110]
I did not find an example covering my question, and I don't know if it is possible using the parser. Setup as follows:

I have written a C++ library which depends on libgmp for big int calculations. This library includes a wrapper for GMPs mpz_class (`integer.h`):

```
class Integer : public mpz_class {
    public:
        /* Constructors */
        Integer();
        Integer(const mpz_class &input);
        Integer(const long &input);
        ...
```

In my Java bindings, I want libgmp to be hidden so only `Integer` is visible, i.e. only let Javacpp parse my own header files and not additionally GMPs. In terms of translation, this means I want

```
    public static class Integer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public Integer(Pointer p) { super(p); }
        ...
```
instead of 
```
    public static class Integer extends mpz_class {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public Integer(Pointer p) { super(p); }
        ...
```

I tried the following:

```
public void map(InfoMap infoMap) {
        infoMap.put(new Info("mpz_class").skip())
        ...
```

However, the generated Java code is still `public static class Integer extends mpz_class`. Is there any way to remove superclasses from C++ types?

Thank you very much.

## Edit - Workaround hack
For now, I have fixed this using a very hacky hack (there probably is a better solution :grimacing:):

* first, I create an empty Java `mpz_class` so the parser does not complain (maybe this is not even necessary)

```
package my.package;

public class mpz_class  {}
```

* Then after parsing and before generating the C++ code, I just replace `mpz_class` with `Pointer` and the default constructor in the generated Java class file:

```
ant.replace(file: targetFile,
            token: 'Integer extends mpz_class',
            value: 'Integer extends Pointer')
    ant.replace(file: targetFile,
            token: 'public Integer() { super((Pointer)null); allocate(); }',
            value: 'public Integer() { allocate(); }')
```

**Comment by saudet** [comment]
What you're looking for is [Info.base](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/Info.html#base). In this case something like `new Info("Integer").base("Pointer")`.

**Comment by jo-m** [comment]
Thanks, that solved it. Also, very fast response time!
