### ISSUE TITLE
Error while running "mvn clean install'

### ISSUE THREAD

**Issue by akhilc1** [bytedeco/javacpp#111]
I was using 'mvn clean install' on linux and I am getting an error as shown below:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.bytedeco.javacpp.AdapterTest
Generating /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniAdapterTest.cpp
Compiling /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64/libjniAdapterTest.so
g++ -I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniAdapterTest.cpp -std=c++11 -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o libjniAdapterTest.so 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.548 sec <<< FAILURE! - in org.bytedeco.javacpp.AdapterTest
org.bytedeco.javacpp.AdapterTest  Time elapsed: 0.547 sec  <<< ERROR!
java.io.IOException: Cannot run program "g++" (in directory "/home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64"): error=2, No such file or directory
	at org.bytedeco.javacpp.AdapterTest.setUpClass(AdapterTest.java:75)
Caused by: java.io.IOException: error=2, No such file or directory
	at org.bytedeco.javacpp.AdapterTest.setUpClass(AdapterTest.java:75)

Running org.bytedeco.javacpp.IndexerTest
Generating /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniIndexerTest.cpp
Compiling /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64/libjniIndexerTest.so
g++ -I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniIndexerTest.cpp -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o libjniIndexerTest.so 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.159 sec <<< FAILURE! - in org.bytedeco.javacpp.IndexerTest
org.bytedeco.javacpp.IndexerTest  Time elapsed: 0.15 sec  <<< ERROR!
java.io.IOException: Cannot run program "g++" (in directory "/home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64"): error=2, No such file or directory
	at org.bytedeco.javacpp.IndexerTest.setUpClass(IndexerTest.java:53)
Caused by: java.io.IOException: error=2, No such file or directory
	at org.bytedeco.javacpp.IndexerTest.setUpClass(IndexerTest.java:53)

Running org.bytedeco.javacpp.PointerTest
Generating /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniPointerTest.cpp
Compiling /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64/libjniPointerTest.so
g++ -I/usr/lib/jvm/java-7-oracle/include -I/usr/lib/jvm/java-7-oracle/include/linux /home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/jniPointerTest.cpp -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o libjniPointerTest.so 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.164 sec <<< FAILURE! - in org.bytedeco.javacpp.PointerTest
org.bytedeco.javacpp.PointerTest  Time elapsed: 0.164 sec  <<< ERROR!
java.io.IOException: Cannot run program "g++" (in directory "/home/user/Desktop/BuildLibrary/javacpp/target/test-classes/org/bytedeco/javacpp/linux-x86_64"): error=2, No such file or directory
	at org.bytedeco.javacpp.PointerTest.setUpClass(PointerTest.java:51)
Caused by: java.io.IOException: error=2, No such file or directory
	at org.bytedeco.javacpp.PointerTest.setUpClass(PointerTest.java:51)

Results :

Tests in error: 
  AdapterTest.setUpClass:75 » IO Cannot run program "g++" (in directory "/home/u...
  IndexerTest.setUpClass:53 » IO Cannot run program "g++" (in directory "/home/u...
  PointerTest.setUpClass:51 » IO Cannot run program "g++" (in directory "/home/u...

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.081s
[INFO] Finished at: Fri Jul 01 21:44:19 IST 2016
[INFO] Final Memory: 32M/607M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project javacpp: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/Desktop/BuildLibrary/javacpp/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
user@user-B85M-DS3H-A:~/Desktop/BuildLibrary/javacpp$ 

I would be greatful if I could find a solution for this issue, I am pretty desparate.

**Comment by saudet** [comment]
Please install GCC.

**Comment by akhilc1** [comment]
That solved the issue, also I had to install curl and cmake. Now am stuck with the following error,
CMake Error at platforms/android/android.toolchain.cmake:809 (message):
  Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.
Call Stack (most recent call first):
  CMakeFiles/2.8.12.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:93 (project)


-- Detected version of GNU GCC: 49 (409)
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/share/cmake-2.8/Modules/TestBigEndian.cmake:44 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeLists.txt:527 (test_big_endian)


-- Configuring incomplete, errors occurred!
See also "/home/user/Desktop/JavaCV/WorkspaceCV/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.1.0/CMakeFiles/CMakeOutput.log".
See also "/home/user/Desktop/JavaCV/WorkspaceCV/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.1.0/CMakeFiles/CMakeError.log".
when I execute ANDROID_NDK=/path/to/android-ndk/ bash cppbuild.sh -platform android-xxx install

**Comment by saudet** [comment]
Please try to follow the instructions for your platform here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by akhilc1** [comment]
I build using the instructions from the above link itself. OpenCV guys told that that we can specify explicitly native api level using 'Add -DANDROID_NATIVE_API_LEVEL=xxx to specify API level'  ' ANDROID_NATIVE_API_LEVEL is OpenCV's CMake variable passed via CMake command line (-D option) or via environment. ' . Do we add this in "$ ANDROID_NDK=/path/to/android-ndk/ bash cppbuild.sh -platform android-xxx install" or some build script?? @saudet

**Comment by saudet** [comment]
If it works for you, sure

**Comment by akhilc1** [comment]
No its not working, I think I edited in the wrong place, could you point me in the right direction?
