### ISSUE TITLE
How to use javacpp on Android 

### ISSUE THREAD

**Issue by joyoyao** [bytedeco/javacpp#115]
I want to use javacpp on android ,I failed When  refer to https://github.com/bytedeco/javacpp/wiki/Gradle，Can provide an example ?

**Comment by saudet** [comment]
There isn't a Gradle plugin yet unfortunately, but it's possible to use the command line tool from Gradle this way for example: https://gist.github.com/bongole/05021bdd1f21578e1f6f

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
