### ISSUE TITLE
Plan to release version 1.2.3

### ISSUE THREAD

**Issue by npanpaliya** [bytedeco/javacpp#121]
Hi, 
I see master branch has some changes done with respect to 1.2.3 but 1.2.3 hasn't been released officially yet. I want to know when would this be released.

**Comment by saudet** [comment]
Yes it has been released:
http://search.maven.org/#artifactdetails%7Corg.bytedeco%7Cjavacpp%7C1.2.3%7Cjar

**Comment by npanpaliya** [comment]
Thanks @saudet, I didn't see any tag for that. So, should I use the current master branch?

**Comment by saudet** [comment]
Forgot the tag, I've just added one.

**Comment by npanpaliya** [comment]
Okay. Thanks.

**Comment by saudet** [comment]
Thanks for reporting!
