### ISSUE TITLE
Multiple definitions ignored

### ISSUE THREAD

**Issue by ashleyj** [bytedeco/javacpp#124]
When specifying multiple definitions for a class, supplement matches are ignored. Specifically I'm trying to point a definition to another name and annotate with ```@Deallocator```

example:
```
new Info("namespace::blah").pointerTypes("somethingElse")
new Info("namespace::blah()").annotations("@Deallocator"),
```
The second match is ignored

**Comment by saudet** [comment]
Yes, that's the way it's supposed to work right now actually. You can't inverse these two lines? It should work.

**Comment by ashleyj** [comment]
Actually looks like the problem is constructor matching no longer works.... 

I've wiped my project and included a single header and a simple Info definition and I can see the same result -- no match for the constructor.

```
.put(new Info("llvm::DIContext()").annotations("@NoDeallocator"))
```
which generates 
```
@Namespace("llvm") @NoOffset public static class DIContext extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public DIContext(Pointer p) { super(p); }
```

**Comment by saudet** [comment]
In my version of LLVM, there is no `llvm::DIContext()` default constructor, but does there is a `llvm::DIContext(DIContextKind)` one. Is this the one you're trying to annotate?

**Comment by ashleyj** [comment]
Closing this off, i don't believe there's a bug here
