### ISSUE TITLE
Add convenience options for specifying org.bytedeco.javacpp.maxbytes property

### ISSUE THREAD

**Issue by AlexDBlack** [bytedeco/javacpp#125]
Currently setting the maxbytes property is done using a number of bytes.
For large amounts, it would be convenient to set this similar to Xmx options: i.e., "4G" or "1024M" instead of having to specify values like 4294967296 and 1073741824 respectively.

**Comment by saudet** [comment]
Included in version 1.2.4. Thanks for reporting!
