### ISSUE TITLE
Javacpp build failure in the surefire-plugin test

### ISSUE THREAD

**Issue by jenniferwillow** [bytedeco/javacpp#127]
I'm trying to compile javacpp (and ultimately javacv) on RHEL 6.6 but I keep running into the following error when running 'mvn clean install'.  Does anyone have any idea about what's breaking the build?

Tests run: 19, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.300 s
[INFO] Finished at: 2016-08-29T11:16:10-07:00
[INFO] Final Memory: 30M/514M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project javacpp: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/developer/andor_development_stargate/working/opencv/javacpp/javacpp && /usr/local/palomar/java/jdk1.8.0_77/jre/bin/java -jar /home/developer/andor_development_stargate/working/opencv/javacpp/javacpp/target/surefire/surefirebooter3085228468637439840.jar /home/developer/andor_development_stargate/working/opencv/javacpp/javacpp/target/surefire/surefire5271024293490319181tmp /home/developer/andor_development_stargate/working/opencv/javacpp/javacpp/target/surefire/surefire_049818025832313188tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by saudet** [comment]
For Linux, please try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64

**Comment by jenniferwillow** [comment]
Thanks for the response but your instructions don’t even begin to solve the problem.  All of your instructions depend upon using docker as a container.  Unfortunately, docker is NOT AVAILABLE on RHEL 6.x (it requires version 7 as a minimum).  Using CentOS is not an option in our environment.  All of the dependencies have been installed but the system does not compile.  Just pointing me to a set of directions that don’t work is not a terribly useful response.  
     Please address the actual issue.
Jennifer Milburn

**Comment by saudet** [comment]
The idea with Docker is to prevent system dependencies from conflicting with the build. If you cannot use Docker, please try to reinstall the OS from scratch.
