### ISSUE TITLE
Void Pointers and Buffers | Codec Buffers

### ISSUE THREAD

**Issue by sirinath** [bytedeco/javacpp#128]
There are times you want the flexibility to to write out different primitive types into a buffer. So is it possible to have such support where you get and set data of any type at a memory offset and even re interpret part of whole structure as any other primitive type array.

E.g. a structure like this will have different types:
header
 - n_records
 - record 1
  - length
  - type
  - data_array
 - record 2
  - length
  - type
  - data_array

**Comment by saudet** [comment]
Sure, that's what subclassing Pointer is for.

**Comment by saudet** [comment]
But that particular example looks it would be best served by ByteBuffer. Why not use that?

**Comment by sirinath** [comment]
It does not have ` put(long i, long j, long[] b, int offset, int length)`, ` put(long i, long j, float[] b, int offset, int length)` etc.

**Comment by sirinath** [comment]
Java `ByteBuffer` is slow.

**Comment by sirinath** [comment]
I see you are using native to put and get data than unsafe. This is going to be problematic and perhaps slower for what I want to use.

**Comment by saudet** [comment]
An Indexer should be used for fast access, but it's not going to be faster than Buffer:
http://bytedeco.org/news/2014/12/23/third-release/
If you need more speed than that, you'll need to right your code in C++.

**Comment by sirinath** [comment]
You can be faster than Buffer while not in C/C++. See: https://github.com/OpenHFT/Chronicle-Bytes, https://github.com/real-logic/Agrona
