### ISSUE TITLE
No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes()

### ISSUE THREAD

**Issue by Luonic** [bytedeco/javacpp#132]
Hello Samuel! After upgrading JavaCPP to version 1.2.4 from 1.2.3 I started to recive multiple 
`E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)`
during video playback with FFmpeg, looks like it occurs on every frame grab/bgr2rgba color conversion by OpenCV. I played around with versions of JavaCPP and this problem is present only in 1.2.4. With 1.2.3 everything works fine except OOM exception but this seems have been fixed in 1.2.4. Also I tried to add to manifest `android:largeHeap="true"`
So, how can I deal with that problem? JavaCPP installed via gradle in Android Studio 2.2, launched on Nexus 5 6.0.1.
Thanks!

**Comment by saudet** [comment]
You can safely ignore that, it's not a problem. It will go away when binaries are updated, of you could remove the call in JavaCPP, etc, but like I said it's not an issue.
