### ISSUE TITLE
use static library

### ISSUE THREAD

**Issue by xiehechong** [bytedeco/javacpp#134]
generate jni shared library,when link with static library raise error "java.lang.UnsatisfiedLinkError"

**Comment by saudet** [comment]
No it doesn't. You'll have to provide a bit more details if you want me to understand what you are doing wrong.

**Comment by xiehechong** [comment]
build a jni, but use a functioin in a static library. so the jvm raise "java.lang.UnsatisfiedLinkError"

**Comment by saudet** [comment]
Please follow these instructions:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
It shows how to build and use a static libraries, and it works just fine!
