### ISSUE TITLE
javacpp  - does not support vectors of "void *" pointers

### ISSUE THREAD

**Issue by arshadm** [bytedeco/javacpp#139]
I have an application where I would like to return a vector of "void *" pointers, on the java side I have the following definition.

  public native @StdVector Pointer[] getData();

The code thats is generated for this is incorrect, it does not even attempt to copy the data across as is done in the case of primitive types. Rather "NULL" is returned as the variables are uninitialised.

**Comment by saudet** [comment]
What you need is `@StdVector PointerPointer` as shown in the README.md file:
https://github.com/bytedeco/javacpp#using-complex-c-types
