### ISSUE TITLE
Fails with weird template declarations

### ISSUE THREAD

**Issue by crockpotveggies** [bytedeco/javacpp#141]
Javacpp fails when attempting to parse the following:

```
    private:
        typename M::template rebind<char>::other pool; 
    };
```

It's some sort of weird template declaration. This is on line `130` in this file for dlib: https://github.com/davisking/dlib/blob/master/dlib/std_allocator.h#L130

**Comment by saudet** [comment]
I can't reproduce this failure anymore, it's probably been fixed around commit b5378cff5d0f8722bd92a43d05efa9c59cecab96. :)
