### ISSUE TITLE
unimplemented pure virtual method

### ISSUE THREAD

**Issue by 275873859** [bytedeco/javacpp#142]
For example：

``` cpp
virtual void login(const std::string& user,const std::string& pwd,std::function<void(ErrorInfo&)> cb) = 0;
```

My Java file：

``` java
private native @Virtual @Name("login") void login_c(@StdString String user,/*@Const*/ @StdString String pwd,@ByVal Callback result);
```

error
Can you help me ?

**Comment by 275873859** [comment]
.h file:
`virtual void login(const std::string& user) = 0;`
java file:
`private native @Virtual(true) @Name("login") void login_c(@StdString String user);`
This is also wrong,error info:allocating an object of abstract class type  ;service::IAuthService* rptr = new JavaCPP_service_0003a_0003aIAuthService();unimplemented pure virtual method 'login' in 'JavaCPP_service_0003a_0003aIAuthService'

**Comment by saudet** [comment]
This works for the first one:
```java
@Virtual(true) public native void login(@StdString BytePointer user);
```
But the one with a `std::function` parameter is a big more complex. We'll need to figure out something for that.

**Comment by saudet** [comment]
What is the IAuthService class?

**Comment by 275873859** [comment]
The complete code is:
```cpp
#pragma once
#include <functional>
#include <memory>
#include <string>

namespace AuthService
{
class IAuthService
{
  public:
     ~IAuthService();
virtual void login(const std::string& user) = 0;
};
}
```
Java code:
```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Namespace("AuthService")
public class AuthService {
    public static class IAuthService extends Pointer {
        static {
            Loader.load();
        }

        public IAuthService() {
            allocate();
        }

        private native void allocate();

        @Virtual(true) public native void login(@StdString String user);
    }
    public static void main(String[] args) {
        IAuthService service =new IAuthService();
        service.login("aaa");
        System.out.println("Callback success");
    }
}
```
The first example Java code is a reference.

**Comment by saudet** [comment]
I see, then with this declaration it works:
```java
        @Virtual(true) public native void login(@Cast({"", "const std::string&"}) @StdString String user);
```

**Comment by 275873859** [comment]
```java
Exception in thread "main" java.lang.RuntimeException: Cannot call a pure virtual function.
	at NativeLibrary$NativeClass.login(Native Method)
	at NativeLibrary$NativeClass.access$000(NativeLibrary.java:7)
	at NativeLibrary.main(NativeLibrary.java:35)
```

**Comment by saudet** [comment]
Yes, that's normal, what are you trying to do?

**Comment by 275873859** [comment]
Thank you for your help, I should find the corresponding solution.

**Comment by 275873859** [comment]
```cpp
#include <iostream>
#include "jniFoo.h"

int main() {
    JavaCPP_init(0, NULL);
    try {
        foo(6, 7);
    } catch (std::exception &e) {
        std::cout << e.what() << std::endl;
    }
    JavaCPP_uninit();
}
```
This example didn't understand, there are other specific example?

**Comment by saudet** [comment]
Could you explain what you are trying to do?

**Comment by 275873859** [comment]
I need to write before the jni functions Through javacpp implementation.

**Comment by saudet** [comment]
There is some documentation available here for that:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
Let me know if you have any questions!

**Comment by 275873859** [comment]
Thank you very much, I look at the API and examples, if have what not understand place, please teach you again
