### ISSUE TITLE
Always creating new thread when callback function is invoked

### ISSUE THREAD

**Issue by AresZhu** [bytedeco/javacpp#143]
I have callback function in C++, and it works when converted to java by javacpp.
But, when I print the thread id in the callback function, the thread id always changes when the callback function is invoked, that does not make sense, since, the callback function should work in the same thread context.

Does anyone encounter the same issue, or can anyone help me?  Thanks in advance.

BTW: the callback function is invoked by a thread in C++ library at intervals.

**Comment by saudet** [comment]
Since you're basically controlling your threads from C++, you'll need to call AttachCurrentThread(env) as part of its initialization and call DetachCurrentThread() before it gets destroyed to avoid memory leaks.

**Comment by saudet** [comment]
You can find an example of this in the code generated by JavaCPP itself:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L833

**Comment by AresZhu** [comment]
Hi Saudet,

Thanks for your replying, but how do I achieve this in my infomap java code?

**Comment by saudet** [comment]
You can't, that's something we need to do in the C++ library when it creates a new thread.

**Comment by AresZhu** [comment]
But the C++ library is provided by 3rd party, and we could not change it, since it only include header files and .so library.

**Comment by saudet** [comment]
Ok, I've added a hack in the last commit that will do what you want if you write `@Platform(define="NO_JNI_DETACH_THREAD", ...)`, but this will leak resources if threads not created by the JVM are destroyed before the application terminates.

**Comment by AresZhu** [comment]
Hi Saudet, it works for me, thank you very much~

**Comment by gordeevnm** [comment]
> Ok, I've added a hack in the last commit that will do what you want if you write `@Platform(define="NO_JNI_DETACH_THREAD", ...)`, but this will leak resources if threads not created by the JVM are destroyed before the application terminates.
Can you please describe in a little more detail when a memory leak will occur and how to avoid it?

**Comment by saudet** [comment]
@gordeevnm Just making sure that no threads are ever deallocated will prevent any leaks.

**Comment by gordeevnm** [comment]
@saudet They should not be deallocated by native code, or by GC? 
Thank you
