### ISSUE TITLE
How to write infomap for this?

### ISSUE THREAD

**Issue by AresZhu** [bytedeco/javacpp#144]
Dear,

Does anyone know how to write code in infomap for this line.

C++ code, and this is in global scope.
`double const MAX_DBL =  (std::numeric_limits<double>::max)();`

Thanks in advance.

**Comment by AresZhu** [comment]
The generated cpp file reports that error: ‘MAX_DBL’ was not declared in this scope.

**Comment by saudet** [comment]
That would be `infoMap.put(new Info("MAX_DBL").translate(false)`.

**Comment by AresZhu** [comment]
Great, it works, thank you Saudet.

**Comment by AresZhu** [comment]
Sorry, my mistake, it still reports the same error even after I added the line infoMap.put(new Info("DFITC_L2::MAX_DBL").translate(false) in the infomap java code.

Since the variable is within the namespace DFITC_L2.

**Comment by saudet** [comment]
Try `new Info("MAX_DBL").skip()` then?

**Comment by AresZhu** [comment]
Sorry, still failed.
`
public void map(InfoMap infoMap) {
        infoMap
                .put(new Info("DFITC_L2::MAX_DBL").skip())
                .put(new Info("DFITC_L2::THYQuote").pointerTypes("MDBestAndDeep").define())
                .put(new Info("DFITC_L2::TENENTRUST").pointerTypes("MDTenEntrust").define())
                .put(new Info("DFITC_L2::ORDERSTATISTIC").pointerTypes("MDOrderStatistic").define())
                .put(new Info("DFITC_L2::REALTIMEPRICE").pointerTypes("MDRealTimePrice").define())
                .put(new Info("DFITC_L2::MARCHPRICEQTY").pointerTypes("MDMarchPriceQty").define())
                .put(new Info("DFITC_L2::DFITCL2Spi", "DFITC_L2::DFITCL2Api").virtualize())
                .put(new Info("DFITC_L2API_API").skip());
    }
`

and generated C++ code is following:
`
JNIEXPORT void JNICALL Java_org_bytedeco_javacpp_XspeedLevel2_MAX_1DBL__D(JNIEnv* env, jclass cls, jdouble arg0) {
    MAX_DBL = arg0;
}
JNIEXPORT jdouble JNICALL Java_org_bytedeco_javacpp_XspeedLevel2_MAX_1DBL__(JNIEnv* env, jclass cls) {
    jdouble rarg = 0;
    double rvalue = DFITC_L2::MAX_DBL;
    rarg = (jdouble)rvalue;
    return rarg;
}`

But there is not any other information about MAX_DBL.

**Comment by saudet** [comment]
I said `new Info("MAX_DBL").skip()`, I didn't say `new Info("DFITC_L2::MAX_DBL").skip()`. Please try to at least copy/paste properly.

**Comment by AresZhu** [comment]
Yes, when I try the solution, I use both new Info("MAX_DBL").skip() and new Info("DFITC_L2::MAX_DBL").skip(), neither works.

**Comment by saudet** [comment]
The macro is probably defined inside a `#ifdef` ... `#endif` conditional group. So, like is shown in the presets, try to set `define(false)` for the the bit after `#ifdef`.

BTW, there is a lot of examples of what you can try among the presets. Please do refer to them:
https://github.com/bytedeco/javacpp-presets/

Also I'm afraid I won't be able to keep helping you like this is you cannot provide more information than that about what you're having problems with.

**Comment by AresZhu** [comment]
The, the statement is inside a `#ifdef` ... `#endif`, I will try to solve it myself, thanks for your time.
