### ISSUE TITLE
How to map char array to java while using  JavaCpp

### ISSUE THREAD

**Issue by hzyfox** [bytedeco/javacpp#147]
I define a C Struct, and there is a member: char buffer[256]; and I want to use JavaCpp to map it, I use the following code:
```java
public native @Cast("char *")BytePointer buffer(); piblic native void buffer(@Cast("char *")BytePointer buffer);
```
but cause incompatible cast error: from 'char [256]' to 'char*'
Can some one help me how to map it, thank you!

**Comment by saudet** [comment]
Sorry for the late reply. I almost forgot to answer!

Please follow the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

The `Parser` produces this declaration, which works just fine:
```java
@MemberGetter public native @Cast("char*") BytePointer buffer();
```

**Comment by linzaihui** [comment]
@saudet can I map c++ char array to java String, and generated code some like this?
` @MemberGetter  public native String buffer(); 
 @MemberSetter public native void buffer(String value);`
I'd tried `infoMap.put(new Info("char").cast().pointerTypes("String"));` but without luck

**Comment by saudet** [comment]
@linzaihui No, we can't, because `String` cannot be converted to a pointer. It can only be accessed temporarily using a pointer, so that's why it works for functions, but it doesn't work for variables.

**Comment by linzaihui** [comment]
@saudet I have such structure in c++
`typedef struct tagNET_EHOME_IPADDRESS
{
    char szIP[128]; 
    WORD wPort;
    char byRes[2];
}NET_EHOME_IPADDRESS, *LPNET_EHOME_IPADDRESS;`
and generated java code is like
`public static class NET_EHOME_IPADDRESS extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public NET_EHOME_IPADDRESS() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public NET_EHOME_IPADDRESS(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public NET_EHOME_IPADDRESS(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public NET_EHOME_IPADDRESS position(long position) {
        return (NET_EHOME_IPADDRESS)super.position(position);
    }

    public native @ByRef @Cast("char*") String szIP(int i); public native NET_EHOME_IPADDRESS szIP(int i, String setter);
    @MemberGetter public native @Cast("char*") String szIP(); 
...`
I have to modify java code `public native @ByRef @Cast("char*") String szIP(int i); public native NET_EHOME_IPADDRESS szIP(int i, String setter);` to `@MemberSetter public native @ByRef @Cast("char*") void szIP(String val);` and jni code will also work ok.
I just wonder if I can do something to InfoMap so that generated code can turn to that I modified.

**Comment by saudet** [comment]
In that case in particular, something like this should work:
```java
new Info("NET_EHOME_IPADDRESS::szIP").javaText("public native String szIP(); public native NET_EHOME_IPADDRESS szIP(String setter);")
```

**Comment by linzaihui** [comment]
@saudet thank you. But I have a lot of fields of type char-array, is there a convenient way to cover all?

**Comment by saudet** [comment]
Not really, it's not currently possible to provide different `Info` for arrays and pointers of the same type. It would require some additional enhancements to the parser, but contributions are welcome!

**Comment by linzaihui** [comment]
thanks
