### ISSUE TITLE
Gradle Dplatform.linkpath and @Properties linkpath

### ISSUE THREAD

**Issue by 275873859** [bytedeco/javacpp#148]
For example:
@Properties
```java
                        includepath = "XXX/service"
                        link = {"imsdkapi",  "lddplugin"},                               
                        linkpath = "XXX/libs/armeabi") 
```
Gradle:
```java
                        "-Dplatform.includepath=${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include:${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include:${incluePath}",
                        "-Dplatform.linkpath=${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi:${soPath}",
```

I want to ask next, the two configuration, what is the difference? If is set to be given priority to with what?

**Comment by saudet** [comment]
What do you mean by "difference"?

With regards to the priority, the ones defined via the command line have priority:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/ClassProperties.java

Are you having an issue or is this just a question?

**Comment by 275873859** [comment]
My current project, at the command line, call dylib have no questions, but now switch to the Android studio, found so file to load.

**Comment by saudet** [comment]
I see. `linkpath`, `includepath`, and `preloadpath` are relative to the `sysroot`. That might be what is causing the issue.

**Comment by 275873859** [comment]
```java
ext {
    //获取配置的NDK路径
    ndkPath = plugins.getPlugin('com.android.application').sdkHandler.ndkFolder
    projectDir = project.projectDir.absolutePath
    File root = file('src/main')
    // 生成so库的位置
    File libs = file('libs')
    soPath = libs.absolutePath+'/armeabi/';
    //头文件的位置
    incluePath = projectDir + '/jni/service/';//root.absolutePath+'/h';
    //生成java的位置
    javaPath = root.absolutePath + '/java';
}

    sourceSets.main {
        jniLibs.srcDir 'libs'
        jni.srcDirs = [] // disable automatic ndk-build call
    }
    applicationVariants.all { variant ->
        variant.javaCompile.doLast {
            println 'javacpp ' + variant.name + soPath
            javaexec {
                main 'org.bytedeco.javacpp.tools.Builder'
                classpath "libs/javacpp.jar"
                args '-cp', variant.javaCompile.destinationDir,
                        '-properties', 'android-arm',
                        '-classpath', '/Users/zxj/EnvTools/sdk/platforms/android-25/android.jar',
                        "-Dplatform.root=${ndkPath}",
                        "-Dplatform.compiler=${ndkPath}/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++",
                        "-Dplatform.includepath=${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/include:${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include:${incluePath}",
                        "-Dplatform.linkpath=${ndkPath}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi:${soPath}",
                        '-d', "${javaPath}"
            }
            println 'javacpp done'
        }
    }
```

**Comment by 275873859** [comment]
This is my Gradle compilation command:
/Users/zxj/EnvTools/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ --sysroot=/Users/zxj/EnvTools/sdk/ndk-bundle/platforms/android-14/arch-arm/ -I/Users/zxj/EnvTools/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/Users/zxj/EnvTools/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -I/Users/zxj/zxj/Android/Tests/cpp1/app/jni/service/ /Users/zxj/zxj/Android/Tests/cpp1/app/src/main/java/jniImServiceConfig.cpp -march=armv5te -mtune=xscale -msoft-float -funswitch-loops -finline-limit=300 -O3 -s -std=c++11 -Wl,-rpath,lib/ -DANDROID -ffunction-sections -funwind-tables -fstack-protector -Wall -nodefaultlibs -fPIC -shared -Wl,--no-undefined -z text -o libjniImServiceConfig.so -Wl,-soname,libjniImServiceConfig.so -L/Users/zxj/EnvTools/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi -L/Users/zxj/zxj/Android/Tests/cpp1/app/libs/armeabi/ -lservice -limsdkapi -llddplugin -llog -lgnustl_static -lgcc -ldl -lz -lm -lc

**Comment by saudet** [comment]
Yes, that's fine, so which part of my answer do you not understand?

**Comment by 275873859** [comment]
![1](https://cloud.githubusercontent.com/assets/8743818/20700469/7e799f04-b648-11e6-842c-bdbcd556015b.png)

my libservice.so has a function named getClient(), l already link the .so  on command  "-lservice" ,but build error:
```java
jniImServiceConfig.cpp:function Java_vrv_imsdk_api_ImService_getClient: error: undefined reference to ['service::getClient()']()    
```

**Comment by saudet** [comment]
How do you know that this library contains the definition?

**Comment by 275873859** [comment]
Thank you very much for your help, you are great.

**Comment by saudet** [comment]
Happy to hear that it works :)

**Comment by 275873859** [comment]
Ask another question, how could you compile multiple platforms, such as armeabi, armeabi v7a, arm64 v8a, I found
```java
$ java -jar libs/javacpp.jar -classpath bin/ -classpath bin/classes/ \
> -properties <android-arm|android-x86> -Dplatform.root=/path/to/android-ndk/ \
> -Dplatform.compiler=/path/to/<arm-linux-androideabi-g++|i686-linux-android-g++> -d libs/<armeabi|x86>/
```
This one, but there is no better way to generate these? Such as this in Gradle:
```java
       ndk {
            moduleName "NativeExample"
            ldLibs "log", "z", "m"
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
```

**Comment by saudet** [comment]
Not for now. If you would like to make a contribution, a Gradle plugin would be welcome! :)

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
