### ISSUE TITLE
How does feature detection work?

### ISSUE THREAD

**Issue by aghasemi** [bytedeco/javacpp#15]
Hello,
I'm having a very hard time getting a simple Feature detector to work. Here is my code:

 FeatureDetector featureDetector = new opencv_features2d.DenseFeatureDetector();
KeyPoint keypoints = new KeyPoint();
featureDetector.detect(frame, keypoints);

However, the KeyPoint class stands for a single keypoint, not an array of them as it should be. Is there a bug in your architecture?

**Comment by saudet** [comment]
`KeyPoint` is a `Pointer`, which implements the functionality of a native array. We can, for example, loop over the values returned by `featureDetector.detect(frame, keypoints)` this way:
```java
for (int i = 0; i < keypoints.limit(); i++) {
    KeyPoint kp = keypoints.position(i);
    // do something with kp
}
```
