### ISSUE TITLE
FunctionPointer call("const std::string&")

### ISSUE THREAD

**Issue by 275873859** [bytedeco/javacpp#151]
Excuse me, may I ask to a very simple question, but I've tried, and failed to solve:
Such as:
```cpp
virtual void regContactHeadImgUpdateCb(std::function < void(int64,const std::string&) > cb) = 0;
```
In my Java File:
```java
    public abstract static class FnCbLongStr extends FunctionPointer {
        static {Loader.load();}
        protected FnCbLongStr() {allocate();}
        public FnCbLongStr(Pointer p) {super(p);}
        private native void allocate();
        public abstract void call(long code64, @ByRef @Cast("const std::string&") Pointer /**BytePointer*/ p);
    }
```
It can generate so file, but in the end get from Pointer or BytePointer value is wrong,I think here should be liquid `@StdString String` .

**Comment by saudet** [comment]
You've already asked that question and I've already answered here:
https://github.com/bytedeco/javacpp/issues/142#issuecomment-256850646

**Comment by 275873859** [comment]
Sorry,Our engineering finally no problem, thank you for your help.

**Comment by 275873859** [comment]
Hi, I think I still don't know much about the callback parameter setting, although in the case of a caffe see similar, but not the same.
```cpp
virtual void regMsgNoticeCb(std::function< void(std::shared_ptr<Msg>) > cb) = 0;
```
My preset file:
```java
.put(new Info("std::shared_ptr<Msg>", "std::shared_ptr<model::Msg>").annotations("@SharedPtr").pointerTypes("Msg"))
```
In the vector, calling the get method to obtain the value of the is no problem, but the call, I think so also should be written, but compile error, now still didn't understand the usage, can you help me?
```java
 @Index public native @SharedPtr Msg get(@Cast("size_t") long i);
```
My call() method :
```java
public abstract void call(@Cast("const std::shared_ptr<Msg>") @SharedPtr Pointer p);
```

**Comment by 275873859** [comment]
Another, I now through the compiler =` {" cpp11 ", "fastfpu}"` generated v7.so file
But through the readelf tools, to see the compilation and other has two different,
by ` {" cpp11 ", "fastfpu}"`:
```java
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM v7"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_optimization_goals: Aggressive Speed
  Tag_CPU_unaligned_access: v6
  Tag_DIV_use: Not allowed
```
Others:
```java
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM v7"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_optimization_goals: Aggressive Speed
  Tag_CPU_unaligned_access: v6
  Tag_DIV_use: Not allowed
```
Our program will collapse in the Android M, there is no other users also met this problem?

**Comment by saudet** [comment]
What compiler error are you getting? And don't use "fastfpu" if you have issues.

**Comment by 275873859** [comment]
Can you help me to look at the first: `public abstract void call (@ Cast (" const STD: : from < Msg > ") @ SharedPtr Pointer p)` of the problem?

**Comment by 275873859** [comment]
This compilation can pass, but the values, is wrong. In javacpp or javacpp - persets didn't find the corresponding examples.
```java
public abstract void call(@ByRef @Cast("const std::shared_ptr<Msg>") Pointer p);
```

**Comment by saudet** [comment]
Are you talking about `std::function` in a callback? Already answered that here: https://github.com/bytedeco/javacpp/issues/142#issuecomment-255930244

**Comment by saudet** [comment]
As for shared_ptr, there are examples in Caffe and TensorFlow: 
https://github.com/bytedeco/javacpp-presets/search?q=SHARED_PTR_NAMESPACE

**Comment by 275873859** [comment]
![1](https://cloud.githubusercontent.com/assets/8743818/21414513/1b77a2ac-c83b-11e6-9de3-215cb7567111.png)

**Comment by 275873859** [comment]
OK,Thanks，I try again.
