### ISSUE TITLE
Output path breaks compile 

### ISSUE THREAD

**Issue by aishfenton** [bytedeco/javacpp#153]
When I run:
`java -jar javacpp.jar -d myOutputDir Processor`

JavaCPP correctly outputs the `jniProcessor.cpp` file to the myOutputDir. But then when the clang++ command runs it bombs out with 

```clang: error: no such file or directory: 'myOutputDir/jniProcessor.cpp```

Having a look at how Builder works, I see that the compile method sets it's working directory to outputPath. But then its given sources also have the output path prefixed to them (i.e. it ends up looking for `myOutputPath/myOutputPath/jniProcessor.cpp`)

**Comment by saudet** [comment]
Fixed! Thanks for reporting

**Comment by saudet** [comment]
Fix is in version 1.3.1. Enjoy!
