### ISSUE TITLE
Couldn't destroy threadgroup

### ISSUE THREAD

**Issue by lacic** [bytedeco/javacpp#157]
Hi, not sure if this is the right place to post this, but while using the [deeplearning4j framework](https://github.com/deeplearning4j/deeplearning4j) and the mvn exec:java command from the terminal I get a warning which could be a javacpp issue:

**[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup**

The warnings can be reproduced by pulling my [git repo](https://github.com/lacic/dl4j-2548) and runing **EvaluationExampleCorrect** from the terminal via the mvn exec:java command:

**mvn exec:java -Dexec.mainClass="com.issue2548.EvaluationExampleCorrect"**

This should produce warnings about not being able to destroy a threadgroup. Here is also a [gist](https://gist.github.com/lacic/80fdec1c3cc7928280f5829faa0edb9d) of the output.

I'm running this under Ubuntu 16.04.1 and java version "1.8.0_101"

**Comment by saudet** [comment]
Looks like an issue with NativeRandomDeallocator, not JavaCPP. Actually, using JavaCPP's deallocator thread instead should solve this issue. @raver119 Do you see any reason why this wouldn't work?

**Comment by raver119** [comment]
Hmm, if that's NativeRandomDeallocator then i'll take care of it. However i hadn't saw such messages even once.

As of JCPP deallocator use: there's also CUDA involved.
