### ISSUE TITLE
Question: Vector of unsigned char?

### ISSUE THREAD

**Issue by ergpudb** [bytedeco/javacpp#159]
I have a method that returns a std::vector<uint8_t> (vector of unsigned char). Is there a way to get JavaCPP to turn this into a byte array? I tried:

`@StdVector public native byte[] getVarBytes(@Cast("size_t") long index);`

But I get:

`no matching function for call to ‘VectorAdapter<signed char>::VectorAdapter(std::vector<unsigned char>)`

I've also tried:

`@StdVector @Cast("std::vector<int8_t>") public native byte[] getVarBytes(@Cast("size_t") long index);`

which adds a bunch of more errors, and:

`@Adapter("VectorAdapter<uint8_t>") public native byte[] getVarBytes(@Cast("size_t") long index);`

which gives:

`conversion from ‘VectorAdapter<unsigned char>’ to ‘signed char*’ is ambiguous`

What is the best way to make this work (preferably without changing the C++ header)? Is there any way to tell the VectorAdapter to cast each value in the vector to a different type (in this case, signed char)?

**Comment by saudet** [comment]
What you're missing is just a cast for byte[]:
```java
@Adapter("VectorAdapter<uint8_t>") @Cast("uint8_t*") native byte[] getVarBytes(@Cast("size_t") long index);
```
But we could also simply do:
```java
@StdVector @Cast("uint8_t*") native byte[] getVarBytes(@Cast("size_t") long index);
```
Samuel
