### ISSUE TITLE
GetPrimitiveArrayCritical option for byte array push

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp#16]
Hello , there can be an option on JavaCPP.
That can pass parameter without copying.
Example like :

void doOperation(@Critical byte bigdata[]) {
    ... this byte array will be on C++ side without copying.
}

**Comment by saudet** [comment]
That's for a use case where direct NIO buffers are out of the question?

**Comment by saudet** [comment]
It's a good idea though, thanks for mentioning it! And it shouldn't be too hard to implement, so would you like to give it try?

**Comment by jduke32** [comment]
what kind of help you want?

**Comment by saudet** [comment]
For updating the code in `Generator`, and maybe writing a unit test to make sure it actually works.

**Comment by jduke32** [comment]
did you look at ANTLR4 ?

**Comment by saudet** [comment]
Yes, it still only supports context-free parsing, so it doesn't work well
with C++. What does that have to do with GetPrimitiveArrayCritical though?

**Comment by jduke32** [comment]
it can be good for video processing.
passing images or audio without "copying"

**Comment by jduke32** [comment]
memorymappedfile can be solution for that also ?

**Comment by saudet** [comment]
Direct NIO buffers support all that, so why not use use those?

**Comment by aishfenton** [comment]
A use-case for a GetPrimitiveArrayCritical over a direct buffer is that the direct buffer is very slow to access from the Java side (or at least, that's my understanding). So if you have code that needs to access the array at frequently from both the native and Java ends, then GetPrimitiveArrayCritical seems like the best bet (as long as you're ok with pausing the GC).

**Comment by saudet** [comment]
@aishfenton That's not usually the case, no:
http://web.archive.org/web/20111117132310/http://blog.vlad1.com/2011/10/05/looking-at-java-nio-buffer-performance/

**Comment by vincent-grosbois** [comment]
Hi
as discussed in #253 I'll try to implement it, but what do you think would be best?
I can  add a new  flag in the methodInfo instance or somewhere else (ie a global config) ?

**Comment by saudet** [comment]
It can be both, like `@NoException`.

**Comment by vincent-grosbois** [comment]
where in the code do you see that @NoException can be setup for all the methods?

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/annotation/NoException.java

**Comment by vincent-grosbois** [comment]
I'm not sure I follow...
it seems the annotation can be added for types and method
What I'm wondering is, is there a way to globally add this annotation for all objects in the code that is parsed?

**Comment by vincent-grosbois** [comment]
Here's a PR for the annotation: https://github.com/bytedeco/javacpp/pull/254

**Comment by vincent-grosbois** [comment]
If there is no global toggle, then how could it work for the MKL binding for instance?
For instance when generating the MKL java wrapper, everything is generated automatically as far as I know.
How could it be made possible that all the methods are now automatically generated with _Get/ReleasePrimitiveArrayCritical_ ? For MKL is this sure that it is the correct choice in all cases

**Comment by saudet** [comment]
We could put it here alongside @NoException:
https://github.com/bytedeco/javacpp-presets/blob/master/mkl/src/main/java/org/bytedeco/javacpp/presets/mkl_rt.java#L54

**Comment by saudet** [comment]
Whether this what you want or not is up to you!

**Comment by vincent-grosbois** [comment]
As this is completely blocking the JVM during a call, now I'm having second-thoughts about putting this as a default for MKL...
We'll do tests on our side and get back to you ;) at worst it's still possible for anyone to have a custom MKL preset where the @ForceCritical tag is there by default

**Comment by saudet** [comment]
It's probably not a good default, no, but having it as an option so we can test it is good.

**Comment by saudet** [comment]
Enhancement included in JavaCPP 1.4.3! Thanks again for the contribution @vincent-grosbois.

**Comment by Hamlin-Li** [comment]
> A use-case for a GetPrimitiveArrayCritical over a direct buffer is that the direct buffer is very slow to access from the Java side (or at least, that's my understanding). So if you have code that needs to access the array at frequently from both the native and Java ends, then GetPrimitiveArrayCritical seems like the best bet (as long as you're ok with pausing the GC).

I hope [Region Pinning in JDK](https://bugs.openjdk.java.net/browse/JDK-8276094) may help eliminate or alleviate this problem in the future.
