### ISSUE TITLE
Question: warning about JavaCPP_getPointerOwner

### ISSUE THREAD

**Issue by ergpudb** [bytedeco/javacpp#160]
I'm using the Maven javacpp 1.3.1 plugin to handle generation/compilation of a C++ wrapper. Everything seems to work fine, but during the build g++ throws a warning:

....cpp:351:31: warning: ‘void* JavaCPP_getPointerOwner(JNIEnv*, jobject)’ defined but not used [-Wunused-function]

Is there something I need to do to get rid of this warning? Should it just be ignored?

**Comment by saudet** [comment]
It happens sometimes, but it's harmless. If you have a fix for it though, please send a pull request! Thanks

**Comment by saudet** [comment]
Fixed in the newly released version 1.4. Thanks for the feedback!
