### ISSUE TITLE
moderngpu preset request

### ISSUE THREAD

**Issue by archenroot** [bytedeco/javacpp#161]
First of all big thanks for this project! I use it primarily for image processing with openCV, but as I do also other stuff, I want to ask if it is possible to support some other CUDA related stuff, especially project https://github.com/moderngpu/moderngpu

Any help or suggestion how to start?

**Comment by saudet** [comment]
Sure, please start here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by saudet** [comment]
Actually, "It is a header-only C++ library written for CUDA", so it might be hard/impossible to create useful presets as it is now. Try to do something like with Thrust, as explained here:
https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA
