### ISSUE TITLE
Wrong function pointer definition

### ISSUE THREAD

**Issue by Arcnor** [bytedeco/javacpp#162]
The following C++ definition:
```cpp
const char* (*GetClipboardTextFn)();
```
...creates the following Java definition:
```java
public static class @Cast("const char *") GetClipboardTextFn extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public @Cast("const char *") GetClipboardTextFn(Pointer p) { super(p); }
    protected @Cast("const char *") GetClipboardTextFn() { allocate(); }
    private native void allocate();
    public native @Cast("const char*") BytePointer call();
}
```

Both the `@Cast` on the class and the ones on the constructors make this impossible to compile.

I've fixed this in my `InfoMap` in the meantime by doing `infoMap.put(new Info("char* (*)()").pointerTypes("GetClipboardTextFn"))`, which might also be a bug? (There is no way of referencing this that I can see other than `char* (*)()`, but that can obviously match with multiple functions)

**Comment by saudet** [comment]
How did you generate that? When I try this typedef:
```java
typedef const char* (*GetClipboardTextFn)();
```
The output is as follows and compiles fine:
```java
public static class GetClipboardTextFn extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GetClipboardTextFn(Pointer p) { super(p); }
    protected GetClipboardTextFn() { allocate(); }
    private native void allocate();
    public native @Cast("const char*") BytePointer call();
}
```

**Comment by Arcnor** [comment]
I've checked the code, and `typedef` has special code, so you won't get the `@Cast`.

This comes from here: https://github.com/ocornut/imgui/blob/master/imgui.h#L761

**Comment by saudet** [comment]
Still doesn't happen here. I get this:
```java
public static class GetClipboardTextFn_Pointer extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GetClipboardTextFn_Pointer(Pointer p) { super(p); }
    protected GetClipboardTextFn_Pointer() { allocate(); }
    private native void allocate();
    public native @Cast("const char*") BytePointer call(Pointer user_data);
}
@MemberGetter public native GetClipboardTextFn_Pointer GetClipboardTextFn();
```

**Comment by Arcnor** [comment]
Ok, my original report seems wrong. What I'm really getting in Java is:
```java
    public static class @Cast("const char*") BytePointer_GetClipboardTextFn extends FunctionPointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public    @Cast("const char*") BytePointer_GetClipboardTextFn(Pointer p) { super(p); }
        protected @Cast("const char*") BytePointer_GetClipboardTextFn() { allocate(); }
        private native void allocate();
        public native @Cast("const char*") BytePointer call();
    }
    @MemberGetter public native @Cast("const char*") BytePointer_GetClipboardTextFn GetClipboardTextFn();
```
... so `BytePointer_` is being appended. Since you're not getting it, I can upload the project I'm using for the generation (the mappings for imgui), it will probably be easier to see it there.

**Comment by Arcnor** [comment]
https://expirebox.com/download/efce5caa04c94eb8c9c481b7a1016a56.html contains the bindings, hopefully you should be able to just do "mvn clean package" and the error will show.

**Comment by saudet** [comment]
Ah, wait a minute, I had tried the one with the `void*` argument. Ok, without the `void*` argument, then it outputs weird, I see.

**Comment by saudet** [comment]
I've fixed this in the commit above. Thanks for reporting!

**Comment by saudet** [comment]
And now part of JavaCPP as of version 1.3.2. Thanks again for the feedback!
