### ISSUE TITLE
gcc complains on SharedPtrAdapter template

### ISSUE THREAD

**Issue by CasperReduct** [bytedeco/javacpp#166]
Hi, gcc complaint on SharedPtrAdapter template - "operator const T*() { return sharedPtr.get(); }"
.......
jniSomeLibrary.cpp:484:5: error: 'SharedPtrAdapter<T>::operator const T*() [with T = const somenamespace:MyClass]' cannot be overloaded
     operator const T*() { return sharedPtr.get(); }
     ^
...: with 'SharedPtrAdapter<T>::operator T*() [with T = const somenamespace:MyClass]'
     operator T*() {
     ^

.h file
std::shared_ptr< MyClass const > func();

Code generated from InfoMapper:
 public native @Const({false, true}) @SharedPtr MyClass func();

jni cpp code:
SharedPtrAdapter< ::somenamespace::MyClass const  > radapter(ptr->func()); <<--exception goes from here

1.If i commented line: operator const T*() { return sharedPtr.get(); } all works fine, but sadly i can't change template of SharedPtrAdapter
2.In InfoMapper class i can't find instruction to remove '@Const' annotation
3.Also i've tried add new adapter and it looks like works, but  but i faced with another problem in InfoMapper, but it's another story )

**Comment by saudet** [comment]
I've included a fix for that in the last commit above. Thanks for reporting!

**Comment by saudet** [comment]
And it's now part of JavaCPP 1.3.2. Thanks again for reporting!
