### ISSUE TITLE
Set single cache dir

### ISSUE THREAD

**Issue by mabruce** [bytedeco/javacpp#167]
I like the idea of caching since I package my jar with 250 MB of associated libraries that change very rarely, and the extract procedure is rather slow on Windows (I've been stuck with version 0.11 for various reasons). However, my jar name does change frequently (monthly versioning) so I don't particularly want the cache organized by jar.

Any objections to adding functionality to the Loader that would cache everything together in a single folder? I did a quick mod where it can be optionally set through either Loader.load or directly through a static method. If not manually set, then the existing cache dir methods are used.

**Comment by saudet** [comment]
I'm not sure I understand what the issue is, but sure send a pull request
with the proposed changes. I guess we should use a new system property?

**Comment by mabruce** [comment]
Not so much an issue as an enhancement - it would take advantage of new caching behavior, but not segregate by jar name so that a user's cache dir doesn't fill up over time with new versions. When you've got a lot of data, duplication gets pricey.

Would a system property or a static call be better?

**Comment by saudet** [comment]
I'd go with "org.bytedeco.javacpp.cachedir.nosubdir", what do you think? At least it associates it with "org.bytedeco.javacpp.cachedir"...

**Comment by saudet** [comment]
The new system property is included JavaCPP 1.3.2. Thanks for the feedback!
