### ISSUE TITLE
javacpp ffmpeg build with MMAL

### ISSUE THREAD

**Issue by emilio1986** [bytedeco/javacpp#168]
Hello,

Right now there is no hardware acceleration in compiled ffmpeg preset (1.3). This cause very big delay during video udp grabbing using FFMPEG on arm processor (RPI 3).

It is possible to compile FFMPEG with MMAL acceleration support that decrease a lot the latency. I check this using FFPLAY.

Here is the flags that should be used.
[https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=144242](url)

Is it possible to create OpenCV & FFMPEG presets that support MMAL acceleration?

**Comment by saudet** [comment]
Sure, could you send a pull request with the necessary changes?

**Comment by saudet** [comment]
I see that you already sent pull bytedeco/javacpp-presets#388 for this, so I am closing this. Thanks for the contribution!

As mentioned in the comments there though, before we merge this, it would be great if we could confirm that MMAL-enabled binaries still work when the hardware is not present.
