### ISSUE TITLE
Question: how do I access Pointer data?

### ISSUE THREAD

**Issue by mattdibi** [bytedeco/javacpp#172]
I'm trying to access a RealSense camera's frame. As a reference I've used che c++ code interfacing with Opencv

```cpp
Mat depth(Size(ImageWidth, ImageHeight), CV_16U , (uchar *)dev->get_frame_data(rs::stream::depth), Mat::AUTO_STEP);
```
But when I try the same in Java I get this error:
```sh
TestConnection.java:57: error: no suitable constructor found for Mat(Size,int,Pointer)
        Mat depth = new Mat(sz, CvType.CV_16U ,device.get_frame_data(RealSense.depth));
                    ^
    constructor Mat.Mat(int,int,int) is not applicable
      (argument mismatch; Size cannot be converted to int)
    constructor Mat.Mat(Size,int,Scalar) is not applicable
      (argument mismatch; Pointer cannot be converted to Scalar)
    constructor Mat.Mat(Mat,Range,Range) is not applicable
      (argument mismatch; Size cannot be converted to Mat)
```

because device.get_frame_data() returns a Pointer. What can I do to access the data of the Pointer?

**Comment by saudet** [comment]
Maybe you could do the same thing as in https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/RealSenseFrameGrabber.java ?

**Comment by mattdibi** [comment]
I'm sorry. I haven't looked hard enough for a solution before asking you. Anyway thanks a lot. This is exactly what I needed! =D
