### ISSUE TITLE
Compatabilty for Mat (opencv) and Mat (javacv)

### ISSUE THREAD

**Issue by Inumanoj** [bytedeco/javacpp#18]
I am building an Android app utilizing 2 parts.

takes videos from camera and processes them.
takes stored videos and analyses them frame by frame.
I had already built part 1. of the app with opencv. It was later that I realised that opencv does not support stored video processing. I found your library made use of the Framegrabber to grab all frames, the couldn't process them with the same code that i used for direct cam video (opencv). Hence I rewrote the code in javacv which works amazingly well. So, thanks a lot for that.

THE PROBLEM. there is a part of the code - delaunay triangulation which is written in native ndk with opencv. I have a list of points which i convert to mat and send them into ndk. process them . get a Mat as output and convert it into list of points again..

I cannot, by my understanding, use javacv in a similar fashion as its Mat object not a native object. Also weirdly when I did find a work around to it. I realise that I cannot create opencv Mat objects when I use javacv in the app. I get an unsatisfied linker error for the opencv Mat, which has no errors and works when there are no javacv objects in activity/app.

Is there any way I can avoid re-writing the code? Can I use opencv Mat when I use javacv in the app, if so would you know why I receive a unsatisfied linker error and is there a way to avoid it? Or is there a way to push javacv Mat into ndk in a similar fashion as opencv (referencing its native address) and avoid reconstructing the Mat object in ndk.

**Comment by saudet** [comment]
It's possible to pass around raw pointers between the two wrappers of Mat, there's an example of this here in issue #4.

But if all that you need is to map a native function to a Java method, we can do that with JavaCPP. These resources should help you get there before long:
https://github.com/bytedeco/javacpp#accessing-native-apis
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

Let me know if that answers your questions or not!

**Comment by Inumanoj** [comment]
Thanks a lot! It did help sort my problem out!
