### ISSUE TITLE
JavaCPP java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by acekillersg** [bytedeco/javacpp#183]
When I clone the latest JavaCPP into my local folder and execute "mvn clean install", there are some errors like follows in the test phases:
```
Loader
4 2 1
FloatPointer
Size: 26843545
java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(26843545): totalBytes = 921M, physicalBytes = 101M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107439716 107374180
BytePointer
java.lang.OutOfMemoryError: Cannot allocate new BytePointer(107374182): totalBytes = 921M, physicalBytes = 98M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107390566 107374182
Pointer
103227392
8589934592
67452928
IntPointer
java.lang.OutOfMemoryError: Cannot allocate new IntPointer(26843545): totalBytes = 921M, physicalBytes = 98M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107439716 107374180
DoublePointer
java.lang.OutOfMemoryError: Cannot allocate new DoublePointer(13421772): totalBytes = 921M, physicalBytes = 98M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107505248 107374176
LongPointer
java.lang.OutOfMemoryError: Cannot allocate new LongPointer(13421772): totalBytes = 921M, physicalBytes = 98M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107505248 107374176
CharPointer
java.lang.OutOfMemoryError: Cannot allocate new CharPointer(53687091): totalBytes = 921M, physicalBytes = 98M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107406950 107374182
Deallocator
ShortPointer
java.lang.OutOfMemoryError: Cannot allocate new ShortPointer(53687091): totalBytes = 921M, physicalBytes = 97M
java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes = 921M + 102M > maxBytes = 1G
107406950 107374182
```
As the build finally succeeds, so it seems this error does not affect the usage of JavaCPP. But may I know how to resolve it and whether it will affect other usage like in the javacpp-presets? Thanks in advance.

**Comment by saudet** [comment]
It shouldn't affect general usage, no. Which JDK are you using BTW? I know
this happens with IBM JDK, but I don't know why. Garbage collection seems
to work differently there.

**Comment by acekillersg** [comment]
Hi @saudet I tried both Oracle JDK and OpenJDK on both Centos 7 and Ubuntu 16.04. This error occurred everytime.

Should it be the maximum heap size limit or the maximum allocation limit problem? It's really annoying tbefore resolving this issue. Thanks

**Comment by saudet** [comment]
Oh, the build succeeds? Yes, that's normal. Those are caused on purpose to
make sure they work.

**Comment by acekillersg** [comment]
@saudet so you mean those testing codes are used on purpose to find the maximum size  of JVM allocation limit? If so, this is not an error actually, right?

**Comment by saudet** [comment]
We don't need to worry about on-heap memory, but we need to worry about off-heap memory.

**Comment by acekillersg** [comment]
@saudet so it can be resolved by setting larger off-heap memory size by "-XX:MaxDirectMemorySize=N" JVM option? But it seems still not work, a little weird.

**Comment by saudet** [comment]
Can you clarify the issue that you are facing?

**Comment by acekillersg** [comment]
@saudet as posted at the very beginning, there are some java.lang.outOfMemoryError exceptions when I try to execute "mvn clean install" for JavaCPP source code. Though the build succeeds in the end, but I want to know whether this is a program bug, or it is supposed to run like this, or it is just JDK's own problem? Thanks.

**Comment by acekillersg** [comment]
@saudet Thanks a lot!
