### ISSUE TITLE
powerpc platform args

### ISSUE THREAD

**Issue by vb216** [bytedeco/javacpp#187]
In trying to cross compile a powerpc build, I get something a little strange, example from libfreenect

[INFO] Compiling /home/travis/build/vb216/javacpp-presets/libfreenect/target/classes/org/bytedeco/javacpp/linux-ppc64le/libjnifreenect.so
[INFO] g++ -I/home/travis/build/vb216/javacpp-presets/libfreenect/cppbuild/linux-ppc64le/include/ -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux /home/travis/build/vb216/javacpp-presets/libfreenect/target/classes/org/bytedeco/javacpp/jnifreenect.cpp -mcpu=power8 -m64 -O3 -s -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -Wall -fPIC -shared -o libjnifreenect.so -L/home/travis/build/vb216/javacpp-presets/libfreenect/cppbuild/linux-ppc64le/lib/ -Wl,-rpath,/home/travis/build/vb216/javacpp-presets/libfreenect/cppbuild/linux-ppc64le/lib/ -lfreenect_sync -lfreenect 
g++: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
/home/travis/build/vb216/javacpp-presets/libfreenect/target/classes/org/bytedeco/javacpp/jnifreenect.cpp:1:0: error: bad value (power8) for -mtune= switch
 // Generated by JavaCPP version 1.3.3-SNAPSHOT: DO NOT EDIT THIS FILE

I'm building by:
mvn install -Djavacpp.platform=linux-ppc64le -Djavacpp.platform.compiler=powerpc64le-linux-gnu-g++

And it looks like its picking up args from linux-ppc64 properties out of these three:
linux-ppc64le-cuda.properties:platform.compiler.default=-Xcompiler=-mcpu=power8,-m64,-O3 -Xlinker=-s
linux-ppc64le.properties:platform.compiler.default=-mcpu=powerpc64le -m64 -O3 -s
linux-ppc64.properties:platform.compiler.default=-mcpu=power8 -m64 -O3 -s

I tried grepping the project itself for this with no joy, so I guess its passed / detected - so I wonder if something going wrong in that process? I remember thinking there was a similar issue with the linux-armhf properties a while ago but never dug into it. 

Asking as the cross compiler for ubuntu 14.04 is gcc-4.8 and doesn't like power8 as an argument (https://travis-ci.org/vb216/javacpp-presets/jobs/238732766). The cppbuild steps work ok with a bit of tweaking, so just need to solve last hurdle

**Comment by saudet** [comment]
Well, it's not executing powerpc64le-linux-gnu-g++, so that's a problem,
but it should...

**Comment by vb216** [comment]
AH missed that.. think I've seen the problem in the travis build.. will check

**Comment by vb216** [comment]
Bingo. I'd messed up the declaration of javacpp.platform.compiler in the travis file, fixed now and libfreenect has uploaded a ppc64le snapshot :)
