### ISSUE TITLE
How can I fill an image?

### ISSUE THREAD

**Issue by aghasemi** [bytedeco/javacpp#19]
Hi,

May I please ask how I can fill an image I have created with `new opencv_core.Mat`? Suppose for example I want to write a random value to every pixel location.

Thanks a lot

**Comment by saudet** [comment]
There's an example exactly like that here:
http://bytedeco.org/news/2014/12/23/third-release/

**Comment by aghasemi** [comment]
The indexer created by createIndexer does not have a put method in my code. I use Maven like this:

```
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>2.4.11-0.11</version>
        </dependency>
        
```

**Comment by saudet** [comment]
You need to cast the `Indexer` to some concrete type.
