### ISSUE TITLE
continuous memory leak 

### ISSUE THREAD

**Issue by youzp** [bytedeco/javacpp#190]
I checked the c++ code with valgrind and not found any memory leak，
so I suspect that there is no way to use javacpp, resulting in a continuous memory leak. 
Is there any problem with my code below?
```cpp
std::string update(const std::string& parm1,
                             const int64_t& parm2,
                             const std::string& parm3,
                             const std::string& parm4,
                            const std::string& parm5);`
```
```java
@Platform(value = "linux-x86_64",
        compiler = "cpp11",
        define = "NDEBUG",
        include = "MyAlgo.h",
        link = "CacheAlgo")
@Namespace("algo")
public class CacheAlgoImpl implements CacheAlgo {
    private static MyAlgo algo_ = new MyAlgo(100, 100);

    private static class MyAlgo extends Pointer {
            static {Loader.load(); }

        public MyAlgo(int expire_time_s, int list_max_len) {
            allocate(expire_time_s, list_max_len);
        }

        private native void allocate(int expire_time_s, int list_max_len);

        public native @StdString
        String update(@StdString String parm1,
                      @Const @ByRef long parm2,
                      @StdString String parm3,
                      @StdString String parm4,
                      @StdString String parm5);
    }
    
    @Override
    public String getMyAlgo(String parm1,
                            long parm2,
                            String parm3,
                            String parm4,
                            String parm5) {
        return algo_.update(parm1,
                            parm2,
                            parm3,
                            parm4,
                            parm5);
    }}
```

**Comment by saudet** [comment]
What happens if you call `System.gc()`?

**Comment by youzp** [comment]
@saudet  call System.gc() operation every 30,000 requests, but the memory is still growing slowly.

**Comment by thumlx12** [comment]
@youzp seems like your problem is very similar to [this one](https://github.com/bytedeco/javacpp/issues/182). We used to meet that memory problem before.
You can try to use malloc_trim(0) to implement a function like System.gc(), which was useful in my last experience encountering this problem.
According to my knowledge, this problem could be caused by the mechanism of glib of Linux which will not release small objects' memory immediately. But malloc_trim(0) in malloc.h could force the glib not to do that.

**Comment by youzp** [comment]
@thumlx12 my c++ code use some STL containers(std::unordered_map/std::forward_list) and a lot of new and delete operations with smart pointer(std::make_shared/std::shared_ptr/std::unique_ptr). 
All the places after the delete operation need to add malloc_trim (0)?

**Comment by thumlx12** [comment]
@youzp I remember calling malloc_trim(0) once would suffice. You can have try. If not, try add it multiple times.
You can refer [here](https://github.com/bytedeco/javacpp-presets/issues/423) for debug inspiration if this solution doesn't work out.

**Comment by youzp** [comment]
@thumlx12 It works when call malloc_trim(0) after every request, memory is smooth and little fluctuation,but the CPU usage has increased 5~8 times,malloc_trim(0)  is very CPU consumption. 
@saudet Maybe this is not a javacpp problem, frequent new and delete operations in c++ code will lead to memory cannot be released  to OS immediately. In this case it should use a memory pool.

**Comment by saudet** [comment]
glibc already uses a memory pool. It will allocate memory out that. Memory usage won't continuously increase.

**Comment by youzp** [comment]
@saudet ok,now there seems to be no better way to solve this growing memory problem, what better advice?

**Comment by saudet** [comment]
Try to reduce the maximum memory, that's how Java works.

**Comment by youzp** [comment]
@saudet @thumlx12  now i use jemalloc to replace malloc/free in glibc, the growth of memory fragmentation has been well controlled and cpu performance has also been greatly improved.

cd jemalloc-5.0.1
./configure && make
export LD_PRELOAD=/xxx/libjemalloc.so.2

**Comment by saudet** [comment]
Interesting, too bad it's not as easy to use on Windows...

**Comment by saudet** [comment]
In any case, https://github.com/bytedeco/javacpp/commit/86e4d57e9ac0bc94f0b836e0c08e3a45f362148f should take care of the "leak", so I'm marking this as a duplicate of https://github.com/bytedeco/javacpp-presets/issues/423
