### ISSUE TITLE
Explore the possibility of removing . from manifest class path

### ISSUE THREAD

**Issue by xuzhongxing** [bytedeco/javacpp#192]
Adding . to class path implicitly could lead to mysterious class path problems. Consider the possibility of removing it.

**Comment by saudet** [comment]
If we do so, we would need a way to prevent beginners from getting confused between ';' and ':' when trying out simple examples on a different platforms. Would you have any ideas about how to resolve that another way?

**Comment by saudet** [comment]
Actually, this might be an additional area where a runtime API (pull #138) would come in handy.

@cypof Are you still planning to work on this?

**Comment by saudet** [comment]
It's done, I've removed "." from the class path! 

I've upgraded the build process so it's now possible to compile and run classes from source this way with only a single command to make it easy for new users, without the need to have "." in the class path:
```bash
java -jar javacpp.jar NativeLibrary.java -exec
```

**Comment by saudet** [comment]
Now released in JavaCPP 1.4.4! Thanks for your patience
