### ISSUE TITLE
How do the types before Java and c++ correspond?

### ISSUE THREAD

**Issue by daoqiang** [bytedeco/javacpp#196]
The structure is used in c++，But I didn't find the structure in the javacpp source file，Only the Pointer。
Where do you have detailed examples of javacpp usage?
Thank you ！

**Comment by saudet** [comment]
That would be the presets:
https://github.com/bytedeco/javacpp-presets/
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by daoqiang** [comment]
ok，Now what should the structure replace, and I tried to use class or extends struct without success

**Comment by daoqiang** [comment]
https://groups.google.com/forum/#!topic/javacpp-project/IRtPLyI8TiM，You are busy，Thank  you

**Comment by saudet** [comment]
Could you explain a bit more what you are trying to do and the errors you get?

**Comment by daoqiang** [comment]
A class extends Pointer as a pointer to the structure, passed to c++, where c++ is 0 or null。In the meantime, it doesn't have any err。It can run, but the value is incorrect

**Comment by daoqiang** [comment]
![n cpqmc_3ca hp2s7o2s](https://user-images.githubusercontent.com/16305190/28488997-28ffc624-6eea-11e7-8391-534ac12852f9.png)

**Comment by saudet** [comment]
Try to follow the sample code in the README.md file or use the Parser as
with the presets.

**Comment by saudet** [comment]
I'm assuming the documentation I gave you above was clear enough, but please let me know if you still have any questions!
