### ISSUE TITLE
Working with already compiled shared lib?

### ISSUE THREAD

**Issue by magick93** [bytedeco/javacpp#199]
Hello

Correct me if I am wrong, but it seems JavaCpp combines compilation of both java and c++ in a single project. 

I have a c++ project - and have a rather elaborate build process. I am looking to wrap this cpp library (.so) with Java. 

Do you have any documentation on how to do that?

I can certainly add the .h file to the JavaCpp project, but it doesnt make sense - in my situation - to combine the cpp project with the java project. The two do need to be kept separate. 

Any guidance is appreciated.

**Comment by saudet** [comment]
Check the presets for that:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
