### ISSUE TITLE
poor error handling x64,x86 jvm dedection

### ISSUE THREAD

**Issue by jduke32** [bytedeco/javacpp#20]
Hello , 
i set x64 jvm as a default JAVA_HOME

On MingW , i tried to generate dll  , 
i got error like shown below:

[ERROR] Failed to execute goal org.bytedeco:javacpp:0.12:build (generate-sources
) on project ffmpeg: Failed to execute JavaCPP Builder: Could not parse "libavut
il\avutil.h": File does not exist -> [Help 1]

Then i understand i am using x64 bit jvm.
I need to use x86 JVM
You need to show warning for 64 bit compiling , check for JAVA_HOME is x64 JVM
for x86 , check for JAVA_HOME x86

**Comment by saudet** [comment]
At build time, it doesn't matter, no. So we don't need to check for that.
Your issue is caused by something else.

**Comment by saudet** [comment]
I believe you simply forgot to set the `platform` system property to say "windows-x86"...
