### ISSUE TITLE
Generate "...-platform.jar"

### ISSUE THREAD

**Issue by arturo-eid** [bytedeco/javacpp#201]
I can compile any preset with the following command:
`mvn clean install --projects .,<preset_name>`

But the jar _<preset_name>-platform.jar_ is not generated. Is there any other command for this purpose?

**Comment by saudet** [comment]
One way would be as follows:
```bash
$ cd platform
$ mvn install --projects ../opencv/platform,../ffmpeg/platform,etc. -Djavacpp.platform.host
```

**Comment by arturo-eid** [comment]
Got it. Thank you
