### ISSUE TITLE
RoboVM MobiVM New fork

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp#203]
There is new fork and robovm is alive again.
But how can we use javacpp and javacpp-presets with robovm ?

**Comment by saudet** [comment]
Should be in the same way as before. Please follow the instructions and let
me know if something doesn't work.

**Comment by saudet** [comment]
I'm assuming that you've encountered no issues, but please let me know if this isn't the case!

**Comment by saudet** [comment]
FYI, we now also have [Gluon VM](http://gluonhq.com/products/mobile/vm/) that supports Java 9 and Android too! @johanvos has already contributed builds for OpenBLAS that work for both RoboVM and Gluon VM:
https://github.com/bytedeco/javacpp-presets/commit/53e93263a9cafe36af0a7afd872233d3318b7819
