### ISSUE TITLE
为什么没有org.bytedeco.javacpp.opencv_core这个包

### ISSUE THREAD

**Issue by WillWolfWang** [bytedeco/javacpp#204]
你好，我想问一下，这个包下的类要自己编译么？还是从其他途径获得？

**Comment by wongjoel** [comment]
The JavaCPP repository is for the JavaCPP project itself. If you are looking to use OpenCV via JavaCPP, the easiest way is to use the JavaCV (https://github.com/bytedeco/javacv) project which has all of the necessary presets, configuration and artifacts prebuilt.

**Comment by saudet** [comment]
Thanks for answering @wongjoel!
