### ISSUE TITLE
Unable to compile javacpp in Android Studio with gradle

### ISSUE THREAD

**Issue by Venzo92** [bytedeco/javacpp#205]
Im trying to implement javacpp into my project but i'm unable to finish the build,
i've also tried to open the sample project "javacpp-android-gradle" but it's not compiling too. 
In the gradle log i can succesfully read the paths, but i'm getting the following errors:

`OOOOOOO++++++++++++++OOOOOOO++++++++++++++OOOOOOO++++++++++++++OOOOOOO++++++++++++++
variant.name: release
C:\Users\Marsic1\AndroidStudioProjects\javacpp-android-gradle\app
C:\Users\Marsic1\AndroidStudioProjects\javacpp-android-gradle\app\build\intermediates\classes\release
C:\Users\Marsic1\AndroidStudioProjects\javacpp-android-gradle\app\src\main\jni
++javacpp file path:
C:\Users\Marsic1\AppData\Local\Android\Sdk\ndk-bundle

process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/armeabi/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/x86/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/mips/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/src/main/jni/jniMultiplyDemo.cpp', needed by `C:/Users/Marsic1/AndroidStudioProjects/javacpp-android-gradle/app/build/intermediates/ndkBuild/debug/obj/local/mips64/objs/jniMultiplyDemo/jniMultiplyDemo.o'.  Stop.
`

any idea how to fix?

**Comment by saudet** [comment]
@leak918, ideas?

In any case, try to use JavaCPP on the command line. We need someone to make a plugin for Gradle, so if you feel like making a contribution, it would be welcome!

**Comment by leaf918** [comment]
the reason for this is :
remove the auto generated cpp file first ,and run compile to generate javacpp bridge file,and add the generated cpp bridge file into the android.mk file.
there should be some smarter way to do this ,but I am good at android.mk writing ,so I update the project to cmake build way ,grant the pull request please ,and check it again.
@Venzo92

**Comment by saudet** [comment]
Thanks @leaf918! So, if we don't need to have a dummy .cpp file with CMake, could you remove it from your pull request https://github.com/bytedeco/sample-projects/pull/19?

**Comment by saudet** [comment]
Should be fixed now thanks to the pull request above from @leaf918!

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
