### ISSUE TITLE
best way to pass byte array from java to C++?

### ISSUE THREAD

**Issue by leaf918** [bytedeco/javacpp#206]
```java
public static String predict(byte[] nv21Bytes, int width, int height, Context mContext) {
        _**BytePointer bp = new BytePointer(nv21Bytes);
        bp.put(nv21Bytes, 0, nv21Bytes.length);
        _native.predictWithNV21(bp, width, height);**_
        return "";
    }

package vis.baidu.cpp;

import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.Namespace;
import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.StdString;


@Platform(include = "NativeLibrary.h")
@Namespace("NativeLibrary")
public class NativeLibrary {

    public static class NativeClass extends Pointer {
        static {
            Loader.load();
        }

        public NativeClass() {
            allocate();
        }

        private native void allocate();

        // to call the getter and setter functions
        @StdString
        public native String get_property();

        public native void set_property(String property);

        public native void predictWithNV21(BytePointer nv21Bytes, int width, int height);
    }

}
```
use the BytePointer to pass byte array to C++?

**Comment by saudet** [comment]
Yes, `BytePointer` is usually the more efficient abstraction, but passing `byte[]` directly might avoid allocating an additional buffer. And it depends on what you do with it in your native library.

**Comment by leaf918** [comment]
I need to read all the bytes ,bytes is image data(nv21),I will convert it and predict the content of the image .So should I allocate an buffer like this?
`        BytePointer bp = new BytePointer(nv21Bytes.length);
        bp.put(nv21Bytes, 0, nv21Bytes.length);
        _native.predictWithNV21(bp, width, height);`

while I can get nothing from the pointer:
`void predictWithNV21(const signed char *bytes, int width, int height) {
            char *tmpChar = "123456780987654321234567";
            if (bytes == nullptr) {
                LOGD("bytes pointer is NULL\n");
            }
            for (int i = 0; i < 15; ++i) {
                LOGD("char %i : %c %i\n", i, bytes[i], bytes[i]);
                LOGD("char2 %i : %c %i\n", i, tmpChar[i], tmpChar[i]);
            }
        }`

**Comment by leaf918** [comment]
it works ,thanks.
![image](https://user-images.githubusercontent.com/170311/32319869-ef33dc38-bff6-11e7-9e14-5ea055bc4b54.png)
