### ISSUE TITLE
Can I get the JNIEnv pointer from my c++ class?

### ISSUE THREAD

**Issue by leaf918** [bytedeco/javacpp#207]
like this.
![Uploading 1510815683685.jpg…]()

**Comment by leaf918** [comment]
![1510815683685](https://user-images.githubusercontent.com/170311/32878025-3dd74512-cadf-11e7-81e2-daab953d5d2a.jpg)

**Comment by saudet** [comment]
Yes, use the `@Raw(withEnv=true)` annotation on the native method declaration.
