### ISSUE TITLE
Cannot loading third party DLL 

### ISSUE THREAD

**Issue by phanthanhliem** [bytedeco/javacpp#21]
Hi,

I want to load a dll, named MathFuncsDll.dll, that I created by MS VC++ 2013.
### MathFuncsDll.h ######
#ifdef MATHFUNCSDLL_EXPORTS
#define MATHFUNCSDLL_API __declspec(dllexport) 
#else
#define MATHFUNCSDLL_API __declspec(dllimport) 
#endif

namespace MathFuncs
{
	// This class is exported from the MathFuncsDll.dll
	class MyMathFuncs
	{
	public:
		static MATHFUNCSDLL_API double Add(double a, double b);
		static MATHFUNCSDLL_API double Subtract(double a, double b);
		static MATHFUNCSDLL_API double Multiply(double a, double b);
		static MATHFUNCSDLL_API double Divide(double a, double b);
	};
}
###############

I then created a java file, named MathFuncs.java:
##### MathFuncs.java ########
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include="MathFuncsDll.h", link="MathFuncsDll")
@Namespace("MathFuncs")
public class MathFuncs {
	public static class MyMathFuncs extends Pointer {
		static { 	System.loadLibrary("jniMathFuncs"); }
		public MyMathFuncs() { allocate(); }
		private native void allocate();

		public native double Add(double a, double b);  
		public native double Subtract(double a, double b);  
		public native double Multiply(double a, double b);  
		public native double Divide(double a, double b);  
		
	}
	public static void main(String[] args) {
		MyMathFuncs mfdInstance = new MyMathFuncs();
		System.out.println("spiderDll.dll is successfully loading!!");
		System.out.println("3 x 4 = " + mfdInstance.Multiply(3,4));
	}
}

Then:
> javac -cp javacpp.jar MathFuncs.java
> java -jar javacpp.jar -d . -Xcompiler -L. MathFuncs

I got the error:
######
Microsoft (R) Incremental Linker Version 12.00.31101.0
Copyright (C) Microsoft Corporation.  All rights reserved.
/out:jniMathFuncs.dll
/ltcg
/dll
/implib:jniMathFuncs.lib
/OUT:.\jniMathFuncs.dll
MathFuncsDll.lib
jniMathFuncs.obj
LINK : fatal error LNK1181: cannot open input file 'MathFuncsDll.lib'
[Dynamic-linking native method java.lang.ProcessImpl.getExitCodeProcess ... JNI]
[Dynamic-linking native method java.lang.Shutdown.halt0 ... JNI]
#######

The question is Why javacpp.jar requires the input file MathFuncsDll.lib.
I did put the name of MathFuncsDll.dll in the annotation:
@Platform(include="MathFuncsDll.h", link="MathFuncsDll")

Could you please show me how to resolve this problem, please?
Thanks for your help.

Thanh Liem.

**Comment by saudet** [comment]
It's not required by JavaCPP, it's required by the Microsoft C++ compiler. If you do not have the .lib file, I'm afraid it's rather complicated to create one from a DLL file...

**Comment by phanthanhliem** [comment]
Yesss, it's work, in fact, what I've done is just to copy the MathFuncsDll.lib into the working folder.
So when calling a third party dll, we need to give 3 files: .h; .dll and .lib.

Thank for your quick answer.

**Comment by phanthanhliem** [comment]
But, by loading a .lib, we means "statically linking".
Is there a way to achieve "dynamically linking"?

**Comment by phanthanhliem** [comment]
Hi saudet, 
So what are the differences between @link and @preload in the Platform annotation.

**Comment by saudet** [comment]
It's explained in the docs here:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/annotation/Platform.html
