### ISSUE TITLE
Bindings for Qt?

### ISSUE THREAD

**Issue by oscarvarto** [bytedeco/javacpp#210]
Hi!

I wonder if someone has tried to use javacpp to generate Qt bindings. Is it possible?
Qt is very mature and has a lot of functionality.

**Comment by saudet** [comment]
Sure, it's possible, contributions are welcome :) If you'd like to give it a try, but are having any issues, please let me know.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/pull/674

Thanks to @freastro for starting work on this!
