### ISSUE TITLE
std::map<std::string,std::string> conversion of JavaCPP

### ISSUE THREAD

**Issue by jues** [bytedeco/javacpp#218]
I'm a newbie of JavaCPP, right now I've got a problem.

my TestLibrary.h:

    #include <string>
    #include <map>
    
    
        class TestClass {
            public:
                TestClass() {
                    property["a"]="b";
                }
                const std::map<std::string,std::string>& getMap(std::string str) { 
                    if (str == "a"){
                        return property; 
                    }
                }
                std::map<std::string,std::string> property;
        };

TestLibrary.java

    import org.bytedeco.javacpp.*;
    import org.bytedeco.javacpp.annotation.*;
    
    @Platform(include="TestLibrary.h")
    public class TestLibrary { 
        public static class TestClass extends Pointer {
            static { Loader.load(); }
            public TestClass() { allocate(); }
            private native void allocate();
    
            public static native @ByRef KeyValueMap getMap(String str);    
        }
    
    @Name("std::map<std::string,std::string>") public static class 
    KeyValueMap extends Pointer { 
         static { Loader.load(); } 
         public KeyValueMap(Pointer p) { super(p); } 
         public KeyValueMap()       { allocate();  } 
         private native void allocate(); 
    
         public native long size(); 
    
         @Index public native @StdString BytePointer get(@StdString 
    BytePointer i); 
         public native KeyValueMap put(@StdString BytePointer i, BytePointer 
    value); 
    } 
    
        public static void main(String[] args) {
            TestClass l = new TestClass();
            KeyValueMap m = l.getMap("a");
            System.out.println(m);
            //System.out.println(m.get("a"));
        }
    } 

when 

javac -cp javacpp.jar TestLibrary.java    
java -jar javacpp.jar TestLibrary

jniTestLibrary.cpp:2238:30: error: call to non-static member
      function without an object argument
        rptr = &::TestClass::getMap(ptr0);    
                ~~~~~~~~~~~~~^~~~~~

the code above is modified from the NativeLibrary example. But How to solve the compile problem?
And can I use `m.get("a")` like that?

**Comment by saudet** [comment]
There's a definition for `std::map<std::string,int>` here, for example:
https://raw.githubusercontent.com/bytedeco/javacpp-presets/master/caffe/src/main/java/org/bytedeco/javacpp/caffe.java

**Comment by saudet** [comment]
So, something like this for `std::map<std::string,std::string>` should work:
```java
@Name("std::map<std::string,std::string>") public static class StringStringMap extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public StringStringMap(Pointer p) { super(p); }
    public StringStringMap()       { allocate();  }
    private native void allocate();
    public native @Name("operator=") @ByRef StringStringMap put(@ByRef StringStringMap x);

    public native long size();

    @Index public native int get(@StdString BytePointer i);
    public native StringStringMap put(@StdString BytePointer i, @StdString BytePointer value);

    public native @ByVal Iterator begin();
    public native @ByVal Iterator end();
    @NoOffset @Name("iterator") public static class Iterator extends Pointer {
        public Iterator(Pointer p) { super(p); }
        public Iterator() { }

        public native @Name("operator++") @ByRef Iterator increment();
        public native @Name("operator==") boolean equals(@ByRef Iterator it);
        public native @Name("operator*().first") @MemberGetter @StdString BytePointer first();
        public native @Name("operator*().second") @MemberGetter @StdString BytePointer second();
    }
}
```
We can replace `BytePointer` with `String` and it should also work.

**Comment by jues** [comment]
Thank you very much!!!
