### ISSUE TITLE
How to map a String array?

### ISSUE THREAD

**Issue by jues** [bytedeco/javacpp#219]
I'm a newbie of JavaCPP, right now I've got a problem of mapping a Java string array to c++  

array in Java:  String[] strArr 

and the string array in c++ is std::string strArr[];

when it compiled, showing:
    Warning: The class java.lang.String[] does not map to any C++ type. Compilation will most likely fail.

How to achieve this?

**Comment by jues** [comment]
Shall I define a std::vector<std::string> named StringVector extends Pointer ?

**Comment by saudet** [comment]
`@StdString String` doesn't work?

**Comment by jues** [comment]
@StdString String is a string, I want a string array: String[]
I copied the code StringVector from https://raw.githubusercontent.com/bytedeco/javacpp-presets/master/caffe/src/main/java/org/bytedeco/javacpp/caffe.java
And It works fine...
And I wonder if there's another way to do it...

**Comment by saudet** [comment]
If you need a `std::vector<std::string>`, yes that works fine.

**Comment by jues** [comment]
Thank you very much!!!
