### ISSUE TITLE
Error with annotation

### ISSUE THREAD

**Issue by phanthanhliem** [bytedeco/javacpp#22]
Hi, 
I would like to create a file, named spider.java, from the spiderDll.h. 

Here is the Content of spiderDll.h
#ifndef SPIDERDLL_H
#define SPIDERDLL_H
#ifdef SPIDERDLL_EXPORTS
#define SPIDERDLL_API __declspec(dllexport)
#else
#define SPIDERDLL_API __declspec(dllimport) 
#endif

#include <vector>
#include <string>
#include <QString>
namespace spider
{
	class  spiderDll
	{
	public:
		SPIDERDLL_API spiderDll();
		SPIDERDLL_API std::vector<double>         getVectorDouble();
		SPIDERDLL_API std::vector<double*>        getVectorPointerDouble();		
		SPIDERDLL_API int                         getInt();
	private:
		std::vector<double>         vd;
		std::vector<double*>        vpd;	
		int                         i;
	};
}
#endif // SPIDERDLL_H

The content of spider.java is below:
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include={"spiderDll.h", "<vector>"}, link="spiderDll")
@Namespace("spider")
public class spider {
	public static class spiderDll extends Pointer {
		static { 
			System.loadLibrary("jnispider"); 			
		}
		public spiderDll() { allocate(); }
		
		// define allocator
		private native void allocate();

		// Method we want to use
		public native int getInt();
		public native @Adapter("VectorAdapter<double>") DoublePointer getVectorDouble();  
		public native @Adapter("VectorAdapter<VectorAdapter<double>>") DoublePointerVector getVectorPointerDouble();		
	}
	@Name("std::vector<double*>")
	public static class DoublePointerVector extends DoublePointer {
		public DoublePointerVector() {
			allocate();
		}

		public DoublePointerVector(long n) {
			allocate(n);
		}

		// this = (vector<double*>*)p
		public DoublePointerVector(DoublePointer p) {
			super(p);
		} 

		// this = new std::vector<double*>()
		private native void allocate(); 

		// this = new std::vector<double*>(n)
		private native void allocate(long n); 

		@Name("operator=")
		public native @ByRef DoublePointerVector copy(@ByRef DoublePointerVector x);
		public native long size();
		public native @Cast("bool") boolean empty();
		@Name("operator[]")
		public native @ByRef PointerPointer get(long n);
		public native @ByRef PointerPointer at(long n);
	}	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		spiderDll dllInstance = new spiderDll();		
		System.out.println("spiderDll.dll is successfully loading!!");
		System.out.println("getInt() = " + dllInstance.getInt());
		System.out.println("getVectorDouble() = " + dllInstance.getVectorDouble());
	}
}

There is no problem with the method getVectorDouble(). However,
when i try to map with the method getVectorPointerDouble(), by creating a new class DoublePointerVector extends DoublePointer, I got error like this:

#####
D:\LIEM\SPIDER\DLL Intergration\SpiderDll_woQStr>java -jar javacpp.jar -d . -Xco
mpiler -L. spider
Generating .\jnispider.cpp
Compiling .\jnispider.dll
cl "/IC:\Program Files\Java\jdk1.8.0_45\include" "/IC:\Program Files\Java\jdk1.8
.0_45\include\win32" .\jnispider.cpp -L. /W3 /Oi /O2 /EHsc /Gy /GL /MD /LD /link
 /OUT:.\jnispider.dll spiderDll.lib
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-L.'
jnispider.cpp
.\jnispider.cpp(206) : warning C4996: 'strcpy': This function or variable may be
 unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECUR
E_NO_WARNINGS. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\string.h(
112) : see declaration of 'strcpy'
.\jnispider.cpp(208) : warning C4996: 'strncpy': This function or variable may b
e unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SEC
URE_NO_WARNINGS. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\string.h(
195) : see declaration of 'strncpy'
.\jnispider.cpp(284) : warning C4996: 'strdup': The POSIX name for this item is
deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help f
or details.
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\string.h(
245) : see declaration of 'strdup'
.\jnispider.cpp(335) : error C3083: 'std': the symbol to the left of a '::' must
 be a type
.\jnispider.cpp(335) : error C2039: 'vector' : is not a member of 'spider'
.\jnispider.cpp(335) : error C2065: 'vector' : undeclared identifier
.\jnispider.cpp(335) : error C2062: type 'double' unexpected
.\jnispider.cpp(401) : error C3083: 'std': the symbol to the left of a '::' must
 be a type
.\jnispider.cpp(401) : error C2039: 'vector' : is not a member of 'spider'
.\jnispider.cpp(401) : error C2065: 'vector' : undeclared identifier
.\jnispider.cpp(401) : error C2062: type 'double' unexpected
.\jnispider.cpp(401) : error C2143: syntax error : missing ';' before '}'
.\jnispider.cpp(401) : error C2059: syntax error : ','
.\jnispider.cpp(402) : error C2143: syntax error : missing ';' before '{'
.\jnispider.cpp(402) : error C2447: '{' : missing function header (old-style for
mal list?)
.\jnispider.cpp(404) : error C2065: 'env' : undeclared identifier
.\jnispider.cpp(405) : error C2059: syntax error : 'if'
.\jnispider.cpp(405) : error C2143: syntax error : missing ';' before '{'
.\jnispider.cpp(405) : error C2447: '{' : missing function header (old-style for
mal list?)
.\jnispider.cpp(408) : error C2059: syntax error : 'for'
.\jnispider.cpp(408) : error C2143: syntax error : missing ')' before ';'
.\jnispider.cpp(408) : error C2143: syntax error : missing ';' before '<'
.\jnispider.cpp(408) : error C4430: missing type specifier - int assumed. Note:
C++ does not support default-int
.\jnispider.cpp(408) : error C2143: syntax error : missing ';' before '++'
....
########

I think the problem is the annotation. I don't really understand the meaning of them.
Do you have a tutorial of annotation?
And do you know what are the correct solution for this mapping?

Thanks for your support.

Thanh Liem.

**Comment by saudet** [comment]
`DoublePointerVector extends DoublePointer` isn't going to work. Try to use the `@StdVector` annotation on the method with `DoublePointer` as type.

**Comment by phanthanhliem** [comment]
Sorry, but how can I pass the DoublePointer as type to @StdVector.
I've tried several solutions, but it doesnt work, such that:
- @StdVector("DoublePointer")
- @StdVector<DoublePointer>
And I couldn't find any example.

I know that:
- With std::vector<double> , the below mapping works
public native @StdVector DoublePointer getVectorDouble(); 
- But with std::vector<double*>  ; i dont' know how to proceed.

Could you show me please? Thank for your helps.

**Comment by saudet** [comment]
There's one example here: https://github.com/bytedeco/javacpp-presets/blob/master/caffe/src/main/java/org/bytedeco/javacpp/caffe.java#L16260
```java
    public native @StdVector DoublePointer blob_loss_weights();
```

**Comment by saudet** [comment]
I see... I guess the closest example to that would be `StringVector` here:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/opencv_core.java#L74
```java
@Name("std::vector<cv::String>") public static class StringVector extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public StringVector(Pointer p) { super(p); }
    public StringVector(BytePointer ... array) { this(array.length); put(array); }
    public StringVector()       { allocate();  }
    public StringVector(long n) { allocate(n); }
    private native void allocate();
    private native void allocate(@Cast("size_t") long n);
    public native @Name("operator=") @ByRef StringVector put(@ByRef StringVector x);

    public native long size();
    public native void resize(@Cast("size_t") long n);

    @Index public native @Str BytePointer get(@Cast("size_t") long i);
    public native StringVector put(@Cast("size_t") long i, BytePointer value);

    public StringVector put(BytePointer ... array) {
        if (size() != array.length) { resize(array.length); }
        for (int i = 0; i < array.length; i++) {
            put(i, array[i]);
        }
        return this;
    }
}
```
This is automatically generated code, but we can modify it as is for other purposes too.

**Comment by phanthanhliem** [comment]
So what is the meaning of @StdVector DoublePointer?
To map "std::vector \<double\> " I used:
public native @StdVector DoublePointer getVectorDouble();
And it works.

But to map "std::vector \<double*\> ", a vector of double pointer, it can not be the same, doesn't it?

**Comment by phanthanhliem** [comment]
OK, so I return to the class DoublePointerVector, which will be implemented similarly the class StringVector.

@Name("std::vector<double*>")
	public static class DoublePointerVector extends DoublePointer {
		static { Loader.load(); }
		
		public DoublePointerVector() {
			allocate();
		}

		public DoublePointerVector(long n) {
			allocate(n);
		}

		// this = (vector<double*>*)p
		public DoublePointerVector(DoublePointer p) {
			super(p);
		} 

		// this = new std::vector<double*>()
		private native void allocate(); 

		// this = new std::vector<double*>(n)
		private native void allocate(long n); 

		@Name("operator=")
		public native @ByRef DoublePointerVector copy(@ByRef DoublePointerVector x);

		public native long size();

		public native @Cast("bool")
		boolean empty();

		@Name("operator[]")
		public native @ByRef PointerPointer get(long n);

		public native @ByRef PointerPointer at(long n);
	}

**Comment by saudet** [comment]
Looks like a namespace issue... Check the generated C++ code at those lines to figure out what is wrong.

**Comment by phanthanhliem** [comment]
In fact the namespace spide is inserted before std::vector:
```
line 335:
static void JavaCPP_spider_00024DoublePointerVector_deallocate(void *p) { delete (spider::std::vector<double*>*)p; }
```
```
Line 401:
{ sizeof(spider::std::vector<double*>) },
```

**Comment by saudet** [comment]
You could put an empty `@Namespace` before `@Name`, read the docs: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/annotation/Namespace.html
