### ISSUE TITLE
[question]how to implement the InfoMapper for this typedef?

### ISSUE THREAD

**Issue by AresZhu** [bytedeco/javacpp#220]
`typdef char NameType[20]; struct { NameType userName; }`
Does anyone know how to implement such InfoMapper?

Currently I use `new Info("NameType").cast().cppTypes("const char*").valueTypes("BytePointer"))`, not quite sure if it is right.

Thanks,
Ares

**Comment by saudet** [comment]
Yes, that's pretty much the best we can do for that. If you have any issues when using that `Info` though, please let me know.
