### ISSUE TITLE
record video, video is green

### ISSUE THREAD

**Issue by Z-COL** [bytedeco/javacpp#225]
private void initFrameFilter() {
        mFilters = generateFilters((int) (1f * outputHeight / outputWidth * imageHeight), imageHeight, 0, 0, mTranspose);
        mFrameFilter = new FFmpegFrameFilter(mFilters, imageWidth, imageHeight);
        mFrameFilter.setPixelFormat(avutil.AV_PIX_FMT_NV21); // default camera format on Android
    }

   public static String generateFilters(int w, int h, int x, int y, String transpose) {
         return String.format("crop=w=%d:h=%d:x=%d:y=%d,transpose=%s", w, h, x, y, "clock");
    }

    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        try {
            if (RECORD_LENGTH > 0) {
                int i = imagesIndex++ % images.length;
                yuvImage = images[i];
                timestamps[i] = 1000 * (System.currentTimeMillis() - startTime);
            }
            /* get video data */
            if (yuvImage != null && recording) {
                ((ByteBuffer) yuvImage.image[0].position(0)).put(data);

                if (RECORD_LENGTH <= 0) {
                    try {
                        long pastTime = System.currentTimeMillis() - startTime;
                        if (null != mTimeListener) {
                            mTimeListener.completeTime(pastTime);
                        }

                        if (pastTime >= MAX_RECORD_TIME) {
                            stopRecording();
                            return;
                        }

                        long t = 1000 * pastTime;
                        if (t > recorder.getTimestamp()) {
                            recorder.setTimestamp(t);
                        }

                        recordFrame(yuvImage);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        } finally {
            camera.addCallbackBuffer(data);
        }
    }

    private void recordFrame(Frame frame) throws FrameRecorder.Exception, FrameFilter.Exception {
        mFrameFilter.push(frame);
        Frame filteredFrame;
        while ((filteredFrame = mFrameFilter.pull()) != null) {
            recorder.record(filteredFrame);
        }
    }

build.gradle config
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:support-v4:' + project["support"]
    implementation 'org.bytedeco:javacpp:1.4'
    implementation 'org.bytedeco:javacv:1.4'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4', classifier: 'android-arm'
}

i user pre version is ok, but use this config record video, video is green!!!!

**Comment by saudet** [comment]
Thanks to @hnvn and @djalmaafilho there are working sample projects using FFmpegFrameFilter:
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-camera-preview
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-recognize
Please start with those!
