### ISSUE TITLE
missing jnijavacpp.cpp error

### ISSUE THREAD

**Issue by dlyubimov** [bytedeco/javacpp#228]
when compiling native  package1.ClazzA and package2.ClazzB (in different packages two jni .so libraries) in the same maven javacpp plugin configuration, I get c++ compilation error

`g++: error: /home/dmitriy/projects/[...]/classes/[...]/package2/javacpp/jnijavacpp.cpp: No such file or directory`

note that package1 compilation .so target succeeds.

I.e., it seems jnijavacpp.cpp is not copied into all compilation .so targets. 
1.3.2 does not exhibit this problem.

**Comment by saudet** [comment]
Fixed in the commit above! Thanks for reporting

**Comment by saudet** [comment]
Fix included in JavaCPP 1.4.1! Enjoy
