### ISSUE TITLE
Could not initialize class org.bytedeco.javacpp.avformat$AVFormatContext 

### ISSUE THREAD

**Issue by Eliezer090** [bytedeco/javacpp#229]
Estou tentando fazer um java para deteccao de faces mas estou com esse erro que nao consigo resolver se alguem puder me ajudar agradeço! 
![image](https://user-images.githubusercontent.com/36082343/37467549-51a83fc0-283f-11e8-99ef-62f0704438d6.png)
Minhas bibliotecas que tenho importada

Jars que tenho baixado sao da versao 1.3.3 presciso ser dessa versão pois tenho dependencias que só tem nessa versao Link de onde baixei: https://jar-download.com/?detail_search=g%3A%22org.bytedeco%22+AND+a%3A%22javacv-platform%22&search_type=av&a=javacv-platform&p=1 

Inportaçao do jar ffmpeg-3.4.1... é de uma soluçao que tentei mas nao resolveu nada se alguem puder me ajudar nao sei mais o que fazer!!!!

Plataforma que estou executando é Windows 10 64bits

**Comment by saudet** [comment]
You will need to use JavaCV 1.4 with the JavaCPP Presets for FFmpeg 3.4.1-1.4.
JavaCV 1.2 will not work with those.

**Comment by Eliezer090** [comment]
Resolvi o erro com essas importações tanto para Windows quanto para CentOs6 funcionando corretamente. Vlww pela resposta :+1: 
![image](https://user-images.githubusercontent.com/36082343/37668597-a7fb0774-2c43-11e8-83c1-3667d1e518c5.png)
