### ISSUE TITLE
enum include #undef parse fail

### ISSUE THREAD

**Issue by creatorKoo** [bytedeco/javacpp#230]
example code

this code link: https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/geometry.h#L27

typedef enum
{
#undef NoValue // <- this line make problem
  NoValue = 0x0000,
#undef XValue
  XValue = 0x0001,
  XiValue = 0x0001,
#undef YValue
  YValue = 0x0002,
  PsiValue = 0x0002,
#undef WidthValue
  WidthValue = 0x0004,
  RhoValue = 0x0004,
#undef HeightValue
  HeightValue = 0x0008,
  SigmaValue = 0x0008,
  ChiValue = 0x0010,
  XiNegative = 0x0020,
#undef XNegative
  XNegative = 0x0020,
  PsiNegative = 0x0040,
#undef YNegative
  YNegative = 0x0040,
  ChiNegative = 0x0080,
  PercentValue = 0x1000,    /* '%'  percentage of something */
  AspectValue = 0x2000,     /* '!'  resize no-aspect - special use flag */
  NormalizeValue = 0x2000,  /* '!'  ScaleKernelValue() in morphology.c */
  LessValue = 0x4000,       /* '<'  resize smaller - special use flag */
  GreaterValue = 0x8000,    /* '>'  resize larger - spacial use flag */
  MinimumValue = 0x10000,   /* '^'  special handling needed */
  CorrelateNormalizeValue = 0x10000, /* '^' see ScaleKernelValue() */
  AreaValue = 0x20000,      /* '@'  resize to area - special use flag */
  DecimalValue = 0x40000,   /* '.'  floating point numbers found */
  SeparatorValue = 0x80000, /* 'x'  separator found  */
  AspectRatioValue = 0x100000,    /* '~'  special handling needed  */
#undef AllValues
  AllValues = 0x7fffffff
} GeometryFlags;

please fix this.

problem translated code
/** enum GeometryFlags */

// #undef NoValuepublic static final int // <- '#undef' need new line or 'public static final int' need new line
  NoValue =  0x0000,
// #undef XValue
  XValue =  0x0001,
  XiValue =  0x0001,
// #undef YValue

**Comment by saudet** [comment]
Fixed in the latest commit above! Thanks for reporting and let me know if you encounter any more issues.

**Comment by saudet** [comment]
Fix included in JavaCPP 1.4.1! Enjoy
