### ISSUE TITLE
quick q

### ISSUE THREAD

**Issue by zjufish** [bytedeco/javacpp#233]
how can use a different gcc? 
mvn -Djavacpp.platform.compiler=/dir/to/g++ install seems not working

**Comment by saudet** [comment]
It's part of the platform properties, so we have to pass it with the plugin
config, if that's what you're trying to do?

**Comment by zjufish** [comment]
would u mind provide a pom example snipet code for that? thx

**Comment by saudet** [comment]
Sure, it's in the presets here:
https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L173

**Comment by zjufish** [comment]
hello, i tried this
 <profile>
            <id>javacpp-platform-linux-amd64</id>
            <activation>
                <property>
                    <name>javacpp.platform</name>
                    <value>linux-amd64</value>
                </property>
            </activation>
            <properties>
                <javacpp.platform>linux-amd64</javacpp.platform>
                <javacpp.platform.compiler>/somedir/gcc/6.4.0/bin/g++</javacpp.platform.compiler>
            </properties>
        </profile>

and do mvn install -Djavacpp.platform=linux-amd64
it looks like it is still using gcc 4.8(my default gcc) to build my so. anything wrong ?

**Comment by zjufish** [comment]
hello, i tried this
```
 <profile>
            <id>javacpp-platform-linux-amd64</id>
            <activation>
                <property>
                    <name>javacpp.platform</name>
                    <value>linux-amd64</value>
                </property>
            </activation>
            <properties>
                <javacpp.platform>linux-amd64</javacpp.platform>
                <javacpp.platform.compiler>/somedir/gcc/6.4.0/bin/g++</javacpp.platform.compiler>
            </properties>
        </profile>
> 
```
and do mvn install -Djavacpp.platform=linux-amd64
it looks like it is still using gcc 4.8(my default gcc) to build my so. anything wrong ?

**Comment by saudet** [comment]
Are you trying to build JavaCPP itself from source and want to change the compiler used for tests?

**Comment by saudet** [comment]
Please clarify what your goal is and I will be able to help better! Thanks
