### ISSUE TITLE
My question is cvGetPerspectiveTransform and getPerspectiveTransform these two functions, the same parameters, return matrix is different every time.

### ISSUE THREAD

**Issue by awaymeet** [bytedeco/javacpp#237]
My question is cvGetPerspectiveTransform and getPerspectiveTransform these two functions, the same parameters, return matrix is different every time.
Besides, I am a Chinese, English is not very good, I hope to get help, my email address 1210287094@qq.com. Thank you very much.

**Comment by awaymeet** [comment]
Scalar scalar=new Scalar(0,0,0,0);
		Mat hmat=new Mat(3, 3, CV_32FC1, scalar);
		CvMat map_matrix=new CvMat(hmat);
		
		
		CvPoint2D32f c1 = new CvPoint2D32f(4);
	    CvPoint2D32f c2 = new CvPoint2D32f(4);
	    c1.position(0).put((double)10, (double)20);
	    c1.position(1).put((double)809-10, (double)5);
	    c1.position(2).put((double)10, (double)694-11);
	    c1.position(3).put((double)809-8, (double)694-20);
	    
	    c2.position(0).put((double)0, (double)0);
	    c2.position(1).put((double)809, (double)0);
	    c2.position(2).put((double)0, (double)694);
	    c2.position(3).put((double)809, (double)694);
	    
	    String a=map_matrix.toString();
	    cvGetPerspectiveTransform(c1, c2, map_matrix);
	    String b=map_matrix.toString();
	    System.out.println(a);
	    System.out.println(b);
	    System.out.println("————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————");

**Comment by saudet** [comment]
Try to call this instead:

cvGetPerspectiveTransform(c1.position(0), c2.position(0), map_matrix);

**Comment by awaymeet** [comment]
Thank you from the bottom of my heart for helping me solve the problem.
But I think the official should give a demo like this, otherwise a lot of problems for developers.
If you have a chance to come to China, I think I would like to make friends with you, if really have a chance to please email me after 1210287094 @qq.com. I ask you to eat all kinds of Chinese food. I am a small business entrepreneurs, my company's website http://www.awaymeet.com/.

**Comment by saudet** [comment]
You're welcome! There is already a call like that to `cvFillConvexPoly()` in the `Demo` class actually:
https://github.com/bytedeco/javacv/#sample-usage
Thanks for the invitation! I'll sure let you know if I ever go to China.
