### ISSUE TITLE
Failed EnumTest on windows

### ISSUE THREAD

**Issue by Neiko2002** [bytedeco/javacpp#238]
OS: Windows 10 Pro (Version	10.0.16299 Build 16299)
Dev: Visual Studio 2015

After triggering the "mvn clean install" command for javacpp I get the error 

```
Tests in error:
  EnumTest.setUpClass:88 ▒ Runtime Process exited with an error: 2
```

With the Sunfire report
```
-------------------------------------------------------------------------------
Test set: org.bytedeco.javacpp.EnumTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.88 sec <<< FAILURE! - in org.bytedeco.javacpp.EnumTest
org.bytedeco.javacpp.EnumTest  Time elapsed: 1.88 sec  <<< ERROR!
java.lang.RuntimeException: Process exited with an error: 2
	at org.bytedeco.javacpp.EnumTest.setUpClass(EnumTest.java:88)
```

The problematic commit is https://github.com/bytedeco/javacpp/commit/8b9fc2fd0285879276ee4b622351dbee30b011e5, the one before https://github.com/bytedeco/javacpp/commit/aea25af1df233ef448511995abb3f5029a9bd17a works just fine.

The c11 compiler fix https://github.com/bytedeco/javacpp/commit/23389292924b4329f76874a4e4e952b4cd3cb3e5 did not help and even the current repository head gives me the same messages.

I was following the instructions [here](https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows#installation-recipe-for-visual-studiuo-2015-and-windows-10) and everything worked fine, until the failing test. I think the problem might not be the Java side. If you need the generated JNI code or any other help please let me know.

**Comment by saudet** [comment]
Fixed in the commit above! Thanks for reporting
