### ISSUE TITLE
Memory exception formatting (Pointer.formatBytes) is too imprecise for > 1GB

### ISSUE THREAD

**Issue by AlexDBlack** [bytedeco/javacpp#240]
```
Exception in thread "main" java.lang.OutOfMemoryError: Failed to allocate memory within limits: totalBytes (15G + 1G) > maxBytes (16G)
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:583)
```

This exception: the attempted memory allocation could be anywhere between 1.0 GB and 1.99 GB, while giving the same error - i.e., it's too imprecise for debugging purposes.

Ideally, say 2 decimal points could be reported, or alternatively raw bytes could also be reported?

```
import org.bytedeco.javacpp.Pointer;
    public static void main(String[] args) {
        for( double d=0; d<=2.1; d+= 0.1){
            long bytes = (long)((1024L * 1024 * 1024) * d);

            String gb = String.format("%.2f", d);
            String b = String.format("%-10d", bytes);
            System.out.println(gb + " GB, " + b + " bytes, formatted = " + Pointer.formatBytes(bytes));
        }
    }
```

```
0.00 GB, 0          bytes, formatted = 0
0.10 GB, 107374182  bytes, formatted = 102M
0.20 GB, 214748364  bytes, formatted = 204M
0.30 GB, 322122547  bytes, formatted = 307M
0.40 GB, 429496729  bytes, formatted = 409M
0.50 GB, 536870912  bytes, formatted = 512M
0.60 GB, 644245094  bytes, formatted = 614M
0.70 GB, 751619276  bytes, formatted = 716M
0.80 GB, 858993459  bytes, formatted = 819M
0.90 GB, 966367641  bytes, formatted = 921M
1.00 GB, 1073741823 bytes, formatted = 1023M
1.10 GB, 1181116006 bytes, formatted = 1G
1.20 GB, 1288490188 bytes, formatted = 1G
1.30 GB, 1395864371 bytes, formatted = 1G
1.40 GB, 1503238553 bytes, formatted = 1G
1.50 GB, 1610612736 bytes, formatted = 1G
1.60 GB, 1717986918 bytes, formatted = 1G
1.70 GB, 1825361100 bytes, formatted = 1G
1.80 GB, 1932735283 bytes, formatted = 1G
1.90 GB, 2040109465 bytes, formatted = 1G
2.00 GB, 2147483648 bytes, formatted = 2G
```

**Comment by saudet** [comment]
I used to report raw bytes, but it's not human readable and I believe you also had issues with that. That's more important I think. Hum, what about something like this?
```
0.00 GB, 0          bytes, formatted = 0
0.50 GB, 536870912  bytes, formatted = 524288K
1.00 GB, 1073741824 bytes, formatted = 1024M
1.50 GB, 1610612736 bytes, formatted = 1536M
2.00 GB, 2147483648 bytes, formatted = 2048M
...
100.00 GB, 107374182400 bytes, formatted = 102400M
```

**Comment by AlexDBlack** [comment]
Human readable is definitely important here, that takes priority.
The simplest solution that I'd be happy with is simply reporting 2 decimal places, for 1KB or above.

So it would look something like:
```
Failed to allocate memory within limits: totalBytes (15.00G + 1.35G) > maxBytes (16.04G)
```

**Comment by saudet** [comment]
I don't like to use floating point, it's not consistent with parsing. Sure, we could accept something like 13.099650252g and hope we don't trip over any floating point gotchas, but why? Why not have only one way to represent that?

As for formatting, I think this is pretty acceptable:
```
Failed to allocate memory within limits: totalBytes (15360M + 1382M) > maxBytes (16424M)
```
We can guarantee 3 digits, and no more than 5 (if we count "10" as a digit :), which is still pretty readable.

**Comment by AlexDBlack** [comment]
> I don't like to use floating point, it's not consistent with parsing

Fair enough. Then yeah, reporting in MB would work - certainly precise enough for debugging and configuration purposes 👍

**Comment by AlexDBlack** [comment]
I guess this can be closed - already seeing the improvement after rebuilding :)
Thanks 👍 

> Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(1): totalBytes = 7204M, physicalBytes = 17356M
