### ISSUE TITLE
CvSeq from several CvPoints

### ISSUE THREAD

**Issue by Olka95** [bytedeco/javacpp#249]
I have a situation, when I have several (for now four, but it is not such important) `CvPoints` and I need to put them to `CvSeq` in such way, that to be able to process `CvSeq` with its general operations. I got info for the points from third-party source, as set of the numbers I create cv points from, so I don't see an apportunity to make input look in other way. 

I tried to use the next way:
`opencv_core.CvMemStorage memStorage = cvCreateMemStorage(0);`

`CvSeq cvSeqContour = cvCreateSeq(CV_32SC2, Loader.sizeof(opencv_core.CvSeq.class), loader.sizeof(opencv_core.CvPoint.class), memStorage);`

`        cvSeqPush(cvSeqContour, cvPoint1);`
`       cvSeqPush(cvSeqContour, cvPoint2);`
`        cvSeqPush(cvSeqContour, cvPoint3);`
`        cvSeqPush(cvSeqContour, cvPoint4);`

As a result it was impossible to use some of the general `CvSeq` methods for `cvSeqContour`. For example, with using `cvContourPerimeter(cvSeqContour)` and `cvContourArea(cvSeqContour)` I got fatal errors. Because of it it is also impossble to use `cvApproxPoly`.

After long searching I found something that maybe will help me - `cvPointSeqFromMat` or `cvMakeSeqHeaderForArray`. But I'm not really sure if it is what I really need.

Can you please help me with my problem?

**Comment by Olka95** [comment]
The other project is written with using C API, and I'm not sure, if I have a time to transform it to C++ API :(

**Comment by saudet** [comment]
I see, anyway functions like `cvContourPerimeter()` and `cvContourArea()` typically work on contours, but they should also work with a `CvMat`, and that's much easier to work with.

**Comment by Olka95** [comment]
You are right, in theory this should work.

Can you, please, give me a helping hand again? Sometimes I'm still not doing very well with Java opencv.
I spend some time for it, but I still can not figure out, how creating of the CvMat from CvPoints or numbers should look like for this case.

**Comment by saudet** [comment]
The easiest way is usually by using an indexer. Have you tried to call CvMat.createIndexer()?
