### ISSUE TITLE
How to catch JavaCPP_exception in debugger(lldb)

### ISSUE THREAD

**Issue by louxiu** [bytedeco/javacpp#259]
Currently I tried the following way, but got no luck.

`break set -E c++`
`break set -F std::range_error`
`break set -F JavaCPP_exception`
`break set -F std::JavaCPP_exception`
`breakpoint set --file jnijavacpp.cpp --line xxx` The line where constructor of `JavaCPP_exception`

I also tried to remove `JavaCPP_hidden` before the declare of `JavaCPP_exception`.

**Comment by saudet** [comment]
That would be an issue with lldb...? Does gdb have the same issue?

**Comment by saudet** [comment]
So it works in lldb? What's the issue?

**Comment by louxiu** [comment]
I found the problem. I didn't turn on the debug mode (`compiler = {"cpp11", "debug", "!default"}`) when compiled the final lib.
