### ISSUE TITLE
CharPointer cppTypeName

### ISSUE THREAD

**Issue by iharh** [bytedeco/javacpp#261]
I'm trying to use javacpp for calling a native function, which returns std::wstring (or const wchar_t *)

My gcc has 4-bytes-based wchar_t (NOT a 2-bytes as in case of -fshort-wchar)

javacpp StdWString annotation leads to generating CharPointer-based interface.

For the mentioned CharPointer we generate cppTypeName (at Generator.cpp) using "unsigned short *", NOT a "wchar_t *".

This leads to trunkating returned (from native c++ side) data by factor of 2.

NOTE: I found to any usage of StdWString at available presets (just at one of the unit-test).

Question: What be the right way to fix this mismatch (either fix the Generator.cppTypeName or add some tunings to my client-side code)?

**Comment by saudet** [comment]
For reference, we just need to add this to the InfoMap:
```java
 .put(new Info("wchar_t").cast().valueTypes("int").pointerTypes("IntPointer"))
 .put(new Info("std::wstring").annotations("@StdWString").valueTypes("IntPointer"))
```
Please let me know if that doesn't work for some reason though, thanks!

**Comment by iharh** [comment]
Thank you.
As far as I can see, the change has been made at https://github.com/bytedeco/javacpp/commit/223e82e8cc6d078a940d551012e1afee13f4197e.

BTW, when do you plane to make a next release (1.4.3) ?

**Comment by saudet** [comment]
The change in that commit won't make a difference for your case though.

Soon, yes: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by iharh** [comment]
Thank you.

I've tried to blindly add a pair of suggested mappers, but that does not work - need to dig deeply into the code of Parser and/or other stuff....

**Comment by saudet** [comment]
I've just tried it with a declaration like this and it works just fine:
```cpp
std::wstring getWString();
```
Without the additional Info I get:
```java
public static native @StdWString CharPointer getWString();
```
But with it I get:
```java
public static native @StdWString IntPointer getWString();
```
So it's working fine for me. Let me know if you're still unable to obtain similar results.

**Comment by iharh** [comment]
Thank you, @saudet . I've just managed to get things working even without specifying extra info-stuff like:
`
public class NativeLibrary {

    public static class NativeClass extends Pointer {
        static { Loader.load(); }
        public NativeClass() { allocate(); }
        private native void allocate();
        public native @StdWString IntPointer getWString();
    }
    public static void main(String[] args) {
        System.out.println("start");
        try (NativeClass l = new NativeClass()) {
            IntPointer pI = l.getWString();
            int [] arrI = pI.getStringCodePoints();
            for (int i = 0; i < arrI.length; ++i) {
                System.out.println(arrI[i]);
            }
            System.out.println(pI.getString());
        }
        System.out.println("finish");
    }

}
`
