### ISSUE TITLE
Help with Blur Level

### ISSUE THREAD

**Issue by habeascorpse** [bytedeco/javacpp#264]
Hello,
i'm tryng to code a example to detect the blur level on an image, like this:
https://stackoverflow.com/questions/36413394/opencv-variation-of-the-laplacian-java

``
Mat destination = new Mat();
Mat matGray=new Mat();  

Imgproc.cvtColor(image, matGray, Imgproc.COLOR_BGR2GRAY);          
Imgproc.Laplacian(matGray, destination, 3); 
MatOfDouble median = new MatOfDouble();
MatOfDouble std= new MatOfDouble();        
Core.meanStdDev(destination, median , std);

Math.pow(std.get(0,0)[0],2);
``

but d'ont exist the Class "MatOfDouble"

anyone can help me?

**Comment by saudet** [comment]
It's available here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/opencv/core/MatOfDouble.html
You'll need to make sure to call `Loader.load(opencv_java.class)` though:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
