### ISSUE TITLE
Set Log Level of OpenCV

### ISSUE THREAD

**Issue by neil-benn** [bytedeco/javacpp#265]
Hello,

  I'm trying to do some digging around inside OpenCV to allow me to identify which camera I am connected to on Windows (rather than just 0, 1, n) when connecting from JavaCV.  To do this I'd need to be able to activate the logging within OpenCV as defined in the source file logger.cpp.  I've found a method called av_log_set_level but that isn't doing it (so I assume I'm calling the wrong thing).  Is there a way to make this call from JavaCV to OpenCV in order to activate the logging?

  Thanks.

Cheers,

Neil

**Comment by neil-benn** [comment]
Not needed any more and shouldn't be here!

**Comment by saudet** [comment]
Right, we can use FFmpegFrameGrabber for that!
