### ISSUE TITLE
Failing to compile simple example

### ISSUE THREAD

**Issue by neil-benn** [bytedeco/javacpp#266]
Hello,

  I'm trying to work something up and failing to succeed.  The header file looks as follows in a file called CameraIterator.h:

    #pragma once

    #define INITGUID
    #define _CRT_NO_VA_START_VALIDATION

    #include <stdio.h>
    #include <tchar.h>
    #include <iostream>
    #include <sti.h>
    #include <stdlib.h>
    #include <errno.h>
    #include <Windows.h>
    #include <vector>

    using namespace std;

    namespace CameraIteratorLibrary {

	class CameraIteratorClass {
	public:
		__declspec(dllexport) CameraIteratorClass();
		__declspec(dllexport) ~CameraIteratorClass();
		__declspec(dllexport) int listDevices();
		__declspec(dllexport) std::vector <std::string> getDeviceList();

	private:

		//don't touch
		static bool comInit();
		static bool comUnInit();
		static char deviceNames[20][255];
	};
    }

The cpp class is as follows (implementation code snipped for brevity):

---
    #include "CameraIterator.h"
    #include <tchar.h>

    //Include Directshow stuff here so we don't worry about needing all the h files.
    #include <dshow.h>
    #pragma comment(lib,"Strmiids.lib") 
    #include <windows.h>

    //for threading
    #include <process.h>

    namespace CameraIteratorLibrary
    {

	static bool VI_COM_MULTI_THREADED = false;
	static int comInitCount = 0;

	////////////////////////////  PUBLIC METHODS  ///////////////////////////////

	CameraIteratorClass::CameraIteratorClass() {
		//start com
		comInit();
	}

	char CameraIteratorClass::deviceNames[20][255] = { {0} };

	std::vector <std::string> CameraIteratorClass::getDeviceList() {
		int numDev = CameraIteratorClass::listDevices();
		std::vector <std::string> deviceList;
		for (int i = 0; i < numDev; i++) {
			const char * name = deviceNames[i];
			if (name == NULL)break;
			deviceList.push_back(name);
		}
		return deviceList;
	}

	int CameraIteratorClass::listDevices() {
		//COM Library Intialization
		comInit();
		<snip>
		return deviceCounter;
	}

	CameraIteratorClass::~CameraIteratorClass() {
		//Unitialize com
		comUnInit();
	}

	bool CameraIteratorClass::comInit() {
                <snip>
		return true;
	}

	bool CameraIteratorClass::comUnInit() {
                <snip>
                return false;
	}
}

The Java class is as follows:

    import org.bytedeco.javacpp.*;
    import org.bytedeco.javacpp.annotation.*;

    @Platform(include = "CameraIterator.h")
    public class CameraIteratorLibrary extends Pointer {
	
        public static class CameraIteratorClass extends Pointer {
            static { Loader.load(); }
            public CameraIteratorClass() { allocate(); }
            private native void allocate();

            // to call the getter and setter functions 
            public static native int listDevices();

        }
    
        public static void main(String[] args) {
            CameraIteratorClass.listDevices();
        }
    }

  I know this code works in plain ol' C++ as it works from Visual Studio with no problem.

  I've then dropped the CameraIterator.h file, CameraIterator.dll and CameraIterator.lib in a directory with the java source file - CameraIteratorLibrary.java.  

Executing javac CameraIteratorLibrary.java -cp ..\..\lib\javacpp-1.4.2.jar CameraIteratorLibrary.java works just fine.  

Then in this directory I am executing "c:\Program Files\Java\jdk1.8.0_162\bin\java.exe" -jar ..\..\lib\javacpp-1.4.2.jar CameraIteratorLibrary.  However this gives me a load of warnings followed by:
```
   Creating library jniCameraIteratorLibrary.lib and object jniCameraIteratorLibrary.exp
jniCameraIteratorLibrary.obj : error LNK2001: unresolved external symbol "public: static int __cdecl CameraIteratorLibrary::CameraIteratorClass::listDevices(void)" (?listDevices@CameraIteratorClass@CameraIteratorLibrary@@SAHXZ)
jniCameraIteratorLibrary.obj : error LNK2001: unresolved external symbol "public: __thiscall CameraIteratorLibrary::CameraIteratorClass::~CameraIteratorClass(void)" (??1CameraIteratorClass@CameraIteratorLibrary@@QAE@XZ)
jniCameraIteratorLibrary.obj : error LNK2001: unresolved external symbol "public: __thiscall CameraIteratorLibrary::CameraIteratorClass::CameraIteratorClass(void)" (??0CameraIteratorClass@CameraIteratorLibrary@@QAE@XZ)
jniCameraIteratorLibrary.dll : fatal error LNK1120: 3 unresolved externals
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 2
        at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:515)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:931)
        at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1125)
```
  It's like it can't find the dll but everything (for now) is in the same folder.  Does anybody have any suggestions as to why it can't seem to find the correct files and/or what I am doing wrong?

Cheers,

Neil

**Comment by saudet** [comment]
You'll need to run the Builder on that as well with `java -jar javacpp.jar CameraIteratorClass`, for example, as shown in the README.md file:
https://github.com/bytedeco/javacpp#accessing-native-apis

**Comment by neil-benn** [comment]
Isn't that this line:

javac CameraIteratorLibrary.java -cp ....\lib\javacpp-1.4.2.jar CameraIteratorLibrary.java

**Comment by saudet** [comment]
No, run both these lines:
```
javac -cp /path/to/javacpp.jar CameraIteratorLibrary.java
java -jar /path/to/javacpp.jar CameraIteratorLibrary
```

**Comment by neil-benn** [comment]
Thanks - I'm running:

"c:\Program Files\Java\jdk1.8.0_162\bin\javac.exe" -cp ..\..\lib\javacpp-1.4.2.jar CameraIteratorLibrary.java
"c:\Program Files\Java\jdk1.8.0_162\bin\java.exe" -jar ..\..\lib\javacpp-1.4.2.jar CameraIteratorLibrary

I think that is basically the same as you wrote above?

**Comment by neil-benn** [comment]
Thanks - we're on version 1.4.2 and VideoInputFrameGrabber didn't return the path which is the precise thing I needed.  IMoniker in the DirectShow API does though.

**Comment by saudet** [comment]
Did you also check the lower level videoInput presets?
https://github.com/bytedeco/javacpp-presets/blob/master/videoinput/src/main/java/org/bytedeco/javacpp/videoInputLib.java

**Comment by neil-benn** [comment]
Hello,

  Yes, they can't give me what I need which is the device path.  I'm
actually using opencv extensively and started to look at patching opencv to
allow me to get the device path but it seemed like a huge amount of work.
A small helper library to give me just what I need is easier.  I have done
it with swig for now because I'm short of time but I'll come back to
javacpp shortly as I'd like to learn it.

Cheers,

Neil

**Comment by saudet** [comment]
It's also possible to do it the SWIG way with `java -jar javacpp.jar -nocompile ...`. That will give you the JNI bindings in a C++ file to build independently from JavaCPP.
