### ISSUE TITLE
About C++ writing instructions using javacpp

### ISSUE THREAD

**Issue by unize4** [bytedeco/javacpp#279]
I am building a slightly larger C++ library for use on the java side.
I am going to use the javacpp project.
Is there any C++ writing guide to help my C++ library be more in line with current or future javacpp projects?

Grateful.

**Comment by saudet** [comment]
Something more than the following? Please let me know what is missing from these pages!
https://github.com/bytedeco/javacpp/wiki/Basic-Architecture
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by unize4** [comment]
My C++ project was developed before the Java project. I am worried that the C++ project will be written too freely to cause the need to adjust when using the project through javacpp later.
Just like this:
Make sure the C++ uses a namespace
But I need more detail, if any

**Comment by saudet** [comment]
That's all on https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes
If there is anything that isn't documented there, or
if you need more explanations, let me know! Thanks
