### ISSUE TITLE
Dependency Issue Docker CentOS and Ubuntu

### ISSUE THREAD

**Issue by kev2316** [bytedeco/javacpp#283]
'An exception occured while executing the Java class. no jniopencv_highgui in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]: /root/.javacpp/cache/opencv-4.0.1-1.4.4-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjniopencv_highgui.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory'

This works fine through eclipse on both my window and linux machines, but if I try to launch via a `mvn exec:java -D"exec.mainClass"="com.service,Application"` or `java -cp 'app/target/maven-deps/*:app/target/opencv-result-service-1.0.0.jar'com.service,Application`

I get the same random errors.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/593
