### ISSUE TITLE
Possible @NoDeallocator annotation issue

### ISSUE THREAD

**Issue by imoschak** [bytedeco/javacpp#284]
Hi!

I've got a problem with using the @NoDeallocator annotation, I've searched quite a bit and haven't found a concrete example of its usage, so I tried using it on my own but it seems I'm missing something cause I cannot get it to work,

First thing I've tried, was using it as an annotation to the type i.e.:

infoMap.put(new Info("TestClass").pointerTypes("TestClass").annotations("@NoDeallocator")

This correctly annotates allocate() methods with @NoDellocator, the problem then is that it annotates all instances of the type and as a result compilation of java crashes due to invalid annotations.

See "no_deallocator_applied_to_all_instances.zip" for a concrete example of the problem I'm facing in this case.

I've seen in gitter that you mentioned annotating the constructors i.e.:

infoMap.put(new Info("TestClass::TestClass()").annotations("@NoDeallocator"));

This annotates the Java constructor instead of the native annotate method resulting in " annotation type not applicable to this kind of declaration:

@NoDeallocator public TestClass() { super((Pointer)null); allocate(); }
private native void allocate();

See "deallocator_applied_to_constructor.zip" for a concrete example of this.

For the record I've also tried to annotate allocate() but that doesn't work of course since from what I've seen in generator they are always generated along with constructors and cannot be referenced from the preset file.

[no_deallocator_applied_to_all_instances.zip](https://github.com/bytedeco/javacpp/files/2873016/no_deallocator_applied_to_all_instances.zip)
[deallocator_applied_to_constructor.zip](https://github.com/bytedeco/javacpp/files/2873017/deallocator_applied_to_constructor.zip)

**Comment by saudet** [comment]
Ok, I've fixed this in commit https://github.com/bytedeco/javacpp/commit/d71d8f690b23648b00601a6a56be1c5ae89d9d8a. Give it a try with 1.4.5-SNAPSHOT: http://bytedeco.org/builds/ Thanks for reporting this issue!

BTW, to apply the annotation to all constructors we can use `new Info("TestClass::TestClass")`, that is without the `()` at the end.

**Comment by imoschak** [comment]
Hi!

Thanks for the fix, it seems that it works when `TestClass` is not within a namespace working example here:
[Nodallocator_without_namespace.zip](https://github.com/bytedeco/javacpp/files/2875167/Nodallocator_without_namespace.zip)

It doesn't seem to work though when I put it in a namespace i.e.:

```java
      infoMap.put(new Info("ns1::ns2::TestClass").pointerTypes("TestClass"));
      infoMap.put(new Info("ns1::ns2::TestClass::TestClass").annotations("@NoDeallocator"));
      infoMap.put(new Info("ns1::ns2::UserClass").pointerTypes("UserClass"));
```
In this case it doesn't annotate `allocate()` with `@NoDeallocator`. But maybe I've configured it wrong?

Problematic example here:
[Nodallocator_with_namespace_not_fixed.zip](https://github.com/bytedeco/javacpp/files/2875169/Nodallocator_with_namespace_not_fixed.zip)

**Comment by saudet** [comment]
No, that's another bug. Fixed in commit https://github.com/bytedeco/javacpp/commit/7f7ba43bf84389b3ec7d21e32101e6bf31245739!

**Comment by imoschak** [comment]
Great that fixes the problem with namespaces! But what if templates are involved too?

The following for example doesn't seem to work:
```java
      infoMap.put(new Info("ns1::ns2::TestClass<double>").pointerTypes("TestClass"));
      infoMap.put(new Info("ns1::ns2::TestClass<double>::TestClass").annotations("@NoDeallocator"));
```

In this case it fails to parse the header once it reaches the constructor, problematic example here:

[NoDeallocator_not_fixed_for_templates.zip](https://github.com/bytedeco/javacpp/files/2880729/NoDeallocator_not_fixed_for_templates.zip)

**Comment by saudet** [comment]
This is getting into stuff that JavaCPP doesn't really support that well, but yes there was something missing for that and your sample code now works with the changes in commit https://github.com/bytedeco/javacpp/commit/3e134fe6d8d2eba8b6584a357b6c690201af3475.

**Comment by imoschak** [comment]
That fixes it too! thanks a lot!

**Comment by imoschak** [comment]
Darn it! Managed to find another one!

There is a problem when the `@NoDeallocator` annotated class has methods that return or receive objects of the class as parameters e.g.:

```cpp
  class TestClass
  {
  public:
     TestClass();
     virtual ~TestClass() = default;
     virtual const char* getIt() const;
     virtual const char* getWhich(const String& arg) const;
     virtual bool isEqual(const TestClass& other) const;
     virtual TestClass copy() const;
  };
```
+
```java
      infoMap.put(new Info("ns1::ns2::TestClass").pointerTypes("TestClass").purify(false).virtualize());
      infoMap.put(new Info("ns1::ns2::TestClass::TestClass").annotations("@NoDeallocator"));
```
=
```java
  @Namespace("ns1::ns2") public static class TestClass extends Pointer {
      static { Loader.load(); }
      /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
      public TestClass(Pointer p) { super(p); }
      /** Native array allocator. Access with {@link Pointer#position(long)}. */
      public TestClass(long size) { super((Pointer)null); allocateArray(size); }
      private native void allocateArray(long size);
      @Override public TestClass position(long position) {
          return (TestClass)super.position(position);
      }

     public TestClass() { super((Pointer)null); allocate(); }
     private native @NoDeallocator void allocate();
     @Virtual public native @Const({false, false, true}) @Cast("const char*") BytePointer getIt();
     @Virtual public native @Const({false, false, true}) @Cast("const char*") BytePointer getWhich(@Const @StdString @ByRef BytePointer arg);
 @Virtual public native @Cast("bool") @Const({false, false, true}) boolean isEqual(@Const @NoDeallocator @ByRef TestClass other);
     @Virtual public native @NoDeallocator @ByVal @Const({false, false, true}) TestClass copy();
  }
```
:'(

Sorry for that.

Full problematic example here:
[NoDeallocator_not_working_when_class_refers_to_itself.zip](https://github.com/bytedeco/javacpp/files/2884849/NoDeallocator_not_working_when_class_refers_to_itself.zip)

Thanks again!

**Comment by saudet** [comment]
Ok, I've managed to fix that in commit https://github.com/bytedeco/javacpp/commit/be92fe8331e798a552da6a1915a25e6cb25e5285. Let me know if there's anything else! Thanks

**Comment by imoschak** [comment]
Great fixed! thanks again!
