### ISSUE TITLE
Virtual call through derived raw pointer (or unique_ptr) calls the base instead of the derived method

### ISSUE THREAD

**Issue by imoschak** [bytedeco/javacpp#285]
Hi!

Okay this will sound a bit strange and it is even stranger to explain, I've got the following:

```cpp
template <typename T>
class TestClass
{
public:
   TestClass() { }

   virtual ~TestClass() { }

   virtual T getIt() const
   {
      std::cout << "Called base" << std::endl;
      return T{};
   }

   virtual void callGetIt() const
   {
      getIt();
   }
};

class UserClass
{
public:
   UserClass(TestClass<double>*);
   virtual ~UserClass()
   {
      _tc.release();
   }
   void call_unique();
   void call_raw();
private:
   std::unique_ptr<TestClass<double> > _tc;
   TestClass<double>* _rtc;
};
```

`call_unique` and `call_raw` call the `callGetIt()` method via either the `unique_ptr` or the raw pointer.

Then I've got the following override in java:

```java
public class Main
{
   public static class TestClassDoubleOverride extends TestClassDouble
   {
      @Override
      public double getIt()
      {
         System.out.println("Called derived");
         return 0.0;
      }
   }

   public static void main(String[] args)
   {
      UserClass uc = new UserClass(new TestClassDouble());
      System.out.println("Calling through unique_ptr!");
      uc.call_unique();
      System.out.println("Calling through raw_ptr!");
      uc.call_raw();
   }
}
```

`TestClassDouble` overrides `TestClass<double>::getIt` and prints out another message, but when `main()` is executed both calls call the base method.
Now this **only** happens with this specific override i.e. a method with a **templated return type** and no arguments (seemingly there may be other cases, but most other virtual method calls seem to work okay up until now, calling the overriden method as expected).

Fully working example of the problem here:
[Problem_with_virtual_calls_to_overriden_functions.zip](https://github.com/bytedeco/javacpp/files/2880768/Problem_with_virtual_calls_to_overriden_functions.zip)

Instruction on build/run:
```shell
cd Cpp/build
cmake ../
make
cd ../../Java
mvn clean install
mvn exec:java -Dexec.mainClass="com.test.Main"
```

Thanks!

**Comment by saudet** [comment]
It seems to work fine here if I change `new TestClassDouble()` to `new TestClassDoubleOverride()`:
```
Calling through unique_ptr!
Called derived
Calling through raw_ptr!
Called derived
```
Is that it?
