### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniClass

### ISSUE THREAD

**Issue by johntwill** [bytedeco/javacpp#292]
when I call Loader.load(org.bytedeco.qt.global.QtCore.class);

**Comment by saudet** [comment]
You'll need to include all the JAR files in the class path. Please try to use this pom.xml file:
https://github.com/bytedeco/javacpp-presets/blob/master/qt/samples/pom.xml

**Comment by saudet** [comment]
This should be fixed with commit https://github.com/bytedeco/javacpp-presets/commit/17d921ec389de79c48155dde960316877547f7bd.
Please let me know if you're still having issues though, thanks!
