### ISSUE TITLE
VideoCapture cannot open ip camera

### ISSUE THREAD

**Issue by bewithme** [bytedeco/javacpp#294]
I am sure that my ip camera is working  and I can connect it with rtsp protocol by other player , but it doesn't work when I use VideoCapture.  what's  wrong with my  code? 

`   
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>3.4.2-1.4.1</version>
</dependency>

`

`
VideoCapture capture = new VideoCapture();
        capture.set(CAP_PROP_FRAME_WIDTH, 1280);
        capture.set(CAP_PROP_FRAME_HEIGHT, 720);
        if (!capture.open("rtsp://user:password,@xxx.xxx.xxx.xxx:554/h264/ch1/main/av_stream")) {
           
         System.out.println("Can not open the cam !!!");
        
        }
`

**Comment by saudet** [comment]
Use FFmpegFrameGrabber, not VideoCapture. The default build for OpenCV
doesn't link with FFmpeg.

**Comment by bewithme** [comment]
> Use FFmpegFrameGrabber, not VideoCapture. The default build for OpenCV doesn't link with FFmpeg.

thank you so much, but when I  use FFmpegFrameGrabber, occur error bellow:

`org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -1330794
744: Could not open input "rtsp://user:password,@xxx.xxx.xxx.xxx:554/h264/ch1/main/av_stream". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:754)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
690)
        at com.ternnetwork.avocado.ai.objectdection.RealtimeObjectDetectionApp.s
tartDetaction(RealtimeObjectDetectionApp.java:52)
        at com.ternnetwork.avocado.ai.objectdection.RealtimeObjectDetectionApp.m
ain(RealtimeObjectDetectionApp.java:31)`

**Comment by saudet** [comment]
Try to call setFormat() to what it's supposed to be, "mp4" maybe?

**Comment by bewithme** [comment]
> Try to call setFormat() to what it's supposed to be, "mp4" maybe?

when I call  grabber.setFormat("h264");  but error like bellow , what kind of format does it support ?

`org.bytedeco.javacv.FrameGrabber$Exception: av_find_input_format() error: Could
not find input format "h264".
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:714)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
690)
        at com.ternnetwork.avocado.ai.objectdection.RealtimeObjectDetectionApp.s
tartDetaction(RealtimeObjectDetectionApp.java:53)
        at com.ternnetwork.avocado.ai.objectdection.RealtimeObjectDetectionApp.m
ain(RealtimeObjectDetectionApp.java:31)`

**Comment by saudet** [comment]
Anyway, check the error message on the console. It's going to give us more information.

**Comment by bewithme** [comment]
> Anyway, check the error message on the console. It's going to give us more information.

that's all information,I have no idea how to fix it .

**Comment by saudet** [comment]
Try to call `FFmpegLogCallback.set()` and check again on the console.
