### ISSUE TITLE
Dependency Conflict: duplicate classes "org.codehaus.plexus.context.ContextMapAdapter" in different JARs, have different implementations

### ISSUE THREAD

**Issue by HelloCoCooo** [bytedeco/javacpp#295]
Hi, in **javacpp-1.4.4**, duplicate classes with the same fully-qualified name _**org.codehaus.plexus.context.ContextMapAdapter**_ are included in two different libraries, i.e., **org.sonatype.sisu:sisu-inject-plexus:1.4.2** and **org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3**.

According to _"first declaration wins"_ class loading strategy, only this class in **_org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3_** can be loaded, and that in _**org.sonatype.sisu:sisu-inject-plexus:1.4.2**_ will be shadowed.

By further analyzing, your project expects to invoke method **_<org.codehaus.plexus.context.ContextMapAdapter: java.util.Set entrySet()>_**  in _**org.sonatype.sisu:sisu-inject-plexus:1.4.2**_. As it has been shadowed, so that this method defined in **_org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3_** is actually forced to be referenced via the following invocation path:

```
<org.bytedeco.javacpp.tools.Generator$ShortEnum: org.bytedeco.javacpp.tools.Generator$ShortEnum[] values()> D:\conflictWorkNew\testcase\TestProject\javacpp-1.4.4\target\classes
<org.apache.maven.project.MavenProject: java.lang.Object clone()> D:\conflictWork\repository\org\apache\maven\maven-core\3.0\maven-core-3.0.jar
<org.apache.maven.project.MavenProject: org.apache.maven.project.MavenProject clone()> D:\conflictWork\repository\org\apache\maven\maven-core\3.0\maven-core-3.0.jar
<org.apache.maven.project.MavenProject: void deepCopy(org.apache.maven.project.MavenProject)> D:\conflictWork\repository\org\apache\maven\maven-core\3.0\maven-core-3.0.jar
<org.apache.maven.project.MavenProject: java.util.Set getExtensionArtifacts()> D:\conflictWork\repository\org\apache\maven\maven-core\3.0\maven-core-3.0.jar
<org.eclipse.sisu.wire.MergedProperties$MergedEntries$1: boolean hasNext()> 
<org.codehaus.plexus.context.ContextMapAdapter: java.util.Set entrySet()>

```
Although both of these two conflicting classes contain the referenced methods (with the same signature), they have different implementations. This issue will not lead to runtime crashes, but it can introduce inconsistent semantic hehavior by changing the control flows and data flows.

**_Workaround solution:_**
An easy way to workaround the problem is **_reversing the declaration order_** of these two libraries (i.e., reverse the declaration order of maven-core and maven-plugin-api) in pom file. 
Then, according to **_"first declaration wins"_** class loading strategy, class _**org.codehaus.plexus.context.ContextMapAdapter**_ in _**org.sonatype.sisu:sisu-inject-plexus:1.4.2**_ can be loaded (the version that **bytedeco/javacpp** expects to reference by static analysis).
This fix will not affect other libraries or class, except the above duplicate class.

**Dependency conflict--**
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ javacpp ---
[INFO] org.bytedeco:javacpp:jar:1.4.4
[INFO] +- org.apache.maven:maven-plugin-api:jar:3.5.4:compile
[INFO] |  +- org.apache.maven:maven-model:jar:3.5.4:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:3.5.4:compile
[INFO] |  +- _**org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:compile**_
[INFO] |  |  +- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |  |  +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[INFO] |  \- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[INFO] +- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.5.2:compile
[INFO] +- org.apache.maven:maven-core:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-settings:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-settings-builder:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-repository-metadata:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-model-builder:jar:3.0:compile
[INFO] |  +- org.apache.maven:maven-aether-provider:jar:3.0:runtime
[INFO] |  +- org.sonatype.aether:aether-impl:jar:1.7:compile
[INFO] |  |  \- org.sonatype.aether:aether-spi:jar:1.7:compile
[INFO] |  +- org.sonatype.aether:aether-api:jar:1.7:compile
[INFO] |  +- org.sonatype.aether:aether-util:jar:1.7:compile
[INFO] |  +- _**org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile**_
[INFO] |  |  \- org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[INFO] |  |     \- org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[INFO] |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO] |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[INFO] |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] \- org.slf4j:slf4j-simple:jar:1.7.25:compile
[INFO]    \- org.slf4j:slf4j-api:jar:1.7.25:compile
```

Thank you very much.
Best,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **_<org.codehaus.plexus.context.ContextMapAdapter: java.util.Set entrySet()>_** in _**org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3**_ (loaded version):
![z](https://user-images.githubusercontent.com/46306510/55685752-708b9480-598c-11e9-9599-81019d2e62d1.png)

Code snippet of **_<org.codehaus.plexus.context.ContextMapAdapter: java.util.Set entrySet()>_** in _**org.sonatype.sisu:sisu-inject-plexus:1.4.2**_ 
 (shadowed but expected to invoke method):
![x](https://user-images.githubusercontent.com/46306510/55685756-75504880-598c-11e9-852f-a6bdee004884.png)



As a result, these conflicting method included in **org.sonatype.sisu:sisu-inject-plexus:1.4.2** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
May I pull a request to fix it?
Thanks for your attention.

**Comment by saudet** [comment]
Please do, I never noticed that issue. Thanks!

**Comment by saudet** [comment]
Then again I don't think that making sure we are invoking a method that isn't even implemented is going to change much of anything. Have you found any other conflicts? Or is that it?
