### ISSUE TITLE
link system lib and user lib 

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp#300]
I almost build cbc (https://github.com/coin-or/Cbc/) for javacpp successfully, but some function was failed..

i have confused by how to write the configMapper.java 
if i want link some my .dylib and also some sys lib
```
@Platform(
    linkpath = ".../cppbuild/macosx-x86_64/lib/",
    link = {
        "CbcSolver",   "gfortran"
    },
    include = {
        "wrapper.h",
    }
)
```
but the `gfortran` was not under the dir by linkpath? should i add another `@platform` block info?
```
...
,
@Platform(
     link = "gfortran"
)
```

**Comment by saudet** [comment]
We can add both paths to "linkpath".

**Comment by zhengdi1992** [comment]
cool. thanks.. i'm so foolish
