### ISSUE TITLE
input must be a scalar, but it has shape [1]

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp#301]
in tensorflow javacpp..
the placeholder was define by 
```
self.drop = tf.placeholder(tf.float32,name='drop')
self.phase = tf.placeholder(tf.bool,name='x_phase')
``` 
in java, how to build the tensor?
i have try like this 
```
tensorflow.Tensor drop = new tensorflow.Tensor(tensorflow.DT_FLOAT, new TensorShape(new long[]{1}));
FloatRawIndexer dropIndexer = drop.createIndexer();
dropIndexer.put(0, 0.5f);
```
but occur the error when session run..

```
input must be a scalar, but it has shape [1]
	 [[Node: fc_1layer/cond/sub/Switch = Switch[T=DT_FLOAT, _class=["loc:@drop"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_drop_0_1, _arg_x_phase_0_0)]]
```

i think was the `new TensorShape(new long[]{1})` should not like that, but a scalar shape?
but how build it?  if use `new TensorShape()`, the data cannot fill into the tensor..`dropIndexer.put(0, 0.5f);` will occur `ArrayIndexOutOfBoundsException exeption`

**Comment by saudet** [comment]
TensorFlow considers arrays that have a number of dimensions equal to 0 as scalars, so something like `new TensorShape(new long[]{})` works for that.

**Comment by zhengdi1992** [comment]
but if that `new TensorShape(new long[]{})`,  how can assign the value to the tensor?
if in python, can use like that and works well.. how to translate to javacpp?
```
drop = sess.graph.get_tensor_by_name('drop:0')
op = sess.graph.get_tensor_by_name('str_output:0')
sess.run(op, {drop: 0.5})
```
i got the `ArrayIndexOutOfBoundsException` exception, by use that..when ` drop.createIndexer();`
```
tensorflow.Tensor drop = new tensorflow.Tensor(tensorflow.DT_FLOAT,
            new TensorShape(new long[]{}));
FloatRawIndexer dropIndexer = drop.createIndexer();
dropIndexer.put(0, 0.5f);
```

**Comment by saudet** [comment]
There was an issue previously with scalars like that, but it should work with the latest release.

**Comment by zhengdi1992** [comment]
the version is that?
```
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>tensorflow</artifactId>
    <version>1.12.0-1.4.4</version>
</dependency>
```

**Comment by saudet** [comment]
No, 1.13.1-1.5, see: http://bytedeco.org/download/ 
The groupId and package names changed a bit:
http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by zhengdi1992** [comment]
upgrade it and works well..
yep, changed a bit...hahaha..

**Comment by saudet** [comment]
I've added a couple more overloads for `Tensor.create()` so we can now do something like this instead:
```java
        Tensor scalar = Tensor.create(new float[] {42});
        Tensor vector = Tensor.create(new float[] {0, 1}, 2);
```
