### ISSUE TITLE
new version load very high

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp#302]
is there any differences from 
```
     <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>tensorflow</artifactId>
        <version>1.12.0-1.4.4</version>
      </dependency>
```
and 
```
     <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>tensorflow-platform</artifactId>
        <version>1.13.1-1.5</version>
      </dependency>
```
After upgraded...and change some import error because of the upgrade
but cpu from 80% to 700%....which a 8c docker env..

**Comment by zhengdi1992** [comment]
in the new version . i found that warning .
```
Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance
```

**Comment by saudet** [comment]
There's most likely been some changes in TensorFlow 1.13, yes.
Check the "behavioral changes": https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1

**Comment by saudet** [comment]
If your goal is to disable multithreading though, make sure to always set the OMP_NUM_THREADS environment variable to 1

**Comment by saudet** [comment]
We might also need to set other parameters like inter_op_parallelism_threads to 1 to disable multithreading. It's all documented on the following page, but let me know if you're having any issues setting them from Java:
https://www.tensorflow.org/guide/performance/overview

**Comment by saudet** [comment]
It looks like the default inter_op_parallelism_threads will be back to 2 with 1.14, so you might not need to tweak things manually with that version:
> 2019-05-29 11:18:33.979699: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
