### ISSUE TITLE
clang and thousands of Pointer (de)allocation leads to segmentation fault on Linux

### ISSUE THREAD

**Issue by mennodenhollander** [bytedeco/javacpp#303]
I am using clang to parse C/C++ code. This works fine on Windows, but on linux the Java VM exits with a fatal error (segmentation fault) in various places of the parser code. When I change the parser code then the problem pops up in another place. I suspect the issue has to do with Pointer allocation/deallocation. The following code triggers the segmentation fault (most of the time, since the issue is a bit random).

```
import org.bytedeco.javacpp.clang.*;

import static org.bytedeco.javacpp.clang.*;

public class PointerTest {
    public static void main(String[] arguments) {
        for (int i = 0; i < 10; i++) {
            CXIndex cxI = clang_createIndex(0, 0);
            for (int j = 0; j < 50000; j++) {
                CXCursor cxCursor = new CXCursor();
                cxCursor.deallocate(); // also crashes without this statement
            }
            clang_disposeIndex(cxI); // also crashes without this statement
        }
    }
}
```

Error message:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1e79207175, pid=22766, tid=0x00007f1e767f7700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 392 C2 java.lang.ref.Reference.tryHandlePending(Z)Z (115 bytes) @ 0x00007f1e79207175 [0x00007f1e79207100+0x75]
#
# Core dump written. Default location: /home/menno/Code/x/core or core.22766
#
# An error report file with more information is saved as:
# /home/menno/Code/software-evaluation-product/hs_err_pid22766.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
- Without clang_createIndex and clang_disposeIndex the issue does not occur
  - I also haven't run into this issues when I use the libllvm functionality to process hundreds of LLVM IR files on Linux.
- Issue occurs in llvm-platform 1.4.2 and 1.4.4
- Issue occurs in Oracle JDK 8u211 and OpenJDK 8u222 (I think I also tried OpenJDK 11, which also give the same results)
- I am running Ubuntu 18.04.2 LTS 64 bit (on VMWare Workstation, but also tried VirtualBox with the same results)

**Comment by mennodenhollander** [comment]
I discovered a work-around. If you set the environment variable LIBCLANG_DISABLE_CRASH_RECOVERY=1, then this issue does not occur anymore. It might require a system restart to take effect.

**Comment by saudet** [comment]
Yes, that's already documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/llvm#sample-usage
