### ISSUE TITLE
Safer default for maxPhysicalBytes?

### ISSUE THREAD

**Issue by AlexDBlack** [bytedeco/javacpp#309]
Consider the following memory settings:
Xmx=4G
org.bytedeco.javacpp.maxbytes=10G

If org.bytedeco.javacpp.maxphysicalbytes is not set, it currently defaults to `2 * Runtime.maxMemory()` (i.e., Xmx) - [here](https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L327-L329) / [here](https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L393-L403)
For the settings above, we'll have maxphysicalbytes=8G, whereas the intent was to have the program use up to 14GB total (4+10).

I am proposing the following change (when maxphysicalbytes is not explicitly set): maxphysicalbytes defaults to `Runtime.getRuntime().maxMemory() + maxbytes`

If maxbytes is not set by the user, the result is the same as the current behaviour (`2*Runtime.getRuntime().maxMemory()`) as maxbytes defaults to `Runtime.getRuntime().maxMemory()` in this case.

Simple change to implement - I'm happy to send a PR if this change is acceptable.

**Comment by saudet** [comment]
Sounds good! Please do send a PR :)
