### ISSUE TITLE
Crash in JavaCPP Deallocator

### ISSUE THREAD

**Issue by EmergentOrder** [bytedeco/javacpp#314]
When using the JavaCPP ONNX Preset, I get this consistently, but asynchronously:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f821c3d130f, pid=29736, tid=0x00007f81bbfff700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b01) (build 1.8.0_212-8u212-b01-1-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libonnx_proto.so+0x21c30f]  onnx::ModelProto::SharedDtor()+0xcf
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f81e4ab4000):  JavaThread "JavaCPP Deallocator" daemon [_thread_in_native, id=29941, stack(0x00007f81b9fff000,0x00007f81bc000000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 
```

**Comment by EmergentOrder** [comment]
Hmm.. This may just be a protobuf bug, see: https://github.com/okapies/protobuf-shareddtor-crash

Although I also saw JavaCPP Deallocator crashes without the reference to SharedDtor, perhaps just due to lost frame details.

**Comment by saudet** [comment]
It can corrupt memory without crashing, and show up as something else
later. So, what's the fix for this bug?

**Comment by saudet** [comment]
Ah, it's just a typical issue with C++. @thomasstep explains the correct workaround for this here:
https://github.com/protocolbuffers/protobuf/issues/435#issuecomment-486831578

**Comment by EmergentOrder** [comment]
Makes sense, but I'm still not clear on how to fix this from the JavaCPP side. It seems like I need to use a PointerPointer, but doing so still requires me to create the ModelProto first, which leads to the sharedDtor issue. How do I do the equivalent of `new(...)` and assign the result to a PointerPointer?

**Comment by EmergentOrder** [comment]
Looks like I found a solution, using `(new ModelProto()).New()`. Strangely, even though I still create a ModelProto before calling it (seems like that should be static), it doesn't error.

**Comment by saudet** [comment]
The best thing would be to have only one copy of Protocol Buffers in memory, which isn't always easy to achieve, but in the case of nGraph, for example, it doesn't depend itself on Protocol Buffers, only through its dependency on ONNX...

**Comment by saudet** [comment]
But it doesn't look like nGraph supports linking to an external version of ONNX, that's annoying. I wonder how they expect all this to work together?
