### ISSUE TITLE
i have no c++ source code

### ISSUE THREAD

**Issue by mengpengfei** [bytedeco/javacpp#315]
i have no c++ source code,but i have  the dll and the .h file which declear the dll method, can i use javacpp to call the dll,please tell me how to do

**Comment by saudet** [comment]
Yes, it's possible. There are some instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

And a "Hello, World" sample library with presets here:
https://github.com/bytedeco/helloworld
https://github.com/bytedeco/javacpp-presets/tree/helloworld/helloworld

For any additional questions, please feel free to ask here!
