### ISSUE TITLE
Version 1.5.1 - java.lang.UnsatisfiedLinkError: no jniSQLite in java.library.path

### ISSUE THREAD

**Issue by gwenn** [bytedeco/javacpp#318]
Version 1.5 fine (at least locally: macOs X):
https://github.com/gwenn/sqlite-jna/tree/javacpp
Version 1.5.1 ko:
https://github.com/gwenn/sqlite-jna/tree/javacpp-1.5.1
CI builds are not reliable but:
https://travis-ci.org/gwenn/sqlite-jna/builds/556919973?utm_source=github_status&utm_medium=notification
> java.lang.UnsatisfiedLinkError: org.sqlite.SQLite$LogCallback.allocate()V

**Comment by saudet** [comment]
Fixed! Is there anything else that broke?

**Comment by gwenn** [comment]
Tested successfully with 1.5.2-SNAPSHOT: 27a7a49185904fdd503cbd035147c3988c8bc4c2
Thanks.
