### ISSUE TITLE
how to map struct with javacpp

### ISSUE THREAD

**Issue by huanxue318** [bytedeco/javacpp#319]
Hi 

I have a c++ struct like:
```cpp
struct Result{
string msg；
int errorCode；
};
```

The struct is a return value of a c++ interface ,like: Result query();

The native method in java is：
public static native Result query();

How can I map struct Result to java?I have read the mapping recipes but no ideas. 

Could you give me a example for me,thanks

**Comment by saudet** [comment]
The Parser should be able to handle that without any special Info. Try to follow these instructions:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by saudet** [comment]
There's also a hellworld example that you can use pretty much as is, replacing the bits that you need:
https://github.com/bytedeco/helloworld
https://github.com/bytedeco/javacpp-presets/tree/helloworld/helloworld
Let me know if there is still anything unclear from that.

**Comment by huanxue318** [comment]
Thanks for your reply.

I found the following codes in helloworld.h  ,but I did not find any examples in Java using these,any guides to these?
// by value
struct Person getPerson();
void printPerson (struct Person p);
