### ISSUE TITLE
Parsed not properly

### ISSUE THREAD

**Issue by ggNirvana** [bytedeco/javacpp#322]
If I write "typedef std::string string" in file A . And I use ”string“ in file B.
Can I make javacpp only parse File B with using InfoMap?

**Comment by ggNirvana** [comment]
For example:
Server.h
`#include"Camera.h"
#include"Computer.h"	
#include<vector>

namespace test {
	class Server :public Computer
	{
	public:

		Server(const string& ip, const string& serverName) {
			this->ip = ip;
			this->serverName = serverName;
			this->statu = 1;
		}

		void deleteCamera(Camera* cam) {
			delete cam;
			cam = nullptr;
		}
		void addCamera(Camera* cam);
		void turnOffCamera(Camera* cam);
		void turnOffServer(Server* server);
		std::vector<Camera*> getCameraList();
	private:
        string ip;
        string serverName;
        std::vector<Camera*> CameraList;
	};
}


`


Camera.h:
`#include<string>
namespace test {
	typedef std::string string;
	class Camera
	{
	public:
		int statu;
		std::string name;


		//���췽��
		Camera(std::string name) {
			this->name = name;
			this->statu = 1;
		}

		//�ı��������
		void turnOff();


		void deleteCamera(Camera* cam) {
			delete this;
			cam = NULL;
		}

		
	private:
	};
}`

**Comment by ggNirvana** [comment]
`import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import org.bytedeco.javacpp.tools.*;

@Properties(
        value = @Platform(
                includepath = {
                        "Server.h","Camera.h"},
                include = {
                        "Camera.h","Server.h"
                }
        ),
        target = "NativeLibrary"
)
public class NativeLibraryConfig implements InfoMapper {
    public void map(InfoMap infoMap) {


    }
}`

**Comment by ggNirvana** [comment]
I do not want javacpp parse my Camera.h , but typedef is written in it.
And server.h uses type string.

**Comment by ggNirvana** [comment]
I trid to write Info , but didn't work at all....

**Comment by ggNirvana** [comment]
I trid "new Info("string").pointerTypes("BytePointer").define();
It worked but not so properly

**Comment by saudet** [comment]
The default for `std::string` is defined here:
>```java
> .put(new Info("std::string").annotations("@StdString").valueTypes("BytePointer", "String").pointerTypes("BytePointer"))
>```
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/InfoMap.java#L98

So if you're happy with that, we can do the same with just `string`, yes:
```java
.put(new Info("string").annotations("@StdString").valueTypes("BytePointer", "String").pointerTypes("BytePointer"))
```
Or something else...

**Comment by ggNirvana** [comment]
I should read source code....

**Comment by ggNirvana** [comment]
Thank you very much !
