### ISSUE TITLE
System.setProperty("org.bytedeco.javacpp.maxphysicalbytes not working in Android

### ISSUE THREAD

**Issue by jjvargas** [bytedeco/javacpp#324]
I am setting these values in Android , but I do not see any logger prints and still getting the "Physical memory usage is too high error"

            System.setProperty("org.bytedeco.javacpp.logger.debug", "true");
            System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "0");
            System.setProperty("org.bytedeco.javacpp.maxbytes", "0");

I am using the javacpp as a jar file. 

Any idea if there is another way to set this parameters?

**Comment by saudet** [comment]
Make sure to enable "largeHeap"...

**Comment by jjvargas** [comment]
I do not want to enable largeHeap, even if I enable it I have seen the "Physical memory usage is too high error"

**Comment by saudet** [comment]
No, that's how we can set them. Make sure to set them before calling any method of JavaCPP or they will not take effect.
