### ISSUE TITLE
I only have one dll file, how should I use it?

### ISSUE THREAD

**Issue by ACCia** [bytedeco/javacpp#325]
HI！I only have one dll file, how should I use it?

**Comment by saudet** [comment]
Like this: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-macros-to-fields-or-methods

**Comment by ACCia** [comment]
> 像这样：[https](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes)：[//github.com/bytedeco/javacpp/wiki/Mapping-Recipes](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes)

Can I import the dll library by annotation?

**Comment by ACCia** [comment]
> Yes, that's how it works.

What I am calling now is not the jnidll generated by javacpp, but a third-party dll library that is not open source. My current solution can only be to call dll with c++ and then javacpp to generate jni.

**Comment by saudet** [comment]
Yes, that's fine. Let me know if there is something you don't understand
from the documentation.

**Comment by saudet** [comment]
Also be sure to take a look at the helloworld sample project:
https://github.com/bytedeco/helloworld

**Comment by ACCia** [comment]
Thank you, I will  go see it.

**Comment by ACCia** [comment]
> 另外一定要看看helloworld示例项目：[https](https://github.com/bytedeco/helloworld)：
> [//github.com/bytedeco/helloworld](https://github.com/bytedeco/helloworld)

Thank you, I will  go see it.

**Comment by ACCia** [comment]
> > [](https://github.com/bytedeco/helloworld)
> 
> Thank you, I will go see it.

HelloWorldTest runtime getPerson function does not return correctly

READ -------------------------------------------------
Loaded helloworld library
J boolean = false
J byte = -3
J char = \u74F2
J short = 12737
J int = -2147483648
J long = 367995870
J UTF-8 String = Hello UTF-8 zß水🍌 string!
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.helloworld.PersonTypePtr.firstname()Lorg/bytedeco/javacpp/BytePointer;
	at org.bytedeco.helloworld.PersonTypePtr.firstname(Native Method)
	at HelloWorldTest.main(HelloWorldTest.java:38)
Unloaded helloworld library

I did not use the cppbuild.sh script to build, but instead used the dynamic library built by mingw. And changed the two parameters of link and preload under org.bytedeco.helloworld.presets.helloworld and changed to dynamic library name.
 link = "msys-helloworld-0",
 preload = "msys-helloworld-0"

Use maven to build jni's dynamic library
<execution>
                        <id>javacpp.compiler</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <skip>${javacpp.compiler.skip}</skip>
                            <classOrPackageName>org.bytedeco.helloworld.global.*</classOrPackageName>
                            <copyLibs>true</copyLibs>
                            <compilerOptions>
                                <compilerOption>-static-libgcc</compilerOption>
                                <compilerOption>-static-libstdc++</compilerOption>
                                <compilerOption>-Wl,-Bstatic</compilerOption>
                                <compilerOption>-lstdc++</compilerOption>
                                <compilerOption>-lgcc</compilerOption>
                                <compilerOption>-lgcc_eh</compilerOption>
                                <compilerOption>-lpthread</compilerOption>
                                <compilerOption>-Wl,-Bdynamic</compilerOption>
                            </compilerOptions>
                        </configuration>
                    </execution>

**Comment by ACCia** [comment]
Is my Mapping Recipes not working correctly?，How can I make sure my Mapping Recipes are working?

**Comment by saudet** [comment]
You'll need to build the JNI library and link with your DLL, as explained in the guide, and as shown in the helloworld sample project as well. If you could explain what you do not understand, I might be able to help, but I can't guess what you do not understand.

**Comment by ACCia** [comment]
The helloworld sample project has already run. But found a problem
After transcoding a single string, the result is garbled.
 ```
person.lastname(new BytePointer("A".getBytes("GBK"))); [65]
 System.out.printf(person.lastname().getString("GBK"));  [65, -72, 30, 1] //The result is:  A# A�
```
When A is converted to GBK encoding, it should be one byte.
But the result obtained by person.lastname() is four to three bytes.

**Comment by saudet** [comment]
Since you're not setting a null-terminated string, you'll need to give it the size like this: `person.lastname().capacity("1").getString("GBK"))`
