### ISSUE TITLE
UnsatisfiedLinkError for native dependency on Alpine

### ISSUE THREAD

**Issue by jfrantzius** [bytedeco/javacpp#329]
Hi,
when using nd4j, we're seeing this error with OpenJDK12 on Alpine 3.9:

`app_1    | Caused by: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so: Error loading shared library libmkldnn.so.0: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64//libnd4jcpu.so)
app_1    | 	at java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
app_1    | 	at java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[?:?]
app_1    | 	at java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[?:?]
app_1    | 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[?:?]
app_1    | 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[?:?]
app_1    | 	at java.lang.Runtime.load0(Runtime.java:765) ~[?:?]
app_1    | 	at java.lang.System.load(System.java:1866) ~[?:?]
app_1    | 	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1238) ~[javacpp-1.4.3.jar:1.4.3]
app_1    | 	at org.bytedeco.javacpp.Loader.load(Loader.java:999) ~[javacpp-1.4.3.jar:1.4.3]
app_1    | 	at org.bytedeco.javacpp.Loader.load(Loader.java:891) ~[javacpp-1.4.3.jar:1.4.3]
app_1    | 	at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10) ~[nd4j-native-1.0.0-beta3.jar:?]`

The seemingly missing library `libmkldnn.so.0` exists in `/usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0`, but JavaCPP seems to fail telling Alpine where to find it. I don't know how you're doing this, maybe you are setting LD_LIBRARY_PATH?

**Comment by saudet** [comment]
Alpine Linux doesn't install glibc by default. It's probably looking for that...

**Comment by jfrantzius** [comment]
We have glibc installed

**Comment by saudet** [comment]
Try to set the "org.bytedeco.javacpp.logger.debug" system property to "true" and/or the "org.bytedeco.javacpp.logger" one to "slf4j" to get a more detailed log of the errors.

**Comment by jfrantzius** [comment]
I put the following as arguments, and verified in `/proc/<pid>/cmdline`, but unfortunately don't get additional output:
`-Dorg.bytedeco.javacpp.logger.debug=true -Dorg.bytedeco.javacpp.logger=slf4j`

**Comment by saudet** [comment]
You'll need to use SLF4J if you set that one.

**Comment by saudet** [comment]
If your logger isn't working, don't try to use SLF4J, and everything will just be output to the console.

**Comment by jfrantzius** [comment]
OK thanks, now I get a lot more output before the same exception comes up:

> app_1    | Loading class org.nd4j.nativeblas.Nd4jCpu
app_1    | Loading class org.nd4j.nativeblas.Nd4jCpu
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/mkl-dnn-0.16-1.4.3-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1
app_1    | Loading /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1: Error relocating /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1: : initial-exec TLS resolves to dynamic definition in /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libgomp.so.1
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/nd4j-native-1.0.0-beta3-linux-x86_64.jar!/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
app_1    | Loading /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1: Error relocating /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1: : initial-exec TLS resolves to dynamic definition in /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libgomp.so.1
app_1    | Loading library gomp
app_1    | Failed to load for gomp@.1: java.lang.UnsatisfiedLinkError: no gomp in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/mkl-dnn-0.16-1.4.3-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libiomp5.so
app_1    | Loading /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libiomp5.so
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libiomp5.so: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libiomp5.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libiomp5.so)
app_1    | Loading library iomp5
app_1    | Failed to load for iomp5: java.lang.UnsatisfiedLinkError: no iomp5 in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/mkl-dnn-0.16-1.4.3-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so
app_1    | Loading /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so: Error loading shared library libiomp5.so: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmklml_intel.so)
app_1    | Loading library mklml_intel
app_1    | Failed to load for mklml_intel: java.lang.UnsatisfiedLinkError: no mklml_intel in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/mkl-dnn-0.16-1.4.3-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0
app_1    | Loading /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/mkl-dnn-0.16-1.4.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libmkldnn.so.0)
app_1    | Loading library mkldnn
app_1    | Failed to load for mkldnn@.0: java.lang.UnsatisfiedLinkError: no mkldnn in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/nd4j-native-1.0.0-beta3-linux-x86_64.jar!/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
app_1    | Loading /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so: Error loading shared library libmkldnn.so.0: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcpu.so)
app_1    | Loading library nd4jcpu
app_1    | Failed to load for nd4jcpu: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
app_1    | Locking /usr/local/tomcat/.javacpp/cache before extracting
app_1    | Extracting jar:file:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/nd4j-native-1.0.0-beta3-linux-x86_64.jar!/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so
app_1    | Loading /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so
app_1    | Failed to load /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so: java.lang.UnsatisfiedLinkError: /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcpu.so: Error loading shared library libmkldnn.so.0: No such file or directory (needed by /usr/local/tomcat/.javacpp/cache/nd4j-native-1.0.0-beta3-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64//libnd4jcpu.so)
app_1    | Loading library jnind4jcpu
app_1    | Failed to load for jnind4jcpu: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: [/opt/openjdk-12/lib/server, /opt/openjdk-12/lib, /opt/openjdk-12/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]

Concerning `ld-linux-x86-64.so.2`, this library is present in `/lib64`

**Comment by saudet** [comment]
Try to add it to ld.so.conf or LD_LIBRARY_PATH.

**Comment by jfrantzius** [comment]
I tried setting LD_LIBRARY_PATH, and I can see tomcat.sh outputting `LD_LIBRARY_PATH=/lib:/usr/lib:/usr/lib64`, but the error remains the same. 

Next I'll try symlinking it into `/usr/lib`, as that was the solution for it to find `libstdc++.so.6` previously. The trick there was to `ln -sf /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/libstdc++.so.6 /usr/lib/libstdc++.so.6` in the Dockerfile.

**Comment by jfrantzius** [comment]
[In a similar issue of openjdk on Alpine](https://github.com/docker-library/openjdk/issues/77#issuecomment-302871030), someone found out that `LD_LIBRARY_PATH` is ignored for non-privileged users on Alpine (due to musl). The suggested workaround using `/etc/ld-musl-x86_64.path` did not work for me, but symlinking the library (libstdc++) did. 

Will try the same for `ld-linux-x86-64.so.2`.

**Comment by saudet** [comment]
Why are those files not in the library path by default? It doesn't sound like we could do anything on this end to solve this.
