### ISSUE TITLE
can we use main class in javacpp to execute the program

### ISSUE THREAD

**Issue by suguna-mother** [bytedeco/javacpp#330]

**Comment by suguna-mother** [comment]
i know that java connectivity based on c/c++ native library,But i have some doubt for main class that may be have some issue while calling main class

**Comment by saudet** [comment]
Are you getting any error messages? Could you explain what you're trying to do?

**Comment by suguna-mother** [comment]
Has based on pylon program i have created an main class and from that formation i have been calling some native funtion in main class.
in that format i get some exceptions error just already commented in comment#323

**Comment by suguna-mother** [comment]
i just have doubt in javacpp, if that main class can be executable?

**Comment by saudet** [comment]
If you're trying to use something @jpsacha did, you'll need to ask him about that.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv-examples/issues/21
