### ISSUE TITLE
How should std::wstring& type be converted

### ISSUE THREAD

**Issue by ACCia** [bytedeco/javacpp#334]
I have added the @Cast("std::wstring&") annotation, but there is no correct output after the call.

My native code
`void WinToastTemplate::setFirstLine(_In_ const std::wstring& ws) `

java code

`public native void setFirstLine(@Const @Cast("std::wstring&") BytePointer text);`

**Comment by saudet** [comment]
We can use `@StdWString` for that with `CharPointer` on Windows.

**Comment by saudet** [comment]
Duplicate of #261
