### ISSUE TITLE
Trick JVM to tread method as Intrinsic 

### ISSUE THREAD

**Issue by sirinath** [bytedeco/javacpp#34]
Can you add the ability to trick the JVM to treat a method as inctincic.

Ref: https://thinkingandcomputing.com/2014/03/30/eliminating-jni-overhead/, http://www.slideshare.net/RednaxelaFX/green-teajug-hotspotintrinsics02232013

**Comment by saudet** [comment]
Sure, it might become possible with Panama... Would you have any more actionable information about that?

**Comment by sirinath** [comment]
I am not fully sure. The intrinsic symbols are defined here: http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/tip/src/share/vm/classfile/vmSymbols.hpp

There seams to be a way according to the above presentation to do this.

**Comment by saudet** [comment]
I'm pretty sure this is out of scope for JavaCPP, but please let me know if you figure out something we can use. Thanks!
