### ISSUE TITLE
javacpp failing with android ndk r20

### ISSUE THREAD

**Issue by tmm1** [bytedeco/javacpp#341]
```
i686-linux-android/bin/ld: error: cannot find -lc++
```

according to https://bugreports.qt.io/browse/QTBUG-76293 a workaround is to add `-nostdlib++`. i'm not sure if we can add this to `platform.compiler.default` unconditionally or if it will affect older ndk releases adversely.

**Comment by tmm1** [comment]
It would be useful if there were generic properties like `platform.compiler.ldflags` available to add arbitrary flags into the compile process.

**Comment by saudet** [comment]
There are, for libraries it's platform.linkpath.prefix:
https://github.com/bytedeco/javacpp/blob/master/src/main/resources/org/bytedeco/javacpp/properties/android-arm64-clang.properties

**Comment by saudet** [comment]
Or maybe you mean platform.compiler.output?

**Comment by tmm1** [comment]
I ended up using `-Dplatform.compiler.default="-O3 -s -nostdlib++"`

But even with that one I had to repeat the default value to ensure the `-O3 -s` didn't get lost. It would be useful to have a property that defaults to blank that could be used solely to add custom flags that might be necessary in specific compiler environments.

**Comment by saudet** [comment]
We can add arbitrary ones like platform.compiler.ldflags too, yes. It just won't be by default, so I don't see how that would be useful here.

**Comment by tmm1** [comment]
Yea that's what I mean, something that's not on by default so that users can specify extra things they need to add. I feel like I've run into this a few times now, everytime the NDK updates you have to add a flag of some sort and it'd be easier to be able to stuff those somewhere while I work on getting proper fixes upstream. Just an idea..

**Comment by saudet** [comment]
Yes, that already works. Set `platform.compiler.ldflags` if you like that name and do `@Platform(compiler = "ldflags", ...` in the Java config files.

**Comment by saudet** [comment]
Although, what you're probably looking for is the `-Xcompiler` command line option and the `compilerOptions` property for Maven?
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/BuildMojo.html#compilerOptions

**Comment by saudet** [comment]
Did you get it working in the end? Please send a pull request when you do! Thanks

**Comment by tmm1** [comment]
Yes I got it working with the workaround above:

> I ended up using `-Dplatform.compiler.default="-O3 -s -nostdlib++"`

I don't know how this affects older NDK releases, or if it will be required with r21. It is unclear what the right solution here is from javacpp's perspective.

**Comment by saudet** [comment]
Replacing `-static-libstdc++` with `-nostdlib++` in all the properties for Clang works fine with at least NDK r18b as well, so I think that would be a good solution.

**Comment by saudet** [comment]
Could you give that a try and send a pull request if it works for you? Thanks!

**Comment by tmm1** [comment]
According to https://github.com/android/ndk/issues/951#issuecomment-501017894 it does seem like `-nostdlib++` is a requirement going forward:

> 2\. Presumably the reason this happens because your build wasn't passing `-nostdlib++` in prior releases. This flag is fairly new and the result of not passing it was fairly innocuous (even ndk-build and the CMake toolchain didn't do this until somewhat recently), so it was easy to forget. However it's something that you _should_ be using if you're manually linking libc++. If you just add that flag that should let you continue using NDK r20 without more involved modifications to your build system (though you'll want to start looking into this soon, I'm guessing that r22 will be the release that does away with the legacy paths).

**Comment by tmm1** [comment]
> However it's something that you _should_ be using if you're manually linking libc++

Well, this says its only required if we're manually linking libc++. So maybe we should just get rid of `-static-libstdc++` instead?

Honestly I'm not really sure what the right solution here is. If you'd like to open a PR for what makes sense to you, I am happy to test and verify it works in my environment.

**Comment by saudet** [comment]
Yes, that's the idea, replacing `-static-libstdc++` with `-nostdlib++`. Could you try that?

**Comment by tmm1** [comment]
To me the documentation makes it seem like replacing the option won't work. You either need them both, or neither. (Because `-nostdlib++` is only required when manually linking libc++).

**Comment by saudet** [comment]
You're confusing libc++ with libstdc++: Those two are completely unrelated.

**Comment by tmm1** [comment]
> You're confusing libc++ with libstdc++: Those two are completely unrelated.

Okay, thanks. I still don't understand why removing `-static-libstdc++` is related as I didn't need to do that myself earlier.

I opened a PR as you requested and verified it works for me.

**Comment by saudet** [comment]
It outputs a warning if we don't remove it, so might as well remove it :)
