### ISSUE TITLE
default values for function arguments need template substitution

### ISSUE THREAD

**Issue by mkmckenz** [bytedeco/javacpp#342]
If the default value of a function argument uses a template parameter, it is not resolved in the generated JNI .cpp which then fails to compile.  For example:

```cpp
template <class T, class CompareFunctorT>
struct SortedContainer {
    SortedContainer(CompareFunctorT compareFun = CompareFunctorT());
};
```
And lets say I bind an instantiation of that template like so:
```java
 map.put(new Info("SortedContainer<std::string, std::less<std::string> >").pointerTypes("SortedStringContainer"));
```
Because Parser.parameters() does not substitute template arguments for template parameters used in default values, the generated JNI C++ code for the bound instantiation of the template above will contain the expression `ptr0 == NULL ? std::less<std::string>(CompareFunctorT()) : *ptr0`, which doesn't compile and should instead be `ptr0 == NULL ? std::less<std::string>() : *ptr0`.

**Comment by saudet** [comment]
Fix included in JavaCPP 1.5.2! Thanks for the contribution.
