### ISSUE TITLE
How can I use virtualize of InfoMap

### ISSUE THREAD

**Issue by bruceywave** [bytedeco/javacpp#345]
I have a pointer function in c++,
 `typedef void(*cluster_status_notify_j)(bool cluster_up_down);`, 
I use maven parse c++ file and generator code like`	
@Properties(inherit = com.xinhua.xmes.rtdb.cpp.XHPaxosInfoMap.class)
public class cluster_status_notify_j extends FunctionPointer {
	    static { Loader.load(); }
	    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
	    public    cluster_status_notify_j(Pointer p) { super(p); }
	    protected cluster_status_notify_j() { allocate(); }
	    private native void allocate();
	    public native void call(@Cast("bool") boolean cluster_up_down);
}
`
but I don't extends cluster_status_notify_j  and override method 'call', how can I do it?
I want to use like this:
 `                clusterOptions.cluster_status_notify_callback(new cluster_status_notify_j() {

					@Override
					public void call(boolean cluster_up_down) {
						if(cluster_up_down) {
							System.out.println("集群已连接!");
						}else {
							System.out.println("对不起，集群已断开！");
						}
					}
				
				});`

**Comment by saudet** [comment]
Yes, that will work, but keep a reference to the object in a field to prevent premature garbage collection.

**Comment by bruceywave** [comment]
Compilation does not report errors and startup does not report errors, but when data arrives at the callback function, it will report errors, such as is not natvie method. The method I overwrite is not a natvie method. Look at github, modifying it with @Virtual.
for example:
`.put(new Info("xhpaxos::java_cluster_options::cluster_status_notify_j")
					.virtualize()`
but it throws exception:
`jnixhpaxos.cpp:7854:41: error: cannot convert ‘void (**)(bool)’ to ‘void (*)(bool)’ in assignment
     if (rptr != NULL) rptr->ptr = &ptr->cluster_status_notify_callback;`

**Comment by bruceywave** [comment]
>  but keep a reference to the object in a field to prevent premature garbage collection.
how can I keep a reference?

**Comment by bruceywave** [comment]
this is my test code in springboot:
`package com.xinhua.xmes.cpp;

import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.Virtual;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.xinhua.xmes.rtdb.cpp.SubPlcPointDataUnionVector;
import com.xinhua.xmes.rtdb.cpp.XHPaxos;
import com.xinhua.xmes.rtdb.cpp.cluster_status_notify_j;
import com.xinhua.xmes.rtdb.cpp.java_cluster_options;
import com.xinhua.xmes.rtdb.cpp.recv_data_callback_j;
import com.xinhua.xmes.rtdb.cpp.sub_plc_point_data_union;
import com.xinhua.xmes.rtdb.cpp.global.xhpaxos;

@Component
public class CppRtdbCommand implements CommandLineRunner {
	private static XHPaxos xhPaxos = null;
	private static long count = 0;

	@Override
	public void run(String... args) throws Exception {
		java_cluster_options clusterOptions = new java_cluster_options();
		clusterOptions.data_copy((byte) 1);
//		clusterOptions.channel(2122);
//		clusterOptions.beacon_port((short) 18821);
		clusterOptions.channel(1129);
		clusterOptions.beacon_port((short) 40001);
		clusterOptions.service_port((short) 11029);
		clusterOptions.cluster_server_cnt((byte) 2);
		clusterOptions.version((short) 3);
		clusterOptions.dispatcher_type((byte) 3);
		clusterOptions.data_copy((byte) 1);
		clusterOptions.histDbName(new BytePointer("histdb"));
		clusterOptions.confDbName(new BytePointer("configdb") );
		clusterOptions.dbHostIP(new BytePointer("10.125.38.152"));
		clusterOptions.dbPort(new BytePointer("3306"));
		clusterOptions.dbUserName(new BytePointer("root"));
		clusterOptions.dbPassword(new BytePointer("000000"));
		clusterOptions.cluster_status_notify_callback(new cluster_status_notify_j() {

			@Override
			public void call(boolean cluster_up_down) {
				if(cluster_up_down) {
					System.out.println("集群已连接! 开始发送数据:");
					sendCommand();
				}else {
					System.out.println("对不起，集群已断开！");
				}
			}
		
		});
		clusterOptions.pub_data_callback(new recv_data_callback_j() {

			@Override
			public void call(byte data_type, int plc_id, long peer_id, byte ret_code, int result_cnt,Pointer presult) {
				if(count % 100000 == 0) {
					System.out.println("收到数据了:【" + count + "】条 ");
					count ++;
				}
			}
		});
		xhPaxos = new XHPaxos(clusterOptions);
	}
	
	public static void sendCommand() {
		sub_plc_point_data_union subPlcData = new sub_plc_point_data_union();
		subPlcData.inner_struct_plc_id(888);
		subPlcData.inner_struct_point_id(0xffffffff);
		SubPlcPointDataUnionVector subPlcDataVector = new SubPlcPointDataUnionVector();
		subPlcDataVector.put(subPlcData);
		xhPaxos.sub_plc_data(subPlcDataVector);
	}

}
`

**Comment by saudet** [comment]
You have a xhPaxos field. Just keep a reference to the callback there as well.

**Comment by bruceywave** [comment]
Thank you. It's already done. But the performance is relatively weak, the server writes 1000000 data per second, and the javacpp can only reach 40,000-50,000 per second. How can I optimize it?

**Comment by bruceywave** [comment]
DefaultPubDataCallback:Total data received: 12200000 , waste time: 1899 ms
DefaultPubDataCallback:Total data received: 12300000 , waste time: 1907 ms
DefaultPubDataCallback:Total data received: 12400000 , waste time: 1924 ms
DefaultPubDataCallback:Total data received: 12500000 , waste time: 1931 ms
DefaultPubDataCallback:Total data received: 12600000 , waste time: 1913 ms
DefaultPubDataCallback:Total data received: 12700000 , waste time: 1906 ms
DefaultPubDataCallback:Total data received: 12800000 , waste time: 1877 ms
DefaultPubDataCallback:Total data received: 12900000 , waste time: 1968 ms
DefaultPubDataCallback:Total data received: 13000000 , waste time: 1933 ms
DefaultPubDataCallback:Total data received: 13100000 , waste time: 1975 ms
DefaultPubDataCallback:Total data received: 13200000 , waste time: 1958 ms
DefaultPubDataCallback:Total data received: 13300000 , waste time: 1978 ms
DefaultPubDataCallback:Total data received: 13400000 , waste time: 1927 ms
DefaultPubDataCallback:Total data received: 13500000 , waste time: 1919 ms
DefaultPubDataCallback:Total data received: 13600000 , waste time: 1956 ms
DefaultPubDataCallback:Total data received: 13700000 , waste time: 1960 ms
DefaultPubDataCallback:Total data received: 13800000 , waste time: 1929 ms
DefaultPubDataCallback:Total data received: 13900000 , waste time: 2013 ms
DefaultPubDataCallback:Total data received: 14000000 , waste time: 2002 ms
DefaultPubDataCallback:Total data received: 14100000 , waste time: 2006 ms
DefaultPubDataCallback:Total data received: 14200000 , waste time: 2013 ms
DefaultPubDataCallback:Total data received: 14300000 , waste time: 1922 ms
DefaultPubDataCallback:Total data received: 14400000 , waste time: 1893 ms
DefaultPubDataCallback:Total data received: 14500000 , waste time: 1953 ms
DefaultPubDataCallback:Total data received: 14600000 , waste time: 1876 ms
DefaultPubDataCallback:Total data received: 14700000 , waste time: 1954 ms
DefaultPubDataCallback:Total data received: 14800000 , waste time: 1900 ms
DefaultPubDataCallback:Total data received: 14900000 , waste time: 1965 ms
DefaultPubDataCallback:Total data received: 15000000 , waste time: 2011 ms

**Comment by saudet** [comment]
50000 per second, that's 20 microseconds per call, right? The overhead of JNI and everything shouldn't go over 1 microsecond, so that's probably caused by something in your code. If you're copying large amounts of data, that could explain it. Run the profiler on the application to see what is taking all that time.
