### ISSUE TITLE
How do I generate Java code from C/C++ header files？

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacpp#354]
Hi @saudet ! How do I generate Java code from C/C++ header files？Thanks.

**Comment by duck123456** [comment]
I want to link C/C++ SDK dynamic library through Javacpp and use it. How do I do that？

**Comment by saudet** [comment]
Start from here: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by duck123456** [comment]
> 从这里开始：[https](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes) : [//github.com/bytedeco/javacpp/wiki/Mapping-Recipes](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes)

A command to automatically generate Java code from header files was not found. Can Javacpp automatically generate Java interface code?

**Comment by saudet** [comment]
It's not fully automated, no.

**Comment by saudet** [comment]
To make the process more automated, we'll first need to improve the parser, for example, by using Clang, see issue #51.
