### ISSUE TITLE
FFmpegFrameRecorder  paramters

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacpp#356]
Dear javac author, really appreciate to use this library.

Just have some questions about FFmpegFrameRecorder creation, what paramters i should give, currently i set the paramters below, may i know where can i find more information regarding this? thanks!

            recorder = new FFmpegFrameRecorder(pOutputPath,
                    pVideoWidth, pVideoHeight, channel);
            recorder.setSampleRate(sampleRate);

        recorder.setFormat("mp4");
        recorder.setVideoQuality(0);
        recorder.setVideoOption("preset", "veryfast"); // or ultrafast or fast, etc.
       recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); black screen.
        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);

**Comment by saudet** [comment]
They're all documented as part of FFmpeg here:
https://ffmpeg.org/documentation.html

**Comment by saudet** [comment]
They sometimes have different names than the ones used by the `ffmpeg` program though, so feel free to ask about options that you don't seem to be able to use.
