### ISSUE TITLE
[javacpp-project] Problem with multiple inheritance in C++

### ISSUE THREAD

**Issue by AnDevi** [bytedeco/javacpp#360]
Here is my example code:
https://github.com/AnDevi/javacpp_example/tree/master/example 

What I want do is generate class MyClass (https://github.com/AnDevi/javacpp_example/blob/master/example/libs/example/include/example.hpp) without generating BaseA, BaseB and BaseC classes in java file (https://github.com/AnDevi/javacpp_example/blob/master/example/ExampleLibrary.java). 
MyClass have to inherit after 3+ classes. 
Is it possible ? I assume that it is, but I have to some special tricks in config file (https://github.com/AnDevi/javacpp_example/blob/master/example/ExampleConfig.java) to handle it.

Thanks a lot for help !

**Comment by saudet** [comment]
Ah, I see, you did try to do the right thing as explained in a previous message you sent to the mailing list, but you're getting a compile error:
https://groups.google.com/forum/#!msg/javacpp-project/xyosH9eyQC4/ahGDXp_JAwAJ

**Comment by saudet** [comment]
Fixed in commit 3e5a0dfc5a9334d2c7dfda5f044082364abcdc9b. Please give it a try with [the snapshots](http://bytedeco.org/builds/) and something like:
`infoMap.put(new Info("A", "B", "C").pointerTypes("Pointer"))`.
Thanks for reporting this issue!

**Comment by AnDevi** [comment]
I would like to check it with pleasure.
Have you any instructions how to build javacpp source code and pack it into
.jar file ?


pt., 15 lis 2019 o 08:37 Samuel Audet <notifications@github.com> napisał(a):

**Comment by saudet** [comment]
The JAR file is already available here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/

**Comment by AnDevi** [comment]
I've tried two JARs:
javacpp-1.5.3-20191115.041524-4.jar
<https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.3-SNAPSHOT/javacpp-1.5.3-20191115.041524-4.jar>
javacpp-1.5.3-20191115.074016-5.jar
<https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.5.3-SNAPSHOT/javacpp-1.5.3-20191115.074016-5.jar>
from today.
unfortunately, none of those doesn't work :(
I have still the same error.


pt., 15 lis 2019 o 12:50 Samuel Audet <notifications@github.com> napisał(a):

**Comment by saudet** [comment]
The example you provided works for me. Could you provide one that fails?

**Comment by AnDevi** [comment]
It fails for with that example I've shared with you on GitHub.

pt., 15 lis 2019 o 14:13 Samuel Audet <notifications@github.com> napisał(a):

**Comment by AnDevi** [comment]
Sorry, I made a little mistake, it's work for me as well. ! Thank You! :)

pt., 15 lis 2019 o 14:13 Samuel Audet <notifications@github.com> napisał(a):

**Comment by saudet** [comment]
Fix included in just released JavaCPP 1.5.3. Thanks for reporting and for testing!
