### ISSUE TITLE
Can not run in osgi

### ISSUE THREAD

**Issue by jiangyubao** [bytedeco/javacpp#361]
`public class Activator {
    private final static Logger logger = Logger.getLogger(Activator.class);

    public void doStart() {
	try {
	    new Square().main();
	} catch (Exception e) {
	    logger.error("", e);
	}
	
    }

    public void doStop() {
	
    }
}`

java.lang.RuntimeException: OpenCV(4.1.0) /Users/travis/build/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-4.1.0/modules/core/src/array.cpp:3293: error: (-2:Unspecified error) Unknown object type in function 'cvClone'

	at org.bytedeco.opencv.global.opencv_core.cvClone(Native Method)

**Comment by saudet** [comment]
You'll to pass a supported object to cvClone(). That's unrelated to OSGi.
