### ISSUE TITLE
Setters randomly not working

### ISSUE THREAD

**Issue by tmm1** [bytedeco/javacpp#364]
I recently upgraded from 1.4.3 to 1.5.3-SNAPSHOT built from master.

I'm experiencing a very strange intermittent issue since the upgrade, and looking to see if anyone has hunches on where the regression might have occurred.

I have some C code that invokes a javacpp FunctionPointer and passes in a pointer to a struct. I use that pointer to invoke several setters, passing in more function pointers. Randomly, when the C code examines the struct the fields are NULL.

This almost seems like a GC or compiler optimization issue. Has anyone experienced anything similar?

**Comment by saudet** [comment]
If you're not keeping references to the callbacks in fields, they are
probably getting garbage collected, yes.

**Comment by tmm1** [comment]
GC would explain the intermittent behavior, and I got some logs where I can see a GC happening right before the C code checks the fields.

I'm still confused about why this started only after the upgrade. I would expect the JNI layer to be holding a global reference to these fields to prevent them from being GC'd- did something change in this area since 1.4.3?

I will add some strong references and hopefully that resolves the issue..

**Comment by saudet** [comment]
Nothing significant changed, but a couple of differences in timing can
affect GC. If you wish to manage manually the memory of those objects,
either call deallocate() on them once you're done with them, or call
deallocate(false) to remove them from the GC queue permanently...
