### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) and junk value.

### ISSUE THREAD

**Issue by kechikkuat** [bytedeco/javacpp#366]
Hi, 
I'm getting this error. Still newbie to this javacpp. Any help much appreciated

I'm getting this error when calling getSomeNames()
```
 A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffbb10c1637, pid=28656, tid=0x0000000000001794
JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [VCRUNTIME140.dll+0x1650]
```

Also I'm getting junk value when calling this method getName().getString()
expected "Abc" but what I'm getting is "ÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝ"

For boolean / long method it return correct value.

Here is snippet of my code

**some_h_file.h**
```
class CLASS_DECLSPECPSABC Abc{
private:
	Abc(AbcInterfaceUI *_interfaceGui, AbcAbstract *abcFactory);
	virtual ~Abc();
public:
	static Abc* getInstance(AbcInterfaceUI *_interfaceGui, AbcAbstract *abcFactory);
public:
	char* getName();
	long getDays();
	std::vector<const char*>* getSomeNames();
        bool isEnabled()
}
```

**Java Code Snippet**
**Abc,java**
```
@Platform(include = {"<string>", "<vector>", "<sstream>", "<iostream>", "some_h_file.h", "abcinterfaceui.h", "abcabstract.h"},
        includepath = {"C:\\some\\path\\to\\api\\"},
        preload = {"dll_file_name"},
        preloadpath = "C:\\some\\path\\to\\api\\",
        linkpath = "C:\\some\\path\\to\\api\\",
        link = {"lib_file_name"},
        define = "CLASS_DECLSPECPSABC")
@Name("Abc ")
public class Abc extends Pointer{
    static {
        Loader.load();
    }

    public static native @ByPtr Abc getInstance(@ByPtr AbcInterfaceUIImplementation interfaceGui, @ByPtr AbcAbstract emptyBar);

    public native long getDays();
    public native @Cast("char*") BytePointer getName();
    public native boolean isEnabled();
    public native Vector.CharPoint getSomeNames();

    public static void main(String[] args) {
        Abc abc = getInstance();
        System.out.println(abc.getDays());
        System.out.println(abc.isEnabled());
        System.out.println(abc.getName().getString());
        System.out.println(abc.getSomeNames());
    }

    public static Abc getInstance(){
        AbcInterfaceUIImplementation interfaceGui = new AbcInterfaceUIImplementation ();
        AbcAbstract  emptyBar = new AbcAbstract();

        return getInstance(interfaceGui, emptyBar);
    }
}
```
**Vector.java**
```
@Platform(include = "<vector>")
@Name("std")
public class Vector extends Pointer{
    @Name("vector<const char*>")
    public static class CharPoint extends Pointer{
        static{Loader.load();}
        public CharPoint(){
            allocate();
        }
        public CharPoint(long n){
            allocate(n);
        }
        public CharPoint(Pointer p){
            super(p);
        }

        @Name("operator=")
        public native @ByRef CharPoint put(@ByRef CharPoint x);

        @Name("operator[]")
        public native @StdVector CharPoint get(long n);
        public native @StdVector CharPoint at(long n);

        public native long size();
        public native @Cast("bool") boolean empty();
        public native void resize(long n);
        public native @Index long size(long i);                   // return (*this)[i].size()
        public native @Index @Cast("bool") boolean empty(long i); // return (*this)[i].empty()
        public native @Index void resize(long i, long n);         // (*this)[i].resize(n)

        public native @Index Pointer get(long i, long j);  // return (*this)[i][j]
        public native void put(long i, long j, Pointer p);

        private native void allocate();
        private native void allocate(long n);
    }
}
```

**Comment by saudet** [comment]
The header file looks simple enough. Could you try running the Parser on it? 
See https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by kechikkuat** [comment]
> The header file looks simple enough. Could you try running the Parser on it?
> See https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

Hi @saudet,

I tried using the parser and it generated this for the
`public native @Cast("const char**") @StdVector PointerPointer getSomeNames();`

Now the error was different from the previous one.
```
A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_GUARD_PAGE (0x80000001) at pc=0x00007ffbb10c1665, pid=18416, tid=0x0000000000006604
#
# JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [VCRUNTIME140.dll+0x1665]
```

**Comment by saudet** [comment]
There's probably just something wrong with the memory allocated for that `std::vector<const char*>`. Make sure you can use it normally from C++ as well.

**Comment by saudet** [comment]
In any case, if you can provide a small example to reproduce this here, I could help you more.

**Comment by kechikkuat** [comment]
> There's probably just something wrong with the memory allocated for that `std::vector<const char*>`. Make sure you can use it normally from C++ as well.

Hi @saudet,

I can run normally in C++ and the output was correct. But not in java the output return in junk value for `char*` value type "ÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝÝ" and it will crash for value type `std::vector<const char*>* `but for other type like long/short/bool/int it return the value as expected.

Is this problem can be related to compiler? 
Any suggestion what need to be check/done for this problem?

I'll provide you some example to reproduce this problem later.

**Comment by saudet** [comment]
You need to use the exact same C++ compiler to compile everything, yes. If you're not doing that, that's why it's crashing.

**Comment by kechikkuat** [comment]
Hi @saudet,

Thanks for your enlightenment and help, can close this issue it seems compiler issues & some minor code issue.

**Comment by yb-hub** [comment]
how could i catch this error in my java code?

**Comment by saudet** [comment]
@yb-hub We can't, it's a hard crash of the virtual machine. We can do something about it if we run the unstable code in a separate process though.

**Comment by yb-hub** [comment]
how could i catch this error in my java code?

> @yb-hub We can't, it's a hard crash of the virtual machine. We can do something about it if we run the unstable code in a separate process though

oh thanks
