### ISSUE TITLE
How to get thrust::pair first and second value

### ISSUE THREAD

**Issue by rainsonGain** [bytedeco/javacpp#368]
From https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA, I write thrust java code, but when I use first() method to get the first field of thrust::pair, 
**error: expression preceding parentheses of apparent call must have (pointer-to-) function type**
so how to get thrust::pair first and second value ? 

Code example as follows:
```java
@Platform(include="<thrust/pair.h>")
@Namespace("thrust")
public class Thrust {

    static { Loader.load(); }

    @Name("pair<int, double>")

    public static class Pair extends Pointer {
        static { Loader.load(); }
        public Pair(IntPointer key, DoublePointer value){
            allocate(key, value);
        }
        private native void allocate(@ByRef IntPointer k, @ByRef DoublePointer v);
        // will happen error
        public native IntPointer first();
        // will happen error
        public native IntPointer first(IntPointer p);
    }

    public static void main(String[] args) {
        IntPointer i = new IntPointer(1);
        i.put(10);
        DoublePointer d = new DoublePointer(1);
        d.put(10.0);
        Pair p = new Pair(i, d);
        System.out.println(p.first());
    }
}
```
Please help me out !
Thanks

**Comment by saudet** [comment]
`first` and `second` are member variables, not functions, so we need to declare them in pairs of getter and setter methods, something like this:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/gen/java/org/bytedeco/tensorflow/StringIntPair.java#L24
Or if they are not settable, we can use the `@MemberGetter` annotation, something like this:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code

**Comment by rainsonGain** [comment]
> `first` and `second` are member variables, not functions, so we need to declare them in pairs of getter and setter methods, something like this:
> https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/gen/java/org/bytedeco/tensorflow/StringIntPair.java#L24
> Or if they are not settable, we can use the `@MemberGetter` annotation, something like this:
> https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code

TKS reply!
First method can't work. Do we have some complete example in second method ?  
I write infoMap like this, but I don't know how to use it and combine the code:

@Properties(
    value = @Platform(
        include = {"<thrust/pair.h>"},
        link = {"thrust"}
    ),
    target = "thrust"
)
public class MyConfig implements InfoMapper {
    
    @Override
    public void map(InfoMap infoMap) {
        infoMap.put(
            new Info("thrust::pair::first").javaText("public native @MemberGetter @ByVal FieldType first();"));
        infoMap.put(
            new Info("thrust::pair::second").javaText("public native @MemberGetter @ByVal FieldType second();"));
    }
}

**Comment by rainsonGain** [comment]
> `first` and `second` are member variables, not functions, so we need to declare them in pairs of getter and setter methods, something like this:
> https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/gen/java/org/bytedeco/tensorflow/StringIntPair.java#L24
> Or if they are not settable, we can use the `@MemberGetter` annotation, something like this:
> https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code

C struct field is public, I find `NativeLibrary` example can access the public member variable directly, but thrust::pair can't, so I think somethings wrong.  
thrust pair use template and typedef, I don't know if it has any impact, code as follows :
```C++
template <typename T1, typename T2>
  struct pair
{
  typedef T1 first_type;

  typedef T2 second_type;

  first_type first;

  second_type second;

  __host__ __device__ pair(void);

  inline __host__ __device__
  pair(const T1 &x, const T2 &y);
}
```

**Comment by saudet** [comment]
Just something like this should work:
```java
        public native IntPointer first();
        public native Pair first(IntPointer p);
```
Honestly, in the case of Thrust, I'm not sure if using the Parser would be easier than to write the declarations manually, but I think it's worth a try:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#defining-wrappers-for-basic-c-containers
Something like this for that pair might work:
```java
infoMap.put(new Info("basic/containers").cppTypes("thrust::pair"));
infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair").define());
```

**Comment by rainsonGain** [comment]
> ```java
> infoMap.put(new Info("basic/containers").cppTypes("thrust::pair"));
> infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair").define());
> ```

TKS !
`public native IntPointer first();`
will happen error
**error: expression preceding parentheses of apparent call must have (pointer-to-) function type**
`public native Pair first(IntPointer p);`
will happen error
**error: macro "offsetof" passed 3 arguments, but takes just 2
         { sizeof(thrust::pair<int, double>), offsetof(thrust::pair<int, double>, first) },
                                                                                       ^**
The complete code:
```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include="<thrust/pair.h>")
@Namespace("thrust")
public class C {
    static { Loader.load(); }

    @Name("pair<int, double>")
    public static class Pair extends Pointer {
        static { Loader.load(); }
        public Pair(Pointer p){
            super(p);
        }
        public Pair(int key, double value){
            allocate(key, value);
        }
        public Pair(IntPointer key, DoublePointer value){
            allocate(key, value);
        }
        private native void allocate(int k, double v); 
        private native void allocate(@ByRef IntPointer k, @ByRef DoublePointer v);
        public native IntPointer first();  public native Pair first(IntPointer first);
        //@MemberGetter public native double second();  public native Pair second(DoublePointer second);
    }

    public static void main(String[] args) {
        IntPointer i = new IntPointer(1);
        i.put(10);
        DoublePointer d = new DoublePointer(1);                                                                
        d.put(10.0);                                                                                           
        Pair p = new Pair(i, d);                                                                               
        //System.out.println(p.first());                                                                       
        System.out.println(p);                                                                                 
    }                                                                                                          
}
```

I will try infoMap, I have a little confused how to use infoMap. 
code as follows, but I don't know how to use it and combine the complete code above:
```java
@Properties(
    value = @Platform(
        include = {"<thrust/pair.h>"},
        link = {"thrust"}
    ),
    target = "thrust"
)
public class MyConfig implements InfoMapper {
    
    @Override
    public void map(InfoMap infoMap) {
        infoMap.put(
            infoMap.put(new Info("basic/containers").cppTypes("thrust::pair"));
            infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair").define());
            infoMap.put(
                new Info("thrust::pair::first").javaText("public native @MemberGetter @ByVal FieldType first();"));
            infoMap.put(
                new Info("thrust::pair::second").javaText("public native @MemberGetter @ByVal FieldType second();"));
    }
}
```

**Comment by saudet** [comment]
We can't use offsetof() with class templates, that's normal. Annotate with `@NoOffset` to prevent that code from getting generated.

The following seems to work fine for me. What errors are you getting?
```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.tools.*;
import org.bytedeco.javacpp.annotation.*;

@Properties(
    value = @Platform(
        includepath = {"/usr/local/cuda/include/"},
        include = {"<thrust/pair.h>"}
    ),
    target = "thrust"
)
public class MyConfig implements InfoMapper {
    
    @Override
    public void map(InfoMap infoMap) {
        infoMap.put(new Info("__host__", "__device__").cppTypes().annotations());
        infoMap.put(new Info("basic/containers").cppTypes("thrust::pair"));
        infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair"));
    }
}
```

**Comment by rainsonGain** [comment]
> We can't use offsetof() with class templates, that's normal. Annotate with `@NoOffset` to prevent that code from getting generated.
> 
> The following seems to work fine for me. What errors are you getting?
> 
> ```java
> import org.bytedeco.javacpp.*;
> import org.bytedeco.javacpp.tools.*;
> import org.bytedeco.javacpp.annotation.*;
> 
> @Properties(
>     value = @Platform(
>         includepath = {"/usr/local/cuda/include/"},
>         include = {"<thrust/pair.h>"}
>     ),
>     target = "thrust"
> )
> public class MyConfig implements InfoMapper {   
>     @Override
>     public void map(InfoMap infoMap) {
>         infoMap.put(new Info("__host__", "__device__").cppTypes().annotations());
>         infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair"));
>     }
> }
> ```

TKS!
The codes above no problem, if I not append `public native IntPointer first();`, run order:
java -jar javacpp.jar MyConfig.java
java -jar javacpp.jar C.java

But when I add `first()` in C.java,  error happen
```
/usr/local/jniC.cpp: In function '_jobject* Java_C_00024IntDoublePair_first(JNIEnv*, jobject)':

/usr/local/jniC.cpp:458:27: error: expression cannot be used as a function
         rptr = ptr->first();
                           ^
```
add `infoMap.put(new Info("thrust::pair::first").javaText("public native @MemberGetter @ByVal FieldType first();"));` also no work.

C.java complete code:
```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(includepath = {"/usr/local/cuda/include/"}, include="<thrust/pair.h>")
@NoOffset
@Namespace("thrust")
public class C {
    static { Loader.load(); }

    @Name("pair<int, double>")
    public static class IntDoublePair extends Pointer {
        static { Loader.load(); }
        public IntDoublePair(Pointer p){
            super(p);
        }
        public IntDoublePair(int key, double value){
            allocate(key, value);
        }
        public IntDoublePair(IntPointer key, DoublePointer value){
            allocate(key, value);
        }
        private native void allocate(int k, double v);
        private native void allocate(@ByRef IntPointer k, @ByRef DoublePointer v);
        public native IntPointer first();
      //  public native Pair first(IntPointer first);
        //@MemberGetter public native double second();  public native Pair second(DoublePointer second);
    }

    public static void main(String[] args) {
        IntPointer i = new IntPointer(1);
        i.put(10);
        DoublePointer d = new DoublePointer(1);
        d.put(10.0);
        IntDoublePair p = new IntDoublePair(i, d);
        //System.out.println(p.first());
        System.out.println(p);
}
```

**Comment by rainsonGain** [comment]
> We can't use offsetof() with class templates, that's normal. Annotate with `@NoOffset` to prevent that code from getting generated.
> 
> The following seems to work fine for me. What errors are you getting?
> 
> ```java
> import org.bytedeco.javacpp.*;
> import org.bytedeco.javacpp.tools.*;
> import org.bytedeco.javacpp.annotation.*;
> 
> @Properties(
>     value = @Platform(
>         includepath = {"/usr/local/cuda/include/"},
>         include = {"<thrust/pair.h>"}
>     ),
>     target = "thrust"
> )
> public class MyConfig implements InfoMapper {   
>     @Override
>     public void map(InfoMap infoMap) {
>         infoMap.put(new Info("__host__", "__device__").cppTypes().annotations());
>         infoMap.put(new Info("thrust::pair<int,double>").pointerTypes("IntDoublePair"));
>     }
> }
> ```

TKS very much for your help ! ! 
I didn't take long to learn javacpp lib, will try more features, and will be promoted for more colleagues to use.

**Comment by saudet** [comment]
So, you got it working? Great! Just keep asking if you have any more questions. Thanks!
