### ISSUE TITLE
Master Caffe doesn't build

### ISSUE THREAD

**Issue by cypof** [bytedeco/javacpp#37]
It seems there is a pure abstract method that the parser chokes on:

javacpp-presets/caffe/cppbuild/linux-x86_64/include/caffe/data_layers.hpp:83: Could not parse declaration at '0'

**Comment by saudet** [comment]
Yeah, there's a couple of other things that broke too. Trying to find the time to get this fixed...

**Comment by saudet** [comment]
Ok, it should work now!

**Comment by saudet** [comment]
Works now, so thanks for reporting!
