### ISSUE TITLE
std:vector<std:string> to a string array?

### ISSUE THREAD

**Issue by VahidMostofi** [bytedeco/javacpp#372]
Is it possible to cast a std:vector<std:string> to a string array? 
My c++ function is returning a vector<std:string>.

**Comment by saudet** [comment]
Sure, we can create an instance of `std::vector<std::string>` like this:
```java
InfoMap.put(new Info("std::vector<std::string>").pointerTypes("StringVector").define())
```
A lot of presets already do that, so check those for some examples:
- https://github.com/bytedeco/javacpp-presets/blob/master/arrow/src/main/java/org/bytedeco/arrow/presets/arrow.java
- https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/main/java/org/bytedeco/tensorflow/presets/tensorflow.java
- etc
