### ISSUE TITLE
Unable to pass Java implementations of interfaces into methods that take unique_ptr

### ISSUE THREAD

**Issue by davidsj2** [bytedeco/javacpp#378]
I haven't been able to correctly pass in objects allocated in Java to methods that take a unique_ptr "sink" argument.  I'm attaching a simple example that contains a very small interface and implementations of that interface in C++ and Java.  There is a C++ factory class with a factory method that returns instantiations of the C++ implementation as a unique_ptr.  There is a simple registry class that accepts a unique_ptr of that interface.  The registry "moves" the argument into a vector.

There is a Java test app that creates some of the C++ implementation objects using the factory method and adds them to the registry.  It then creates some Java implementation objects and passes them to the registry.  Once the add method returns, it appears the underlying memory is free'd as the element in the vector is no longer valid.  Note that this same thing happens if I manually allocate a C++ implementation without the factory method and pass it through.

How can I get unique_ptr semantics to work correctly when passing in an object that wasn't allocated as a unique_ptr from a C++ factory method?

Use build.sh to compile.  Use run.sh to run.

[example3.tar.gz](https://github.com/bytedeco/javacpp/files/4048674/example3.tar.gz)

**Comment by saudet** [comment]
How would you get this to work in C++? The user would have to provide a new factory method?

**Comment by davidsj2** [comment]
Either that or just directly allocate an object tied a unique_ptr and call add.

**Comment by saudet** [comment]
Ok, so we could basically do the same thing, for example:
```cpp
  std::unique_ptr<IConfig> uniquify(IConfig* x) {
    return std::unique_ptr<IConfig>(x);
  }
```
And then this works just fine:
```java
IConfig j1 = factory.uniquify(new JavaIConfig(3));
icr.add(j1);
IConfig j2 = factory.uniquify(new JavaIConfig(4));
icr.add(j2);
```
We could further wrap this up in Java with private constructors... Sounds good?

**Comment by davidsj2** [comment]
Thanks for the suggestion.  I was able to get something similar to that working.  However, I'm facing issues with implementing interfaces in Java that return unique_ptr.  I'll work up an example and file a different issue for that, though.
