### ISSUE TITLE
JavaCv Mat to Opencv Mat

### ISSUE THREAD

**Issue by kleberbueno** [bytedeco/javacpp#38]
Hi guys

First of all I would like to apologize to create a label almost similar to Issue #4. I am not a expert in Java as well as c++.
However I have been spent last 4 days to take a solution and I got frozen.

I have rewrite c++ code of Mastering Opencv book , chapter 5, regard Licence plate detecting to java code. But the original c++ code uses filestorage that is not yet implemented in opencv wrapper. So I found FileStorage for javacv (javacPP-presets) that is working fine and can be used to return a CvMat class.

The issue is the CvMat data should reflect in opencv.Mat instance. But I know they are not compatible and I really dont know how to build a parser to them. 

I tried to run all CvMat data and use "put" method to pass it to opencv.mat. But 
data got wrong.

if someone can help with a tip. Source code is really great, but if shows me the way to take would be really helpful.

thanks in advance

**Comment by saudet** [comment]
Could you provide the few lines of C++ code you are having trouble with? (BTW, we can convert from CvMat to Mat with the [cvarrToMat()](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.html#cvarrToMat-org.bytedeco.javacpp.helper.opencv_core.CvArr-) function.)

**Comment by kleberbueno** [comment]
Hi Saudet

Thanks so much for your prompt reply.
Sorry I did not attach code earlier

Here is the code:


//using javacpp to read .xml file since opencv there is no wrapper
    	org.bytedeco.javacpp.opencv_core.FileStorage storage = new org.bytedeco.javacpp.opencv_core.FileStorage("resources\\ocr.xml", org.bytedeco.javacpp.opencv_core.FileStorage.READ);
    	org.bytedeco.javacpp.opencv_core.CvMat cvMat2 = new org.bytedeco.javacpp.opencv_core.CvMat(storage.get("TrainingDataF15").readObj());
    	
    	
// After that the whole code ahead is writen with opencv wrapper.
//I tried to convert cvMat to opencv.Mat since only opencv.Mat is used ahead.

  	org.opencv.core.Mat TrainingData = new org.opencv.core.Mat() ; 
    	
TrainingData =  retornaMat(cvMat2);

**Comment by saudet** [comment]
Ah, you're trying to use `org.opencv.core.Mat`. I would recommend not using it. Why do you need it?

**Comment by kleberbueno** [comment]
As I said you. I was tryting to rewrite code from Mastering OpenCv book. Chapter 5.
So opencv was the closest of c++ I found.

So if I decide to move now to JAVACV it would take so much time and double work.

That is I decided at that moment.

**Comment by saudet** [comment]
Ok, anyway, I didn't test it, but this should work:
```java
Mat mat2 = new Mat(null) { { address = mat.getNativeObjAddr(); } };
```

**Comment by saudet** [comment]
Or the other way around:
```java
Mat mat = new Mat(mat2.address());
```

**Comment by kleberbueno** [comment]
My friend.
Both worked and you saved my time.
thanks so much.
Really good to have guys like you.

Have a nice week.

You can consider this closed.

**Comment by davvyy00** [comment]
public Frame processFrame(Frame vFrame){

        javacvInput = converterToMat.convert(vFrame);
        Log.i("mat-cvin", javacvInput.toString());

        //convert javacv mat to opencv mat
        rgba = new Mat(javacvInput.address());


        // Convert rgba to hsv color space
        Imgproc.cvtColor(rgba, hsv, Imgproc.COLOR_RGB2HSV);

        opencv_core.Mat output = new opencv_core.Mat() { { address = hsv.getNativeObjAddr(); } };

        return converterToMat.convert(output);

    };

**Comment by davvyy00** [comment]
any idea wht this does not work, I want to use opencv for image processing and javacv for ffmpeg, I'm trying to convert javacv mat to opencv mat then back to javacv mat???? any ideas

**Comment by saudet** [comment]
@davvyy00 What do you mean by "this does not work?" Could you provide more details?

**Comment by davvyy00** [comment]
When I try to convert the output javacv mat from the hsv opencv mat

**Comment by davvyy00** [comment]
opencv_core.Mat output = new opencv_core.Mat() { { address = hsv.getNativeObjAddr(); } }; This line I want to convert opencv mat to javacv and I just seem to get back an rgba mat not a hsv one

**Comment by davvyy00** [comment]
//convert javacv mat to opencv mat
    rgba = new Mat(javacvInput.address());

I think this works but I'm not 100 percent sure

**Comment by davvyy00** [comment]
Mat mat2 = new Mat(null) { { address = mat.getNativeObjAddr(); } }; and the null part of this gives an error

**Comment by davvyy00** [comment]
11-01 13:51:15.559 5011-5011/com.example.opencv I/mat-javacv-INPUT: org.bytedeco.javacpp.opencv_core$Mat[width=1920,height=1080,depth=8,channels=3]
11-01 13:51:15.559 5011-5011/com.example.opencv I/mat-openCV-rgba: Mat [ 1080*1920*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0x9df74430, dataAddr=0xffffffff9a000000 ]
11-01 13:51:15.569 5011-5011/com.example.opencv I/mat-openCV-hsv: Mat [ 1080*1920*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0xffffffffaf0aad98, dataAddr=0xffffffff90400010 ]
11-01 13:51:15.569 5011-5011/com.example.opencv I/mat-javaCV-output: com.example.opencv.VideoActivity$2[width=1920,height=1080,depth=8,channels=3]

**Comment by davvyy00** [comment]
And one thing I noticed is that the output javacv type is com.example.opencv.VideoActivity instead of org.bytedeco.javacpp.opencv_core$Mat

**Comment by saudet** [comment]
Well, there's obviously something wrong with your code, but since I don't have you code, this is hard for me to debug.

Could you instead prepare a few lines of code that exhibit this bug so that I can test it here? Thank you

**Comment by davvyy00** [comment]
public class VideoActivity extends ActionBarActivity {

    AndroidFrameConverter converterToBitmap = new AndroidFrameConverter();
    OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
    Java2DFrameConverter javaConverter = new Java2DFrameConverter();

    // Opencv mat objects
    private Mat rgba =  new Mat();
    private Mat grey = new Mat();
    private Mat greySubmatrix = new Mat();
    private Mat hsv = new Mat();
    private Mat filteredByColour = new Mat();
    private Mat contoursMat = new Mat();

    //Javacv mat used for conversion from javacv method
    opencv_core.Mat javacvInput = new opencv_core.Mat();
    opencv_core.Mat javacvOutput = new opencv_core.Mat();

    //Scalers for hsv
    Scalar hsvMinScaler;
    Scalar hsvMaxScaler;



    //Indices of hsv values
    private final int HUE_MIN_INDEX =0;
    private final int HUE_MAX_INDEX =1;
    private final int SAT_MIN_INDEX =2;
    private final int SAT_MAX_INDEX =3;
    private final int VALUE_MIN_INDEX =4;
    private final int VALUE_MAX_INDEX =5;

    //Array to hold the hsv values
    int[] hsvNums = new int[]{};

    //Store the values of the hsv values to avoid array lookup
    private int hueMin;
    private int hueMax;
    private int satMin;
    private int satMax;
    private int valMin;
    private int valMax;

    // statically load the opencv so it does not need to download opencv
    static {
        // loads the library opencv java
        if (!OpenCVLoader.initDebug()) {
            // Handle initialization error
            Log.e("openCv init", "warning: open cv not connected");

        } else {
            Log.d("openCv init", " open cv is connected");

        }
        // load jni libraries here

    }

    // The OpenCV loader callback.
    private BaseLoaderCallback mLoaderCallback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch (status) {
                case LoaderCallbackInterface.SUCCESS: {

                }
                break;
                default:
                    super.onManagerConnected(status);
                    break;
            }
        }
    };



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);

        //Initializing hsv values with static array from calibrate camera activity
        hsvNums = CalibrateActivity.hsvNums;
        hueMin = hsvNums[HUE_MIN_INDEX];
        hueMax = hsvNums[HUE_MAX_INDEX];
        satMin = hsvNums[SAT_MIN_INDEX];
        satMax = hsvNums[SAT_MAX_INDEX];
        valMin = hsvNums[VALUE_MIN_INDEX];
        valMax = hsvNums[VALUE_MAX_INDEX];

        //Initial hsv scalars
        hsvMinScaler = new Scalar(hueMin, satMin, valMin);
        hsvMaxScaler = new Scalar(hueMax, satMax, valMax);




    }



    public void processVideo(View v){
        //Full HD
        File videoFile = new File(getGalleryPath() + "Camera/20151030_144103.mp4");
        //ULTRA HD
        //File videoFile = new File(getGalleryPath() + "Camera/20151030_163023.mp4");

        //Initialize and start the video grabber
        FFmpegFrameGrabber videoGrabber = initGrabber(videoFile, "mp4");

        //Initialize and start the video recorder
        FFmpegFrameRecorder recorder = initRecorder(getGalleryPath()+"Camera/test3.mp4","mp4",
                videoGrabber.getFrameRate(), videoGrabber.getImageWidth(), videoGrabber.getImageHeight());

        Frame vFrame = null;
        int frameCounter=0;
        int counterNoData=0;

        long start = System.currentTimeMillis();

        do//while there are frames left to process
        {
            try
            {   //Grab the image from the video frame, no audio
                vFrame = videoGrabber.grabImage();
                if(vFrame != null) {
                    frameCounter++;
                    //Process the frame
                    processFrame(vFrame);
                    //Record the frame
                    recorder.record(vFrame);


                    Log.i("frame",Integer.toString(vFrame.imageStride)+" "+Integer.toString(vFrame.imageDepth)
                            +" "+Integer.toString(vFrame.imageWidth)+" "+Integer.toString(vFrame.imageHeight));
                }
            } catch (Exception e)
            {
                Log.e("javacv", "video grabFrame failed: "+ e);
            }
        }while(vFrame != null);

        long end = System.currentTimeMillis();

        Log.i("time", Long.toString(end-start));

        Log.i("javacv", "num frames: "+Integer.toString(frameCounter)+" num frames no data: "+Integer.toString(counterNoData));

        //Stop the video grabber
        stopVideoGrabber(videoGrabber);
        //Stop the recorder and save the new video
        stopRecorder(recorder);
    }

    public Frame processFrame(Frame vFrame){

        javacvInput = converterToMat.convert(vFrame);
        Log.i("mat-javaCV-input", javacvInput.toString());

        //convert javacv mat to opencv mat --- possible problem conversion
        rgba = new Mat(javacvInput.address());


        // Convert rgba to hsv color space
        Imgproc.cvtColor(rgba, hsv, Imgproc.COLOR_RGB2HSV);

        //convert javacv mat to opencv mat
        //Think this line is the problem
        opencv_core.Mat output = new opencv_core.Mat() { { address = hsv.getNativeObjAddr(); } };
        Log.i("mat-javaCV-output", output.toString());

        return converterToMat.convert(output);


    };




    public FFmpegFrameRecorder initRecorder(String filename, String videoType, double frameRate, int width, int height){
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(filename,  width, height);

        recorder.setFormat(videoType);
        recorder.setFrameRate(frameRate);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        //Ultrafast gives a small low quality video but is very fast
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);


        try {
            recorder.start();
        }catch (Exception e){
            Log.e("javacv","Recorder failed to start", e);
        }
        return recorder;
    }

    public void stopRecorder(FFmpegFrameRecorder recorder){
        try
        {
            recorder.stop();
        }catch (Exception e)
        {
            Log.e("javacv", "Failed to stop video recorder", e);
            return ;
        }
    }

    public void stopVideoGrabber(FFmpegFrameGrabber videoGrabber){
        try
        {
            videoGrabber.stop();
        }catch (Exception e)
        {
            Log.e("javacv", "failed to stop video grabber", e);
            return ;
        }
    }

    public FFmpegFrameGrabber initGrabber(File videoFile, String videoType){
        FFmpegFrameGrabber videoGrabber = new FFmpegFrameGrabber(videoFile);
        try
        {
            videoGrabber.setFormat(videoType);//mp4 for example
            videoGrabber.start();
            Log.i("javacv", "VideoGrabber started with " + videoGrabber.getLengthInFrames() + "frames" +
                    " and framerate: " + videoGrabber.getFrameRate());
        } catch (Exception e)
        {
            Log.e("javacv", "Failed to start grabber" + e);

        }
        return videoGrabber;
    }

    private static String getGalleryPath() {
        return Environment.getExternalStorageDirectory() + "/" + Environment.DIRECTORY_DCIM + "/";
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_video, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}

**Comment by saudet** [comment]
Could you reduce that to a *self-contained* code snippet of less than about
20 lines? Thank you

**Comment by XuHuaiyu** [comment]
Hi, guys
How can I read .yml file to opencv_core.Mat?
I tried the code above, but it seems not right for me ~

**Comment by saudet** [comment]
@XuHuaiyu Use the `FileStorage` API:
http://docs.opencv.org/2.4/modules/core/doc/xml_yaml_persistence.html
https://groups.google.com/forum/#!topic/javacv/ls1sMNmSnZY

**Comment by XuHuaiyu** [comment]
Hi Saudet,
Thanks so much for your prompt reply

I've tried the following code to read a .yml file into a Mat 

FileStorage fs = new FileStorage(tfIdfFilePath, FileStorage.READ);
Mat tfIdfOfBase = new Mat();
read(fs.get("TF-IDF"), tfIdfOfBase);
fs.release();
System.out.println(tfIdfOfBase.cols() + " " + tfIdfOfBase.rows());

Output: 0 0

the tfIdf file like this:

%YAML:1.0
TF-IDF: !!opencv-matrix
   rows: 112
   cols: 29048
   dt: f
   data: [ 0., 0.,...]


And when I use
Mat tfIdfOfBase = null;

The above code will got a NullPointerException

**Comment by saudet** [comment]
Do you some code that works in C++ that we could translate?

**Comment by XuHuaiyu** [comment]
Yeah
``` c++
        Mat tfIdfOfBase;
        FileStorage fs(tmpFileName, FileStorage::READ);
        fs["TF-IDF"] >> tfIdfOfBase;
        fs.release();

```

**Comment by saudet** [comment]
@XuHuaiyu This doesn't happen here with OpenCV 3.1. Did you try with OpenCV 3.1?

**Comment by keai4le** [comment]
Mat mat2 = new Mat((Pointer)null) { { address = mat.getNativeObjAddr(); } };
this work！

**Comment by leeking5300** [comment]
Frame frame = grabber.grab(); // ingore
org.bytedeco.javacpp.opencv_core.Mat m1 = matconverter.convert(frame); // create Mat 
org.opencv.core.Mat image = new org.opencv.core.Mat(m1.address());
//
org.bytedeco.javacpp.opencv_core.Mat m = 
				new org.bytedeco.javacpp.opencv_core.Mat((Pointer)null){{address = mat.getNativeObjAddr();}};

Running well..

**Comment by leeking5300** [comment]
Hi,I got something error messages from using
  [org.opencv.core.Mat image = new org.opencv.core.Mat(m1.address());].

**error messages:**
*** Error in `/opt/lee/jdk8/bin/java': double free or corruption (fasttop): 0x00007fd31dcc9910 *** 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0e39f83242, pid=8161, tid=139699203024640
#
# JRE version: Java(TM) SE Runtime Environment (8.0_73-b02) (build 1.8.0_73-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.73-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libopencv_java249.so+0x20e242]  Java_org_opencv_core_Mat_n_1delete+0x12
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.


**main code :** 

int i=1;
		for(;true;i++){
			// read 
			Frame frame = grabber.grab();
			if(frame==null){
				break;
			}
			org.bytedeco.javacpp.opencv_core.Mat m1 = matconverter.convert(frame);
			if(m1 == null){
				continue;
			}
			org.opencv.core.Mat image = new org.opencv.core.Mat(m1.address());
			// 
			int x = Math.abs(ran.nextInt() % (width /4));
			int y = Math.abs(ran.nextInt() % (height/4));
			int w = Math.abs(x + ran.nextInt() % width);
			int h = Math.abs(y + ran.nextInt() % height);
			if(i % 100 == 0){
				System.out.println(i+":"+x+","+y+","+w+","+h);
			}
			// combined
			final Mat image2 = combineImage(image,labelFileName,x,y,w,h);
			//
			org.bytedeco.javacpp.opencv_core.Mat m = 
					new org.bytedeco.javacpp.opencv_core.Mat((Pointer)null){{address = image2.getNativeObjAddr();}};
			recorder.record(converter.convert(m));
		}
		System.out.println("total image = "+i);
		recorder.stop();
		recorder.release();
		grabber.stop();
		grabber.release();

**Comment by saudet** [comment]
@leeking5300 Looks like a problem with the bindings from OpenCV. You should report that over there, not here.

**Comment by mnh-aj123** [comment]
@saudet can you tell me 
Mat x=new Mat(grabbedImage.address());

This line gets reference of grabbedImage but i need another object how could i get that .. Not using Clone whenever i use .clone() method it freezes my laptop ?

**Comment by mnh-aj123** [comment]
@saudet  can you tell me
Mat x=new Mat(grabbedImage.address());

This line gets reference of grabbedImage but i need another object how could i get that .. Not using Clone whenever i use .clone() method it freezes my laptop ?

**Comment by saudet** [comment]
Try Mat.copyTo().

**Comment by mnh-aj123** [comment]
I have tried it but it still freezes my laptop . I am unable to understand the problem 
grabbedImage.copyTo(previousFrame);
I am converting javacv mat to opencv mat .

**Comment by mnh-aj123** [comment]
@saudet  any method to clone this 
Javacv Mat to opencv Mat

Mat x=new Mat(grabbedImage.address());

I tried but it gives error by any means .

**Comment by tehseenmayar** [comment]
hey guys..
can anybody tell me how to write a mat object into a file ?
i have a mate object which i want to preserve for later use..
i am using opencv with java
please help me i am stuck

**Comment by tobidelbruck** [comment]
This post was very useful for me. We mainly use org.opencv.core classes in our project, but the bytedeco wrappers in opencv_core provide some functionality not available there. Here are some lines of code the allow us to write out the org.opencv.core.Mat objects and read them back in.

`   /**
     * Writes an XML file for the matrix X called path/X.xml
     *
     * @param dir path to folder
     * @param name base name of file
     * @param sMat the Mat to write
     */
    public void serializeMat(String dir, String name, Mat sMat) {
        try {
            String fn = dir + File.separator + name + ".xml";

            // convert org.opencv.core.Mat to opencv_core.Mat to use FileStorage class; see https://github.com/bytedeco/javacpp/issues/38
            opencv_core.Mat bdMat = new opencv_core.Mat() { { address = sMat.getNativeObjAddr(); } };
            opencv_core.FileStorage storage = new opencv_core.FileStorage(fn, opencv_core.FileStorage.WRITE);
            storage.write(name, bdMat);
            storage.release();

            log.info("saved calibration as yaml in " + fn);
        } catch (Exception ex) {
            Logger.getLogger(SingleCameraCalibration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Mat deserializeMat(String dir, String name) {
        String fn = dirPath + File.separator + name + ".xml";
        opencv_core.Mat bdMat = new opencv_core.Mat();

        opencv_core.FileStorage storage = new opencv_core.FileStorage(fn, opencv_core.FileStorage.READ);
        opencv_core.read(storage.get(name), bdMat);
        storage.release();
        if (bdMat.empty()) {
            return null;
        }
        // convert to org.opencv.core.Mat to return; see https://github.com/bytedeco/javacpp/issues/38
        org.opencv.core.Mat mat=new org.opencv.core.Mat(bdMat.address());
        return mat;
    }
`

**Comment by saudet** [comment]
@tobidelbruck Thanks! Though be careful, the Java API of OpenCV will always try to delete `Mat` objects it doesn't own. The `OpenCVFrameConverter.ToOrgOpenCvCoreMat` that I've introduced in commit https://github.com/bytedeco/javacv/commit/f3337fdf7a1f412746d0f5770be2c5aeaa73ef09 is a safer alternative.
