### ISSUE TITLE
Why does Indexer#close() method signature declares throwing Exception ?

### ISSUE THREAD

**Issue by lchdev** [bytedeco/javacpp#381]
I have a hard time figuring out why `Indexer#close()` declares throwing Exceptions, while all it does is calling `release()`, which in turn cannot throw checked exceptions.

From my understanding, it is not expected from Indexer subclasses to override the `close()` method directly (none of them currently do). The current signature makes it a little painful to use Indexer instances within try-with-resource blocks, as opposed to what can be done with `Pointer` or `PointerScope` instances.

**Comment by saudet** [comment]
I suppose it's probably not useful indeed. Mind sending a pull request? :)

**Comment by lchdev** [comment]
See #382

**Comment by saudet** [comment]
Change included in just released version 1.5.3. Thanks for the pull request!
