### ISSUE TITLE
Members by `->` Operator

### ISSUE THREAD

**Issue by helixd-2k18** [bytedeco/javacpp#383]
I want ask question about member access as in pointer, i.e. `->` operator. Can JavaCPP access into these members? I have some C++ classes (wrappers) with that operators, and internal `shared_ptr` members. Also, I mention about methods under that operator.

**Comment by saudet** [comment]
Yes, those are just normal functions but with a strange name, "operator ->()" in this case, as shown here: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#specifying-names-to-use-in-java

**Comment by helixd-2k18** [comment]
Another question. Can (or not) struct, that known only by java with pointer (i.e. Vulkan API structures from LWJGL3, known by pointer only and have no explicit type in C++) passed as `VkDeviceCreateInfo&` argument in C++ code?

**Comment by saudet** [comment]
Opaque pointers? Sure, they get marked with the `@Opaque` annotation like this: https://github.com/bytedeco/javacpp-presets/blob/master/cuda/src/gen/java/org/bytedeco/cuda/cudart/CUstream_st.java

**Comment by helixd-2k18** [comment]
I mean something alike that... 
```C++
// Some regular C++ class
class VulkanBased {
    void createDevice(VkDeviceCreateInfo& info);
}
```

```Java
// May to be code and syntax issues 
class VulkanBased {
    public native void createDevice(@AddressToReference("VkDeviceCreateInfo&") long info); // converts into `VkDeviceCreateInfo& info`
}

// from alternative universe of LWJGL3
VkDeviceCreateInfo deviceCreateInfo = VkDeviceCreateInfo.callocStack()
    .sType(VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO)
    .pNext(NULL); // omitted operations

// 
VulkanBased based = new VulkanBased();

// Important here: 
based.createDevice(deviceCreateInfo.address());
```

**Comment by saudet** [comment]
Sorry for the delay. This sounds like a cast? Something like `new VkDeviceCreateInfo() {{ address = ...; }}` should work.
