### ISSUE TITLE
how to place some additional c code into generated cpp

### ISSUE THREAD

**Issue by linzaihui** [bytedeco/javacpp#386]
Hello, I want to place some additional c code into generated cpp, using some javacpp functions and static variable like JavaCPP_getEnv JavaCPP_addressFID and JavaCPP_createPointer.

**Comment by saudet** [comment]
We can @Platform(include=...) any file we want, if that's the question?

**Comment by linzaihui** [comment]
> We can @platform(include=...) any file we want, if that's the question?

hi, can include cpp file? and insert into generated cpp?

**Comment by saudet** [comment]
Yes, that's how the `#include` directive works.

**Comment by linzaihui** [comment]
Hi， I've tried include=`{...,"a.cpp"}`，but found `#include "a.cpp"` in the generated jniXXXX.cpp. I can't use JavaCPP_getEnv JavaCPP_addressFID and JavaCPP_createPointer.

**Comment by saudet** [comment]
Well, they were not meant to be used by users, but yes we can use them. Why are you saying that we can't? What have you tried?

**Comment by linzaihui** [comment]
Actually, what I want to do is: to intergrate a third-party framework, I must give a function pointer to framework, and the framework will call this function repeatly in a thread pool. But I can't find any javacpp API to implement a function pointer. Please help me.

**Comment by saudet** [comment]
There's `FunctionPointer` for that, and here are a couple of examples:
https://github.com/bytedeco/javacpp#creating-callback-functions

**Comment by saudet** [comment]
Please let me know if you have any other questions!
