### ISSUE TITLE
Global variable setter with a namespace

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp#387]
Now I'm trying to port the LLVM Polly optimizer.
The code is this.
https://github.com/yukoba/javacpp-presets/commit/55d70bc448f617a78f11c9e20165948574b5b390

The generated jnipolly.cpp has the following setter code.
```cpp
JNIEXPORT void JNICALL Java_org_bytedeco_llvm_global_polly_PollyChunkSize__I(JNIEnv* env, jclass cls, jint arg0) {
    PollyChunkSize = arg0;
}
```

But it must have the namespace ```polly``` like this.
```cpp
JNIEXPORT void JNICALL Java_org_bytedeco_llvm_global_polly_PollyChunkSize__I(JNIEnv* env, jclass cls, jint arg0) {
    polly::PollyChunkSize = arg0;
}
```

Getter has the namespace ```polly``` correctly.
```cpp
JNIEXPORT jint JNICALL Java_org_bytedeco_llvm_global_polly_PollyChunkSize__(JNIEnv* env, jclass cls) {
    jint rarg = 0;
    int rval = polly::PollyChunkSize;
    rarg = (jint)rval;
    return rarg;
}
```

If I add ```polly::``` by hand, I can compile by this.
```
g++ -I/home/ubuntu/javacpp-presets/llvm/cppbuild/linux-x86_64/include/ -I/home/ubuntu/javacpp-presets/llvm/cppbuild/linux-x86_64/include/polly/ -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux /home/ubuntu/javacpp-presets/llvm/target/native/org/bytedeco/llvm/linux-x86_64/jnipolly.cpp /home/ubuntu/javacpp-presets/llvm/target/native/org/bytedeco/llvm/linux-x86_64/jnijavacpp.cpp -march=x86-64 -m64 -O3 -s -std=c++11 -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -Wall -fPIC -pthread -shared -o libjnipolly.so -L/home/ubuntu/javacpp-presets/llvm/cppbuild/linux-x86_64/lib/ -Wl,-rpath,/home/ubuntu/javacpp-presets/llvm/cppbuild/linux-x86_64/lib/ -lPolly -lLTO -lLLVM-9
```

What should I do to add the namespace to the global variable setter?

**Comment by saudet** [comment]
There might be an issue with the namespace of global variables. Are you able to reproduce this with a smaller example?

In any case, if this requires the C++ API of LLVM, it hasn't been mapped yet. So if it doesn't have a C API, we may need to map the necessary classes from LLVM first...

**Comment by yukoba** [comment]
The same thing happened on the small example too. I only tested on Ubuntu 18.04.
https://github.com/yukoba/javacpp-presets/tree/cppglobalvar/cppglobalvar

> In any case, if this requires the C++ API of LLVM, it hasn't been mapped yet. 

I know.
I have not tried, but I saw that 
```llvm::PassRegistry``` can be cast to ```LLVMPassRegistryRef```
and ```llvm::legacy::PassManagerBase``` can be cast to ```LLVMPassManagerRef```.
If it is true, I can use high level API. It is enough for me.

**Comment by saudet** [comment]
Thank you! I fixed this in the latest commit. Please give it a try with 1.5.3-SNAPSHOT.

**Comment by yukoba** [comment]
OK. Thank you. I can compile Polly. Next I will run this.
I will close this issue.
