### ISSUE TITLE
How to write Java code for extern "C" functions ?

### ISSUE THREAD

**Issue by nitin2212** [bytedeco/javacpp#397]
I have a Abc.cpp file containing function definitions inside extern "C" scope. How to call these functions using JavacCPP ?

**Comment by saudet** [comment]
Since the `extern "C"` block is already in the header file, the C++ compiler will pick it up just fine. We don't need to do anything special.

**Comment by saudet** [comment]
Simply follow, for example, this guide here and let me know if you have any additional questions:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes
