### ISSUE TITLE
JavaCpp example using Gradle

### ISSUE THREAD

**Issue by jferreira78** [bytedeco/javacpp#399]
Hi,

I have tried getting the example project to work. I know the example uses Maven to build the project but I was interested in using gradle with Eclipse. However, when I try to build and run the project I get an UnsatisfiedLinkError: no jnijavacpp in java.library.path. Has anyone else had the same issue? Or would I have to use Maven?

**Comment by saudet** [comment]
Please try to use Gradle JavaCPP instead: https://github.com/bytedeco/gradle-javacpp

**Comment by saudet** [comment]
These sample projects work just fine with Gradle:
https://github.com/bytedeco/gradle-javacpp/tree/master/samples/zlib
https://github.com/bytedeco/gradle-javacpp/tree/master/samples/javacv-demo

**Comment by jferreira78** [comment]
Thank you for the help! I appreciate it.

John
