### ISSUE TITLE
Annotation question

### ISSUE THREAD

**Issue by kmatzen** [bytedeco/javacpp#4]
I need some help with parameter annotations.  It would be nice if the answer could make it to the README or at least some tips to better understand the annotations for someone familiar with C++, but not so much Java.

I'm not using the javacpp-presets for opencv, just what is built by opencv itself.  I have a function that takes a const reference to a cv::Mat:
```
void foo(const cv::Mat& image);
```

I know how to annotate my java function for the following sort of call:
```
void bar(const cv::Mat* image)
```
```
public native void bar(@Cast("Mat*") long imagePtr);
public void foo(Mat image) { bar(imagePtr.getNativeObjAddr()); }
```

What annotations do I need to specify to get it to dereference the pointer after doing the cast to get it to work with foo above?

Here's what is generated for bar:
```
bar((Mat*)arg0);
```
Here's what I'd like for foo:
```
foo(*(Mat*)arg0);
```

**Comment by saudet** [comment]
So, I'm assuming everything is working out well enough, but let me know if you still have some issues, thanks!
