### ISSUE TITLE
generate java classes from header files that are related

### ISSUE THREAD

**Issue by linzaihui** [bytedeco/javacpp#404]
Give three large header files: A B and C, which B and C include A both. How to generate java class A B and C using `InfoMapper` and `org.bytedeco.javacpp.annotation.Properties`. My problem is that when generating B and C, structures and other definitions in A will be generated into B and C.

**Comment by saudet** [comment]
If we can consider A to be a separate module, you can create an `InfoMapper` class for that one, and do `@Properties(inherit = A.class, ...)` in the other ones.
