### ISSUE TITLE
parser bug C++

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp#406]
When i try to parse C++ projects
almost all

         xxx
                : ptr(ptr) {}

1

         UnigineVector.h:354:Unexpected token '('
         FROM:
         IteratorTemplate(IteratorType *ptr)
                : ptr(ptr) {}
                

          I fixed manually by:
         
                  IteratorTemplate(IteratorType *ptr) {
                  	this->ptr = ptr;
                  }
                  
                  
                  

2
                  
                  UnigineVector.h:486:Unexpected token '('
                  
                  486:
                ReverseIteratorTemplate(IteratorType *ptr)
                : ptr(ptr) {}
                
                

 I fixed manually by:

         ReverseIteratorTemplate(IteratorType *ptr) {
             this->ptr = ptr;
         }

These fixes problem manually but javacpp should parse it

**Comment by eix128** [comment]
Also checked
UnigineMathLib.h

UNIGINE_API dvec2
{
	constexpr UNIGINE_INLINE dvec2()
		: x(0.0)
		, y(0.0)
	{
	}

to

	constexpr UNIGINE_INLINE dvec2()
	{
		this.x = 0.0f;
		this.y = 0.0f;
	}

Parsing error on

	UNIGINE_INLINE dvec3()
		: x(0.0)
		, y(0.0)
		, z(0.0)
		, w(0.0)
	{
	}



	constexpr UNIGINE_INLINE dvec4()
		: x(0.0)
		, y(0.0)
		, z(0.0)
		, w(0.0)
	{
	}


	constexpr UNIGINE_INLINE hvec2()
		: x(0)
		, y(0)
	{
	}



	constexpr UNIGINE_INLINE hvec3()
		: x(0)
		, y(0)
		, z(0)
		, w(0)
	{
	}

**Comment by eix128** [comment]
Original UnigineMathLib.h
https://gist.github.com/eix128/11d2fc7e9aad6b9fbe0ec0a4ac32badd
Patched for JavaCPP but may have errors for real usage:
https://gist.github.com/eix128/5b2a7980ff8f6ffba78cb8ea34ece894

**Comment by eix128** [comment]
Again new parser bug:

Exception in thread "main" org.bytedeco.javacpp.tools.ParserException: C:\Users\Administrator\Unigine SDK Browser\sdks\community_windows_2.11.0.2\include\UnigineVector.h:663:Unexpected token '('
    
I had to change line from:
    
    template<typename C, typename A>
    Vector(const Vector<Type, C, A> &o)
            : Vector() {
        append(o);
    }
    
    
    To:
    
    
    template<typename C, typename A>
    Vector(const Vector<Type, C, A> &o) {
        Vector();
        append(o);
    }

**Comment by saudet** [comment]
I get no parsing errors with the following code snippets:
```cpp
class dvec2
{
    double x, y;
    constexpr dvec2()
        : x(0.0)
        , y(0.0)
    {
    }
};

template<typename Type, typename C2, typename A2>
class Vector2
{
    template<typename C, typename A>
    Vector2(const Vector2<Type, C, A> &o)
            : Vector2() {
        append(o);
    }
};
```
So, the issues you're having are somewhere else.
Make sure the macros don't expand into strange attributes.
