### ISSUE TITLE
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacpp#415]
I have update javacv to snapshot version 1.5.4-SNAPSHOT but im getting Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path:  which increase the load time of our app to 20 sec. 
There are many class we init when loading, and many of them have OpenCV converters and FFmpegFrameGrabber. 

We need the snapshot release due to latest fix of OpenCV issue

**Comment by saudet** [comment]
Make sure you have `javacpp-platform` in your dependencies.

**Comment by AKMANSoft** [comment]
Thank you, after adding the platform it resolve the issue. as it make sense all the external dependencies are in platform. 
Also I have spend good amount of time on javacpp check the examples and links, but its hard for a newbie. I think it need more simple material needed for explain the mapping and linking.

**Comment by saudet** [comment]
You mean something like this?
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
