### ISSUE TITLE
warning:no jnijavacpp in java.library.path and error :no jnimodulename in java.library.path

### ISSUE THREAD

**Issue by wpzybyq** [bytedeco/javacpp#418]
inside the parent directory of javacpp-presets,run command mvn clean install --projects .,modulename,i get four jar files:modulename-version.jar（contains generated java class）、modulename-version-linux-x86_64.jar(contains libjnimodulename.so)、modulename-version-sources.jar、modulename-version-javadoc.jar;

when i add modulename-version.jar and modulename-version-linux-x86_64.jar to my java application（paltform window10 ,just test）,get errors like the title

are there some steps i missing or wrong?

**Comment by saudet** [comment]
You'll need to build on Windows to get binaries for Windows.

**Comment by wpzybyq** [comment]
> inside the parent directory of javacpp-presets,run command mvn clean install --projects .,modulename,i get four jar files:modulename-version.jar（contains generated java class）、modulename-version-linux-x86_64.jar(contains libjnimodulename.so)、modulename-version-sources.jar、modulename-version-javadoc.jar;
> 
> when i add modulename-version.jar and modulename-version-linux-x86_64.jar to my java application（paltform window10 ,just test）,get errors like the title



> You'll need to build on Windows to get binaries for Windows.

thanks.i will have a try.

**Comment by wpzybyq** [comment]
> > inside the parent directory of javacpp-presets,run command mvn clean install --projects .,modulename,i get four jar files:modulename-version.jar（contains generated java class）、modulename-version-linux-x86_64.jar(contains libjnimodulename.so)、modulename-version-sources.jar、modulename-version-javadoc.jar;
> > when i add modulename-version.jar and modulename-version-linux-x86_64.jar to my java application（paltform window10 ,just test）,get errors like the title
> 
> > You'll need to build on Windows to get binaries for Windows.
> 
> thanks.i will have a try.

@saudet now i  add modulename-version.jar and modulename-version-linux-x86_64.jar to my java application（paltform centos7 linux-x86_64）,and do some development(call one class in modulename-version.jar),and then run my java application,get error as below:
java.lang.UnsatisfiedLinkError: no jnimodulename in java.library.path
...
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/jnimodulename -2.0.jar/org/bytedeco/modulename/linux-x86_64/libjnimodulename.so: /root/.javacpp/cache/jnimodulename-2.0.jar/org/bytedeco/modulename/linux-x86_64/libjnimodulename.so: undefined symbol: _ZTVN11modulename9debug_log8DebugLogE

how can i solve this error?thanks.

**Comment by saudet** [comment]
You'll to add the library containing that symbol in @Platform(link=...

**Comment by wpzybyq** [comment]
> You'll need to add the library containing that symbol in @platform(link=...

ok thanks!it's useful!

**Comment by wpzybyq** [comment]
> You'll need to add the library containing that symbol in @platform(link=...

@saudet now also has some warnings:
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Warning: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Warning: Could not load BytePointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path

can i ignore these waring infos?

**Comment by saudet** [comment]
Yes, you can ignore those warnings.
