### ISSUE TITLE
skipDefaults

### ISSUE THREAD

**Issue by drieks** [bytedeco/javacpp#420]
Hi,

in class Info, this function should use `this.skipDefaults = skipDefaults`:
```
public Info skipDefaults(boolean skipDefaults) { this.skipDefaults = skip; return this; }
```

**Comment by drieks** [comment]
And linePatterns, enumerate and skipDefaults are missing in copy constructor

**Comment by saudet** [comment]
Thanks! Please open a pull request, if possible.

**Comment by drieks** [comment]
Thank you! Unfortunately I have only little time, so I could not create a PR.
