### ISSUE TITLE
what is the diffrence beetwen javacpp-platform.jar and javacpp.jar

### ISSUE THREAD

**Issue by mengpengfei** [bytedeco/javacpp#421]
what is the diffrence beetwen javacpp-platform.jar and javacpp.jar

**Comment by mengpengfei** [comment]
the document is to hard for me ,
i have a header file and a .so file, i just want to know how to call the function of my so,
i read all the document,but i still do not know what i should do 
can you give a example that how to call the function of the so if i have the header file and the .so file

**Comment by saudet** [comment]
javacpp-platform depends on javacpp + binaries for each platform

**Comment by saudet** [comment]
Here is an example: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#introduction

**Comment by mengpengfei** [comment]
i had read that , can you give me a more detail example

**Comment by saudet** [comment]
That's all the code you need. What details are you looking for?

**Comment by mengpengfei** [comment]
just if i have a header file and a .so file, how to call the function of the so step by step

**Comment by saudet** [comment]
It's exactly like this: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#introduction
1. Create the NativeLibraryConfig.java
2. Execute the `java -jar javacpp.jar` commands
Could you explain more precisely what you do not understand?

**Comment by mengpengfei** [comment]
i had do that,but some errors occurs
do i need to edit the out file of 2 step

**Comment by saudet** [comment]
Yes, you'll need to add information to the InfoMap. It looks like you're trying to parse a header file from OpenCV though, so I would recommend you to use the presets for OpenCV instead.

**Comment by mengpengfei** [comment]
how the "Loader.load();" know where is location of the the so

**Comment by saudet** [comment]
Again, it's all explained here: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#introduction

You'll need to tell what exactly you do not understand.

**Comment by mengpengfei** [comment]
the header include the header of opencv

**Comment by saudet** [comment]
Ok, so your library uses data types from OpenCV? If so, you'll need to do something like other libraries dependent on OpenCV. This one is probably the easiest one you could use as a template for your own library:
https://github.com/bytedeco/javacpp-presets/tree/master/flandmark

**Comment by mengpengfei** [comment]
the demo of javacpp-presets will down the souce code ,and compile it,
but i only have a header file and a .so file
i have imitate the helloworld,i can not use it

**Comment by saudet** [comment]
If you can't use a normal version
of OpenCV, you can copy the presets for OpenCV, and adapt it to your own
version of OpenCV.

**Comment by mengpengfei** [comment]
than you,
i edit the header file and it works

**Comment by mengpengfei** [comment]
the project is great!
