### ISSUE TITLE
Compiling JavaCPP project to DLL under Windows causes Linker errors

### ISSUE THREAD

**Issue by Leyren** [bytedeco/javacpp#423]
We use JavaCPP in a project where some C++ code uses callbacks to an interface whose implementation is provided in Java. We then use CMake to wrap our C++ source files with the generated sources to a library (.dll). This works like a charm on Linux, however I so far was unable to build it on a Windows machine (using Visual Studio 2017 and the integrated MSVC compiler).  

The Linker fails with errors of the kind:
```
LNK2019	unresolved external symbol 
"public: virtual char const * __thiscall LibraryInterface::foo()" (?foo@LibraryInterface@) 
referenced in function 
"public: char const * __thiscall JavaCPP__0003a_0003aLibraryInterface::super_foo()" (?super_foo@JavaCPP__0003a_0003aLibraryInterface@)	
```
for every single callback function the interface has defined.

In Java, the interface is defined as follows (shortened to the relevant aspects):
```java
@Platform(include = {"src/LibraryInterface.h"})
public class CPPBridge {
    public static class LibraryInterface extends Pointer {
        @Virtual public native String foo();
    }
}
```
In `LibraryInterface.h`:
```cpp
class LibraryInterface {
public:
    LibraryInterface() {}
    virtual ~LibraryInterface() {}

    virtual const char* foo() = 0;
};
```
Extract of the generated code:
```cpp
class JavaCPP_hidden JavaCPP__0003a_0003aLibraryInterface : public ::LibraryInterface {
public:
    jobject obj;
    static jmethodID foo__Ljava_lang_String_2;

    JavaCPP__0003a_0003aLibraryInterface() : ::LibraryInterface(), obj(NULL) { }
    using ::LibraryInterface::foo;
    virtual const char* foo();
    const char* super_foo() { return ::LibraryInterface::foo(); }
};
```
Built with:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall" x64
cmake .. -G "Visual Studio 15 2017" -A Win32
cmake --build .
```

Like I said, on Linux it works without any issue. Building it as a static library instead (.lib, with BUILD_SHARED_LIBS=OFF in CMake) works as well.
I also tried using an LLVM Integration for VS2017, yielding the same results.

Any help would be greatly appreciated.

**Comment by saudet** [comment]
This is an issue with CMake? It's recommended to let JavaCPP do the
compiling and linking for the JNI wrapper.

**Comment by saudet** [comment]
If you really need to use CMake, start by making sure all these flags are active when compiling and linking the JNI code:
https://github.com/bytedeco/javacpp/blob/master/src/main/resources/org/bytedeco/javacpp/properties/windows-x86_64.properties#L13
Also make sure it links with psapi.lib.

**Comment by Leyren** [comment]
Thanks for your answer. I tried using solely JavaCPP, with similar results. More specifically, I was using the example for callbacks from the Readme, except that I changed the function `bar` to a pure virtual function (which should work, according to the example):

VirtualFoo.java:
```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include="Foo.h")
public class VirtualFoo {
    static { Loader.load(); }

    public static class Foo extends Pointer {
        static { Loader.load(); }
        public Foo(int n) { allocate(n); }
        private native void allocate(int n);

        @NoOffset public native int n(); public native Foo n(int n);
        @Virtual  public native void bar();
    }

    public static native void callback(Foo foo);

    public static void main(String[] args) {
        Foo foo = new Foo(13);
        Foo foo2 = new Foo(42) {
            public void bar() {
                System.out.println("Callback in Java (n == " + n() + ")");
            }
        };
        foo.bar();
        foo2.bar();
        callback(foo);
        callback(foo2);
    }
}
```
Foo.h:
```cpp
#include <stdio.h>

class Foo {
public:
    int n;
    Foo(int n) : n(n) { }
    virtual ~Foo() { }
    virtual void bar() = 0;
};

void callback(Foo *foo) {
    foo->bar();
}
```
Using `java -jar javacpp.jar VirtualFoo.java`

Resulting in: 
```bash
jniVirtualFoo.obj : error LNK2001: unresolved external symbol ""public: virtual void __cdecl Foo::bar(void)" (?bar@Foo@@UEAAXXZ)".
```
Not using pure virtual functions works, also for the actual project.

**Comment by saudet** [comment]
I see, as shown in the README.md file, you'll need to give it the "-header"
option for that to work.

**Comment by saudet** [comment]
Actually, I think you just forgot to use @Virtual(true)?

**Comment by Leyren** [comment]
That indeed worked, thank you.
