### ISSUE TITLE
Regressions in 1.5.4 for callback functions

### ISSUE THREAD

**Issue by supergrecko** [bytedeco/javacpp#424]
It may be worth noting that there are regressions faults from 1.5.3 in builds which used callback functions which would previously produce basic pointers instead of `PointerPointer`s.

The regression occured in commit https://github.com/bytedeco/javacpp/commit/cc81ce726c5d15071e6f0dce0dad0913df9dee0a

Assuming this was intended behavior, I think it would be useful to mention this somewhere in the changelog.

**Comment by saudet** [comment]
Yes, it's mentioned in the CHANGELOG.md of the commit that you link to above. It's not a regression if it wasn't working before :)

**Comment by supergrecko** [comment]
Oh right, I see. Thanks

**Comment by saudet** [comment]
Is it causing any usability problems for you though?
