### ISSUE TITLE
Constructor fails to initialize properly using std::unique_ptr

### ISSUE THREAD

**Issue by patmantru** [bytedeco/javacpp#426]
I'm trying to wrap a class that has a member that uses std::unique_ptr.  Calling this constructor and then using the resulting object from Java crashes because the member is not being initialized.  This occurs on both osx and ubuntu, I have not tried it elsewhere yet.  Calling this constructor and using the resulting object from C++ works fine.  The implementation is all under the covers in the .cpp file, the header file that javacpp sees only has a standard constructor method.

Internal header:

```
struct Impl {
  // internal implementation stuff
};
```

Public header:
```
 struct Impl;

 class MyThing {
   public:
      MyThing();
 [...]
   private:
      std::unique_ptr<Impl> m_impl;
 }; 
```

Source:

```
 // This constructor fails to initialize m_impl, which later leads to crashes:
 MyThing::MyThing() : m_impl{std::make_unique<Impl>()} {}
```

```
 // This also does not work:
 MyThing::MyThing() {
   m_impl = std::make_unique<Impl>();
 }
```

Why is the constructor failing to initialize m_impl under javacpp?

**Comment by saudet** [comment]
Can you provide a small example to reproduce the crash? I doubt this has anything to do with JavaCPP though.

**Comment by patmantru** [comment]
Working on it...have determined that the constructor is getting called for the two instances I'd expect.  This could be an alignment issue of some sort, now looks like there is a bad 'this' value being provided when a method of MyThing is called.

**Comment by patmantru** [comment]
The 'this' values appear to be off by 8 bytes in some cases.  The constructor builds something at `this=0x7f0ef41b2330 m_impl=0x7f0ef41b24a0` and later when the method is called it sees `this=0x7f0ef41b2328 m_impl=0`

**Comment by saudet** [comment]
That would happen when changing the position to 1, that is to say, the second element in an array.

**Comment by saudet** [comment]
It might also do that if it's actually allocating new objects because you're trying to pass them `@ByVal`, which may not always work as expected with `std::unique_ptr` since it doesn't have a copy constructor.

**Comment by patmantru** [comment]
This is what I'm doing:

Internal header:

```
struct Impl {
  // internal implementation stuff
};

```
Public MyThing header:

```
 class MyThing {
   public:
      MyThing();
 
      void setStuffInMyThing(const int a, const int b, const int c);

      /// Assignment operator
      MyThing& operator=(const MyThing& newValues);

 [...]
   private:
      struct Impl;
      std::unique_ptr<Impl> m_impl;
 }; 

```
Public MainClass header:

```
class MainClass {
  public:
[...]
    void setMyThing(const MyThing& newValues);

  protected:
    MyThing m_myThing;
}

```
Source:

```
   MyThing::MyThing() {
     m_impl = std::make_unique<Impl>();
     dump("default constructor, creating m_impl", __LINE__);
    }


    /// Assignment operator
    MyThing& MyThing::operator=(const MyThing& newValues) {

      dump("assignment operator this before", __LINE__);
      newValues.dump("assignment operator newValues before", __LINE__);

      if (this != &newValues) {
          *m_impl = *policy.m_impl;
      }
      dump("assignment operator this after", __LINE__);
      return *this;
    }

    void MainClass::setMyThing(const MyThing& newValues) {
        m_myThing = newValues;
    }

```

Main program:

```
      MainClass myMainClass = new MainClass(1,2,3);

      MyThing newValues = new MyThing();
    
      newValues.setStuffInMyThing(4,5,6);
      myMainClass.setMyThing(newValues);
```
This is what I get driving it from Java via javacpp:

```
##### default constructor, creating m_impl line=64 this=0x7f0ef41b2330 m_impl=0x7f0ef41b24a0
##### default constructor, creating m_impl line=64 this=0x7f0ef41ad050 m_impl=0x7f0ef41b2a30

##### setStuffInMyThing this before line=154 this=0x7f0ef41ad050 m_impl=0x7f0ef41b2a30
##### setStuffInMyThing this after line=159 this=0x7f0ef41ad050 m_impl=0x7f0ef41b2a30

##### assignment operator this before line=92 this=0x7f0ef41b2328 m_impl=0
##### assignment operator newValues before line=93 this=0x7f0ef41ad050 m_impl=0x7f0ef41b2a30

```
The first constructor call is to create the member of MainClass.  The second is the one to create the newValues instance.  Calling `newValues.setStuffInMyThing` yields correct 'this' pointers, but when the assignment operator is invoked inside of `setMyThing` against the m_myThing member, the 'this' pointer is wrong.  Note that the 'this' pointer is xxx2328 instead of xxx2330.

**Comment by patmantru** [comment]
My first inclination was that the constructor wasn't getting called somehow. Now I don't think that is the case, so the title of this issue and the unique_ptr may be irrelevant info.  I'm now convinced that the constructor is getting called an appropriate number of times successfully.  I think that the 'this' pointer is incorrect when the assignment operator is invoked, and therefore the value of m_impl (relative to that incorrect 'this' pointer) happens to land on zeroed memory.  Is there some byte/word alignment shift going on here?

**Comment by patmantru** [comment]
Verified...I got rid of the unique_ptr entirely.  
```
class Impl {
}

```

```
 class MyThing {    
 [...]
   private:
      Impl m_impl;
 }; 
```

When I call a method on a local variable MyThing object (newValues) the 'this' pointer is correct.  When I go through a method of myMainClass, which in turn calls a method of m_myThing the 'this' pointer for the MyThing object is off by 8.

```
##### default constructor, line=64 this=0x7fb2bba83c20
##### default constructor, line=64 this=0x7fb2bba841c0

##### setStuffInMyThing this before line=159 this=0x7fb2bba841c0
##### setStuffInMyThing this after line=164 this=0x7fb2bba841c0

##### assignment operator this before line=92 this=0x7fb2bba83c18
##### assignment operator newValues before line=93 this=0x7fb2bba841c0
```
Note again the this pointer change: 0x...3c20 vs 0x...3c18

**Comment by saudet** [comment]
Do you have a complete example including wrappers for Java that I can try here?

**Comment by saudet** [comment]
It's possible that something's going wrong when casting from a `void*` back into a `MyThing*`. That sounds like a compiler bug though. Does this happen with all C++ compilers like GCC, Clang, MSVC? You can try it yourself from C++, by casting a `MyThing*` to `void*` and back into `MyThing*` to see if you get the expected value.

**Comment by saudet** [comment]
Any news about this?

**Comment by patmantru** [comment]
I poked at it some more, but was still getting very strange pointer results internally in the c++ code, so this side-project has been shelved for now until I have time to dive into it in more detail.  Closing this pending more information.

**Comment by saudet** [comment]
May I ask which C++ compiler you are using this with?

**Comment by patmantru** [comment]
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
```

**Comment by saudet** [comment]
Hum, ok, that's strange. If you have a complete example that fails please attach it here. I'll take a look
