### ISSUE TITLE
Mention Gradle JavaCPP in Android readme section

### ISSUE THREAD

**Issue by alexeyr** [bytedeco/javacpp#427]
I realize it's mentioned earlier:

> Another option available to Gradle users is Gradle JavaCPP, and similarly for Scala users there is SBT-JavaCPP.

but it may be worth repeating in the "Instructions for Android, Avian, and RoboVM" given most Android projects will be using Gradle.

**Comment by saudet** [comment]
Yes, the README.md file needs to be updated a bit there. It would be great if you could send a pull request! Thanks
