### ISSUE TITLE
can i set a relative dir？

### ISSUE THREAD

**Issue by mengpengfei** [bytedeco/javacpp#434]
hi 
I have 2 questions.
1、the command "java -jar javacpp.jar xxx.java" create a directory that contains a dll file.
but the directory name is "windows-x86",the dll is a dll of x64 platform.

2、when i use javacpp  to call the function of a dll,I must set a absolute path to the linkpath and preloadpath,
can i set a relative path? so  my project can move from one server to another server without  update anything.

wait for you answer.
thanks

**Comment by saudet** [comment]
You can set a relative path, yes, that's fine, but you shouldn't need to set any path for the JNI library created by JavaCPP.

**Comment by saudet** [comment]
As for the architecture that your C++ compiler targets, you'll need to see the documentation of that C++ compiler to understand why it outputs 64-bit DLLs instead of 32-bit DLLs. I cannot help you without more information.

**Comment by mengpengfei** [comment]
thanks you very much ,i will read the document again

**Comment by saudet** [comment]
BTW, if you wish to load DLLs from resources, relative to class files, what you need to set is "linkresource" and "preloadresource".

**Comment by mengpengfei** [comment]
thanks，I have solved the problem
