### ISSUE TITLE
How to iterate through array?

### ISSUE THREAD

**Issue by dukke** [bytedeco/javacpp#439]
Hi,

I'm using liquidfun javacpp.

### Main question is
How do I iterate through an array?

### My specific case
I have created a `b2ParticleGroup`. Now I want to iterate through an array of `b2Vec2` containing the particles positions:
```
b2ParticleSystem particleSystemIter = world.GetParticleSystemList();
if (particleSystemIter != null) {
    b2Vec2 particlePositionBuffer = particleSystemIter.GetPositionBuffer();
    if (particlePositionBuffer != null && particlePositionBuffer.capacity() != 0) {
      //... (some code omitted here)
      for (int particleIndex = 0; particleIndex < particlePositionBuffer.capacity(); ++particleIndex) {
          b2Vec2 worldPos = particlePositionBuffer.position(particleIndex);
```

However `particlePositionBuffer.capacity()` (and `particlePositionBuffer.limit()`) return 0. I thought that was how I could get the size of an array using javacpp?

**Comment by saudet** [comment]
This is a C++ API, not a Java API. JavaCPP doesn't try to guess where to find the size. The answer is in the docs:
> Get the position of each particle Array is length GetParticleCount()

http://bytedeco.org/javacpp-presets/liquidfun/apidocs/org/bytedeco/liquidfun/b2ParticleSystem.html#GetPositionBuffer--

**Comment by dukke** [comment]
OK that works! Thanks  @saudet 
That was potentially a stupid question, I guess I thought since a Pointer could represent an array it would also know its size.

Anyways, thanks a lot for the quick answer! 😃
