### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniLauncher in java.library.path

### ISSUE THREAD

**Issue by 8man** [bytedeco/javacpp#44]
On a clean install of Windows 7 with a newly installed Visual Studio 2013, I get this when trying to allocate a BytePointer:
```
Exception in thread "main" java.lang.RuntimeException: No native JavaCPP library in memory. (Has Loader.load() been called?)
	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:96)
	at ...
Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.BytePointer.allocateArray(I)V
	at org.bytedeco.javacpp.BytePointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:94)
```
If I call Loader.load() then the following happens:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniLauncher in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:550)
	at org.bytedeco.javacpp.Loader.load(Loader.java:415)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at ...
```
Did I miss some crucial step into making this work? I play around with JavaCPP months ago on a machine with Visual Studio 2013 (and thus the C/C++ compilers) and it worked fine.

**Comment by 8man** [comment]
Okay... Now I'm officially confused. First, to clarify, I'm also using the FFmpeg presets. So the following will crash as I've described:
```
    public static void main(String[] args)
    {
        BytePointer ptr = new BytePointer(1); // crashes
    }
```
Yet, for some reason, if I call `av_register_all()` first then it miraculously works:
```
    public static void main(String[] args)
    {
        av_register_all();
        BytePointer ptr = new BytePointer(1); 
        System.out.println(ptr.address()); // works!
    }
```

**Comment by saudet** [comment]
Yes, that calls Loader.load(). Does that solve your issue? Or are you
trying to create your own wrappers for some other functions?

**Comment by 8man** [comment]
No, nothing fancy, I'm just trying to manually allocate a BytePointer as shown in the example. If I call `Loader.load()` directly, I get the `UnsatisfiedLinkError`. If I don't call it first, I get the `RuntimeException` telling me if  that the native JavaCPP library hasn't been loaded into memory.
```
    public static void main(String[] args)
    {
         Loader.load(); // crashes with UnsatisfiedLinkError
         BytePointer ptr = new BytePointer(1); 
    }
```
Wait, if `av_register_all()` also calls `Loader.load()`, then why would it find jnilauncher.dll all of the sudden?

**Comment by saudet** [comment]
It doesn't, it finds the `jniavformat.dll` because it gets called from the `avformat` class.

**Comment by saudet** [comment]
To make a long story short, the base classes (`Pointer`, `IntPointer`, `FloatPointer`, etc) rely on a few native functions. Ideally, a "common" library should be generated for those, but since they are really really small, I just include the same set of functions in all native libraries generated by JavaCPP, and the functions from the first one that gets loaded get picked up. I hope this clarifies things!

**Comment by ceefour** [comment]
I also got this issue with opencv.

Solution:

        // RuntimeException: No native JavaCPP library in memory. (Has Loader.load() been called?) - https://github.com/bytedeco/javacpp/issues/44
        Loader.load(opencv_core.class);
