### ISSUE TITLE
Is there a way to load native libraries explicitly

### ISSUE THREAD

**Issue by Shysoong** [bytedeco/javacpp#440]
`            Mat temp = new Mat(buf);
`
The type of `buf` is a Java byte array.

It took too much time to create the first instance of Mat.
In my case, when i run  this code the first time, it took about 2s, and 20ms at the second time.

I thought the time it takes to load the libraries makes a difference, so how could i load libraries explicitly.

here is the output of `getLoadedLibraries` when i haven't called any Of JavacV's SDK yet
![image](https://user-images.githubusercontent.com/5877530/101315191-0d56b180-3895-11eb-83df-27e9da447c41.png)
here is the output of `getLoadedLibraries` after i  called `Mat(byte... b)` function
![image](https://user-images.githubusercontent.com/5877530/101315404-74746600-3895-11eb-83be-691975e517c6.png)
So if i can load libraries explicitly i can load the libraries on spring boot application startup to save time by not having to load the library when my business code calls.
Could someone help me, thanks a lot.

**Comment by saudet** [comment]
We can call `Loader.load(opencv_java.class)` for that, as written here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by Shysoong** [comment]
> We can call `Loader.load(opencv_java.class)` for that, as written here:
> https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

I thought `Loader.load(opencv_java.class)` only applies to the API in the `org.opencv` namespace.
I have tried `Loader.load(opencv_java.class)`,it worked well in the 'org.bytedeco' namespace too.
Thanks a lot.

**Comment by saudet** [comment]
That's true, but it depends on most of the other modules, so it's also a good way to preload them I suppose :)

**Comment by saudet** [comment]
BTW, we can also load the other modules manually like `Loader.load(opencv_core.class)`, etc.

**Comment by Shysoong** [comment]
One more question,I used javacv to run dnn network, there's a lot of classes involved ,so if i use the `Loader.load(opencv_core.class)` i have to call it many times.
![image](https://user-images.githubusercontent.com/5877530/101330023-19e70400-38ad-11eb-8968-1a4eea907297.png)
And if i use the `Mat(byte... b)` in the package of `org.bytedeco.opencv.opencv_core` ,do i need load the `BytePointer` class explicitly?
 is there any ways to load the entire jar.

**Comment by saudet** [comment]
That's why I said to just load opencv_java

**Comment by Shysoong** [comment]
> That's why I said to just load opencv_java

I got it.I have read the source, and there is a static block,
    ```static {
        Loader.load();
    }```
so just need load the `opencv_imgcodecs.class`, `opencv_imgproc.class`, `opencv_core.class`,`opencv_dnn.class` .

**Comment by saudet** [comment]
Right, opencv_dnn depends on a bunch of other modules, so that might very well load all that you need.
