### ISSUE TITLE
How to return char array to java  byteBuffer from cpp

### ISSUE THREAD

**Issue by user-ZJ** [bytedeco/javacpp#445]
I want to return c++ char array to java,this is mycode

cpp:
```
#include<iostream>
#include<string.h>
#include"TestNative.h"
using namespace std;

char * TestNative::getByteBuffer(char *buffer,int length) {
    for(int i=0;i<length;i++)
        cout<<buffer[i]<<" ";
    char *ch = (char *)malloc(10);
    const char *tmp = "hijkl";  //this may compute from some functions
    memcpy(ch,tmp,5);
    return ch;
}
```

java code:
```
package com.test;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import java.nio.ByteBuffer;

@Properties(value={
        @Platform(
                compiler="cpp11",
                define={"HAVE_CXXABI_H 1","HAVE_ATLAS 1"},
                include={"TestNative.h"},
                includepath={"/root/javacpp-test/cpp/"},
                linkpath={"/root/javacpp-test/cpp/"},
                link={"test"}
        )
})
public class TestNative extends Pointer {
    static { Loader.load(); }
    public TestNative() { allocate(); }
    private native void allocate();


    public static void main(String[] args) {
        int num = 1;
        TestNative l = new TestNative();
        byte[] array = {97, 98, 99, 100, 101};
        ByteBuffer arrayBuffer = ByteBuffer.wrap(array);
        BytePointer mbp= new BytePointer(arrayBuffer);
        BytePointer get_bp = l.getByteBuffer(mbp,arrayBuffer.capacity());
        System.out.println("return buffer length:"+get_bp.asBuffer().capacity());
    }
    public native @Cast("char*")  BytePointer getByteBuffer(@Cast("char*") BytePointer bp,int length);
}
```
when I run the code, get the message:

`return buffer length:1`

I want to know what should I do if I want to return c++ char array to java.
thanks!

**Comment by saudet** [comment]
It's not possible, `char*` doesn't come with any information about the size of the buffer it's pointing to.

**Comment by user-ZJ** [comment]
> It's not possible, `char*` doesn't come with any information about the size of the buffer it's pointing to.

If I want to return char array to java, what should I do?

at common jni use
`(*env)->SetCharArrayRegion(env, result, 0, size, fill);`
to return char array data

At java cpp ,even if change `char *ch = (char *)malloc(10);` to `char *ch = new char[10];` 
I can't return char array to java.

Please give some help. thanks.

**Comment by saudet** [comment]
We can set the capacity of BytePointer, so in your case something like `bp.capacity(length)`. In any case, you'll need to figure out first what exactly you're asking here. It's not clear at all what your question is. Maybe you have a specific end goal? If so, what is it?

**Comment by user-ZJ** [comment]
> We can set the capacity of BytePointer, so in your case something like `bp.capacity(length)`. In any case, you'll need to figure out first what exactly you're asking here. It's not clear at all what your question is. Maybe you have a specific end goal? If so, what is it?

I'm sorry that my statement bothered you.
I re-describe my problem
1. The input and output of the compute(...) function in c++ are streams
2. Use compute_cuda(...) as jni function
3. Pass ByteBuffer and capacity to compute_cuda(...)
4. At compute_cuda(...),Convert buff to stringstream as compute(...) input 
5. get the compute(...) output
6. Write compute(...) output to stringstream as binary
7. convert stringstream to char array (Can't determine the length of each call)
8. return char array
cpp code:
```
char * compute_cuda(signed char * buff,int length){
    std::stringstream iss(std::string(reinterpret_cast<char *>buff,length));
    Matrix<BaseFloat> input;
    input.Read(iss,true);
    Matrix<BaseFloat> output=compute(input);
    stringstream oss;
    output.Write(oss,true);
    const string &tmp = oss.str();
    return tmp.c_str();
}
```
java code:
```
ByteBuffer arrayBuffer = ByteBuffer.wrap(array);
BytePointer mbp= new BytePointer(arrayBuffer);
BytePointer get_bp = l.getByteBuffer(mbp,arrayBuffer.capacity());
```

my question is:
When I convert a char array from the stream (the length is uncertain), how do I return

I don’t know if this description is clear enough,
thanks！

**Comment by saudet** [comment]
Since you're using `std::string` you could return that and map it to Java using `@StdString BytePointer`.
It should even work with `@StdString ByteBuffer`, but I'm not sure if that's ever been tested...

**Comment by user-ZJ** [comment]
> Since you're using `std::string` you could return that and map it to Java using `@StdString BytePointer`.
> It should even work with `@StdString ByteBuffer`, but I'm not sure if that's ever been tested...

Thanks,It work for me.

fixed code is:
```
string compute_cuda(signed char * buff,int length){
    std::stringstream iss(std::string(reinterpret_cast<char *>buff,length));
    Matrix<BaseFloat> input;
    input.Read(iss,true);
    Matrix<BaseFloat> output=compute(input);
    stringstream oss;
    output.Write(oss,true);
    const string tmp = oss.str();
    return tmp;
}
```
```
ByteBuffer arrayBuffer = ByteBuffer.wrap(array);
BytePointer mbp= new BytePointer(arrayBuffer);
BytePointer get_bp = l.getByteBuffer(mbp,arrayBuffer.capacity());
```

native function is:
```
public native @StdString  BytePointer getByteBuffer(@Cast("char*") BytePointer bp,int length);
```
