### ISSUE TITLE
load issues on Android since 1.5.4?

### ISSUE THREAD

**Issue by tmm1** [bytedeco/javacpp#446]
continuing discussion from https://github.com/bytedeco/javacpp/pull/413#issuecomment-752285429

seems to be more than just warnings for me, i'm not getting any javacpp functionality.

```
12-29 18:19:56.555 19941 19941 W System.err: Warning: Could not load Pointer: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/mnt/expand/4bc1480a-802e-4602-9636-c9c878864962/app/app-xnWv8azJJ4Z1P1r3Wq3SZw==/base.apk"],nativeLibraryDirectories=[/mnt/expand/4bc1480a-802e-4602-9636-c9c878864962/app/app-xnWv8azJJ4Z1P1r3Wq3SZw==/lib/arm64, /mnt/expand/4bc1480a-802e-4602-9636-c9c878864962/app/app-xnWv8azJJ4Z1P1r3Wq3SZw==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libjnijavacpp.so"
```

Maybe the `BufferPoolMXBean` is unrelated and the problem is it is trying to look for `libjnijavacpp.so`? Is that file supposed to exist?

When I compile at the moment, I get a single `libjniHDHRLib.so` which includes `jnijavacpp.cpp`:

```
Info: Generating app/src/main/jniLibs/arm64-v8a/jnijavacpp.cpp
Info: Generating app/src/main/jniLibs/arm64-v8a/jniHDHRLib.cpp
Info: Compiling app/src/main/jniLibs/arm64-v8a/libjniHDHRLib.so
Info: ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ -Ivendor/dst/arm64/include -Ivendor/dst/arm/include app/src/main/jniLibs/arm64-v8a/jniHDHRLib.cpp app/src/main/jniLibs/arm64-v8a/jnijavacpp.cpp -O3 -s -ffast-math -Wl,-rpath,lib/ -D__ANDROID_API__=21 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -march=armv8-a -Wall -nostdlib++ -fPIC -shared -Wl,--no-undefined -z text -o libjniHDHRLib.so -Wl,-soname,libjniHDHRLib.so -Lapp/src/main/jniLibs/arm64-v8a -lhdhomerun -llog -lc++_static -lc++abi -ldl -lm -lc
```

**Comment by saudet** [comment]
`libjnijavacpp.so` is just a warning too, you can ignore that one.

**Comment by tmm1** [comment]
Okay, I guess I am not used to all this noise on boot.

**Comment by saudet** [comment]
It's not noise, you might encounter this issue: https://github.com/bytedeco/javacv/issues/1305

**Comment by tmm1** [comment]
So it would be preferable if I built and shipped a `libjnijavacpp.so` alongside the other libraries?

> Maybe we should be using reflection to call `PointerBufferPoolMXBean.register()` here?
> https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L515

Hmm, yea I think reflection might be the solution.

**Comment by saudet** [comment]
> So it would be preferable if I built and shipped a `libjnijavacpp.so` alongside the other libraries?

If you don't need it in your application, no, it's not necessary. But if this is supposed to be a library, that might get used with other libraries, then users will use it with `libjnijavacpp.so` on their own, so you don't need to worry about it either way.

> > Maybe we should be using reflection to call `PointerBufferPoolMXBean.register()` here?
> > https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L515
> 
> Hmm, yea I think reflection might be the solution.

Yes, let's do that.

**Comment by tmm1** [comment]
> If you don't need it in your application, no, it's not necessary.

Thanks. Is there any way to turn off the warnings in my app, perhaps with some sort of system property?

**Comment by saudet** [comment]
We can set "org.bytedeco.javacpp.logger" to "slf4j" and ignore messages
that we get there. It's better to just bundle libjnijavacpp.so though.

**Comment by tmm1** [comment]
I think I'm missing something really simple here.. how do I generate the `libjnijavacpp.so`?

Currently I do the following to get a `javacpp.jar`, then I can use that to [generate and compile the stubs](https://github.com/bytedeco/javacpp/issues/65#issuecomment-305638997) for my custom preset:

```
$ git clone https://github.com/bytedeco/javacpp
$ cd javacpp
$ mvn install

$ java -cp target/javacpp.jar /path/to/libcustom.java
$ java -jar target/javacpp.jar /path/to/libcustom
$ java -cp target/javacpp.jar /path/to/libcustom.java /path/to/CustomLib.java

$ java -jar target/javacpp.jar /path/to/CustomLib -properties android-arm -d /path/to/jniLibs/arm
$ java -jar target/javacpp.jar /path/to/CustomLib -properties android-x86 -d /path/to/jniLibs/x86
```

All of that works just fine. Do I just need to repeat the same steps with `src/main/java/org/bytedeco/javacpp/presets/javacpp.java`?

**Comment by tmm1** [comment]
> Do I just need to repeat the same steps with `src/main/java/org/bytedeco/javacpp/presets/javacpp.java`?

Looks like this is all you need:

```
$ java -jar target/javacpp.jar org/bytedeco/javacpp/presets/javacpp -d .
Info: Generating /javacpp/jnijavacpp.cpp
Info: Compiling /javacpp/org/bytedeco/javacpp/presets/macosx-x86_64/libjnijavacpp.dylib
Info: clang++ -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home/include/darwin /javacpp/jnijavacpp.cpp -march=x86-64 -m64 -O3 -std=c++11 -arch x86_64 -Wl,-rpath,@loader_path/. -Wall -fPIC -pthread -dynamiclib -undefined dynamic_lookup -o libjnijavacpp.dylib
Info: Deleting /javacpp/jnijavacpp.cpp
```

**Comment by saudet** [comment]
That works too I suppose, but it gets generated with the Maven build with `-Djavacpp.platform=android-arm`, etc.
