### ISSUE TITLE
array of devices

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp#45]
hi all,

I am not familiar with using the *** notation in javacpp. I aim to access an array of uvc_device_t defined in C with...

`uvc_error_t uvc_get_device_list (uvc_context_t *ctx, uvc_device_t ***list)`

C and arrays in C are not my strong point but I assume list is holding the pointer to the first device and I am taking a stab at the java call to access the array with

`public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device_t []") Pointer ucvDevList);`

would anyone please be willing to share a brief snippet that shows how to access the device array correctly? thanks

**Comment by saudet** [comment]
Try to run the `Parser` on that and see if it produces something usable.

**Comment by lobsteroh** [comment]
thanks, ok, I am planning to get the parser worker and i am not finding much to help me in that task. can you please point me to a source that describes what the parser is and how to make it work? I see Parser.java in the tools folder. Is the parser the same as creating bytedeco presets described at <https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets>? sorry for being a noob here ...

**Comment by lobsteroh** [comment]
maybe a step further ... here is the updated call that does compile without a hitch.

`public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device***") Pointer uvcDevList);`

when i call this from java, then uvcDevList contains the first valid uvc device :-). but i can't get this in the form of an array of devices. the handling of arrays in C remains a mystery to me when passed between c to java. any insights greatly appreciated...

**Comment by saudet** [comment]
Yes, follow the instructions https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets.

Actually something like `@Cast("uvc_device***") @ByPtrPtr PointerPointer uvcDevList` is probably more usable. Then we should be able to fetch the i'th device with `uvcDevList.get(uvc_device.class, i)`.
