### ISSUE TITLE
Help with porting modsecurity library 

### ISSUE THREAD

**Issue by artemMartynenko** [bytedeco/javacpp#451]
I'm trying to create a new preset for [modsecurity](https://github.com/SpiderLabs/ModSecurity) lib. I`m already done with adding Info for Parser to properly wrap the library and generate Java Pointers without any Java compilation errors. Now I have an issue with generating and compiling C++ jni wrappers based on Java classes, it produces a lot of C++ compilation errors. A lot of errors in incorrect syntax and variables and I cannot recognize a starting point for fixing in the cause of errors are in generated code. It will be greater if you can help me with troubleshooting. Here is [my fork](https://github.com/artemMartynenko/javacpp-presets) with added modsecurity preset. You can run it and see all errors with command  ```mvn clean install --projects .,modsecurity``` as described in wiki.

**Comment by saudet** [comment]
Please read the following and let me know if you have any questions about that or about errors that don't seem to be related to any of it. Thanks!
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by artemMartynenko** [comment]
I went again through that link. Currently, I can`t find the reasons for the errors. I found from previous issues that I miss to define ```{"UNIQUE_PTR_NAMESPACE std", "SHARED_PTR_NAMESPACE std"}```. It fixed some errors but add a new portion. 
It will be greater if you can help me with the identification. Currently, I see few types of errors. 
1. error: cannot apply ‘offsetof’ to member function.
2. cannot convert ‘std::__cxx11::basic_string<char>’ to ‘std::string*’ {aka ‘std::__cxx11::basic_string<char>*’}
3. invalid conversion from ‘signed char*’ to ‘const char*’ [-fpermissive]
4. no match for ‘operator=’ (operand types are ‘std::shared_ptr<std::__cxx11::basic_string<char> >’ and ‘std::__cxx11::basic_string<char>’)
5.  no matching function for call to ‘SharedPtrAdapter<char>::SharedPtrAdapter(std::shared_ptr<std::__cxx11::basic_string<char> >&)’
6. invalid user-defined conversion from ‘SharedPtrAdapter<char>’ to ‘signed char*’ [-fpermissive]
7.  ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]

There are a lot of errors but they are similar, just use another type. 

Can you suggest the reasons and provide some examples of how it can be fixed?

Thanks!

**Comment by saudet** [comment]
Please provide the whole log of errors returned by your C++ compiler, as well as the wrapper classes generated by JavaCPP. Thanks!

**Comment by artemMartynenko** [comment]
Here are log file and generated files. 
[gen.zip](https://github.com/bytedeco/javacpp/files/5856233/gen.zip)
[output.log](https://github.com/bytedeco/javacpp/files/5856235/output.log)

**Comment by saudet** [comment]
There's a lot of classes in there. Start by reducing that to a small number of core classes, and once those work, we can move forward with more classes, and repeat until everything is done.

Since the library has a C API though, I would recommend starting with that API, first. It should be pretty easy to get that one working. And then if you feel that there's something missing from that API, we can start again to look at mapping the C++ API.

**Comment by artemMartynenko** [comment]
Thank you for your advice. I tried to reduce the number of classes and header files leaving only the most needed for library usage. Now I have a compilable version, but to achieve that I skipped some fields and methods and some of them shouldn`t be skipped for future library usage. 
The main error that I have is about usage of ```std::shared_ptr<std::string>``` and ```std::unique_ptr<std::string>```. If fields with those types are not skipped everything ok with parsing process and java classes compilation but jni compilation fails with such errors:
1.  error: no matching function for call to ‘UniquePtrAdapter<char>::UniquePtrAdapter(std::unique_ptr<std::__cxx11::basic_string<char> >)’
2.  invalid cast from type ‘SharedPtrAdapter<char>’ to type ‘std::string*’ {aka ‘std::__cxx11::basic_string<char>*’}
3. no matching function for call to ‘SharedPtrAdapter<char>::SharedPtrAdapter(std::shared_ptr<std::__cxx11::basic_string<char> >&)’
I think it can be easily fixed and I will be very grateful for your help.
Thanks!

**Comment by artemMartynenko** [comment]
And one more question. How can I deploy an artifact to use in the example project and test if everything works fine? 
Thanks!

**Comment by saudet** [comment]
Supporting something like `std::shared_ptr<std::string>` or `std::unique_ptr<std::string>` is pretty tricky because usually both types are mapped with adapters, and JavaCPP doesn't currently support chaining those. The easiest thing to do is probably to create a wrapper class for `std::string` like this one:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/main/java/org/bytedeco/tensorflow/StringArray.java

> And one more question. How can I deploy an artifact to use in the example project and test if everything works fine?
> Thanks!

Just running `mvn install` will deploy everything locally, and you can test everything that way.

**Comment by artemMartynenko** [comment]
Hello. Thank you for your help. With your advice, I have fixed most of the problems and the java wrapper for modsecurity is almost ready. But currently, I faced a build problem. I'm trying to use this preset as dependent lib in the Spring Boot application. Spring Boot builds uber jar and when I`m trying to run this application in docker or on another workspace I got this error. 
```/root/.javacpp/cache/modsecurity-1.5.5-SNAPSHOT-linux-x86_64.jar/org/bytedeco/modsecurity/linux-x86_64/libjniglobal.so: libmodsecurity.so.3: cannot open shared object file: No such file or directory```
What could be the reason?
Thanks!

**Comment by saudet** [comment]
It probably just means the library file isn't there? Are you sure it's in the uber JAR?

**Comment by artemMartynenko** [comment]
It was another fault. The libraries were inside JAR, but the error was irrelevant because dependent libraries for ModSecurity were not installed inside docker. Now everything works fine. Thank you for your help!

**Comment by artemMartynenko** [comment]
Can I create a pull request for javacpp-presets with added ModSecurity?

**Comment by saudet** [comment]
By all means, please do! Thanks

**Comment by artemMartynenko** [comment]
Hello! Sorry for the delay with PR. here is it [#1012](https://github.com/bytedeco/javacpp-presets/pull/1012). I think you can close the issue and we can continue in PR if there will need some changes. Thanks for your help!
