### ISSUE TITLE
DisableExplicitGC

### ISSUE THREAD

**Issue by skirdey** [bytedeco/javacpp#455]
I haven't had a chance to test it, and decided to ask this question here. 

How does javacpp behave when JVM is configured with +DisableExplicitGC - it seems both maxPhysicalBytes and maxBytes system parameters would not have any effect as a call to System.gc() would not do anything. 

Am I right in my evaluation? Can javacpp even be used with +DisableExplicitGC?

**Comment by saudet** [comment]
Sure, as long as all objects are correctly deallocated, for example, with PointerScope:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/
