### ISSUE TITLE
array of devices - reopen

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp#46]
Hi, i appreciate the help immensely, and i am thinking that i actually just got it. Reporting here in one place in case others are looking for similar things

i am trying to use this call in C ...

`uvc_error_t uvc_get_device_list(uvc_context_t *ctx, uvc_device_t ***list) { .... }`

i am wrapping it in java ...

`public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device***") @ByPtrPtr PointerPointer<?> uvcDevList);`

i then try to access a device from the list with the following code ...

    public class Load { 
        public static void main(String... arg) throws InterruptedException {
            UVCDevice dev = new UVCController.UVCDevice();
            UVCContext ctx = new UVCController.UVCContext();
            UVCStreamCtrl sctrl = new UVCController.UVCStreamCtrl();
            System.out.println("Initialize : " + UVCController.uvc_init(ctx, null));

    //      it works if I access the device directly with ...
    //      System.out.println("Find Camera: " + UVCController.uvc_find_device(ctx, dev, 0x0, 0x0, null));
    //      or I first get the list, then pull a device from it with ...

            PointerPointer<UVCDevice> uvcDevList = new PointerPointer<UVCDevice>();
            UVCController.uvc_get_device_list(ctx, uvcDevList);        
            dev = (UVCDevice) uvcDevList.get(UVCDevice.class, 0);

    //      then again free everything at the end. freeing the device list does not work yet
    //      UVCController.uvc_free_device_list(uvcDevList,(byte)1);
            UVCController.uvc_unref_device(dev);
            UVCController.uvc_exit(ctx);
        }
    }

i tried to free the device list by wrapping C call ...

`void uvc_free_device_list(uvc_device_t **list, uint8_t unref_devices)`

with

`public static native void uvc_free_device_list(@Cast("uvc_device**") @ByPtrPtr PointerPointer<?> uvcDevList, @Cast("uint8_t") byte unref_devices);`

but calling the latter reports

`java(30903,0x1005b7000) malloc: *** error for object 0x1005b6800: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug`

in any case though, this is pretty darn magical, thanks for the effort that has gone into javacpp ...

**Comment by saudet** [comment]
uvcDevList should be declared as PointerPointer, no?

**Comment by lobsteroh** [comment]
correct. so i assume my java wrapper is off ...

    public static native void uvc_free_device_list(@Cast("uvc_device**") @ByPtrPtr PointerPointer<?> uvcDevList, @Cast("uint8_t") byte unref_devices);

any suggestion on how i can fix it? whatever i try to change on it, it either won't compile into the jar or give me a compile error when i call it from ...

   UVCController.uvc_free_device_list (uvcDevList, (byte)1);

am at the end of my limited wisdom ...

**Comment by saudet** [comment]
uvc_free_device_list() takes only a double pointer, so we don't need the
@ByPtrPtr annotation. All that would be done automatically with the Parser
BTW.

**Comment by lobsteroh** [comment]
thanks for the help, Samuel. I owe you quite a few drinks by now ... i am reviewing the final outcome of the issue for folks who end up here with similar questions

the calls in C are ...

`uvc_error_t uvc_get_device_list(uvc_context_t *ctx, uvc_device_t ***list) { .... }`

and 

`void uvc_free_device_list(uvc_device_t **list, uint8_t unref_devices) { .... }`

i am wrapping them in java with ...

`public static native int uvc_get_device_list(UVCContext ctx, @Cast("uvc_device***") @ByPtrPtr PointerPointer<?> uvcDevList);`

and 

`public static native void uvc_free_device_list(@Cast("uvc_device**") PointerPointer<?> uvcDevList, @Cast("uint8_t") byte unref_devices);`

i then make the calls work with the following code ...

    public class UVCLoad { 
        public static void main(String... arg) throws InterruptedException {
            UVCDevice dev = new UVCController.UVCDevice();
            UVCContext ctx = new UVCController.UVCContext();
            UVCStreamCtrl sctrl = new UVCController.UVCStreamCtrl();
            System.out.println("Initialize : " + UVCController.uvc_init(ctx, null));

    //      i could access the device directly with ...
    //      System.out.println("Find Camera: " + UVCController.uvc_find_device(ctx, dev, 0x0, 0x0, null));
    //      but here I get the list, then pull a device from it with ...

            PointerPointer<UVCDevice> uvcDevList = new PointerPointer<UVCDevice>();
            UVCController.uvc_get_device_list(ctx, uvcDevList);        
            dev = (UVCDevice) uvcDevList.get(UVCDevice.class, 0);

    //      then again free everything at the end. freeing the device list does not work yet
        UVCController.uvc_free_device_list(uvcDevList,(byte)1);
            UVCController.uvc_unref_device(dev);
            UVCController.uvc_exit(ctx);
        }
    }

**Comment by saudet** [comment]
You're welcome! :)
