### ISSUE TITLE
rows() is deprecated

### ISSUE THREAD

**Issue by acuna-public** [bytedeco/javacpp#463]
Hello, nice library! I'm having a message that `rows()` in `org.bytedeco.javacpp.indexer.Indexer` deprecated. What we should use instead? Thanks.

**Comment by saudet** [comment]
That would be `size(0)`: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/indexer/Indexer.html#rows--

**Comment by acuna-public** [comment]
Okay, but what if there're no any elements in `sizes` array? It will throw an exception. Or I've missed something?

**Comment by saudet** [comment]
We can check rank() beforehand to avoid exceptions.

**Comment by acuna-public** [comment]
Hmmmm, okay, thanks, but it seems strange...

**Comment by saudet** [comment]
What seems strange?

/cc @HGuillemet

**Comment by acuna-public** [comment]
That we need to use it without checkin which deprecated methods have

**Comment by saudet** [comment]
Indexer offers a generic way to access data from multidimensional arrays. It doesn't know anything about "rows" or "columns". We could add support for that, but I'm not sure it's worth it. I'm assuming that your data is in a `Mat`, so you could change your call from `Indexer.rows()` to `Mat.rows()` and that will do what you need it to do and will always behave as intended.

**Comment by acuna-public** [comment]
Sorry for my late aswer) Yes, it's `Mat`. But in any way thanks for explanation and awesome library....
