### ISSUE TITLE
@AsUtf16 annotation is lost for setter methods

### ISSUE THREAD

**Issue by equeim** [bytedeco/javacpp#482]
E.g. if class has field named `foo` with type `std::u16string`, and Config has following Info:
```Java
.put(new Info("std::u16string").valueTypes("String").pointerTypes("String").annotations("@StdU16String", "@AsUtf16"))
```
Then Parser will generate following methods:
```Java
public native @StdU16String @AsUtf16 String foo(); public native Server foo(String setter);
```

Which will result in following setter JNI method:

```C++
JNIEXPORT jobject JNICALL Java_org_equeim_libtremotesf_Server_foo__Ljava_lang_String_2(JNIEnv* env, jobject obj, jstring arg0) {
    libtremotesf::Server* ptr = (libtremotesf::Server*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID));
    if (ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 7), "This pointer address is NULL.");
        return 0;
    }
    jlong position = env->GetLongField(obj, JavaCPP_positionFID);
    ptr += position;
    const char* ptr0 = JavaCPP_getStringBytes(env, arg0);
    jlong size0 = 0;
    void* owner0 = (void*)ptr0;
    BasicStringAdapter< unsigned short, char16_t > adapter0(ptr0, size0, owner0);
    jobject rarg = obj;
    ptr->foo = adapter0;
    JavaCPP_releaseStringBytes(env, arg0, ptr0);
    return rarg;
}
```

`ptr0` has to be of type `const unsigned short*`, but it is `const char*` instead.

**Comment by saudet** [comment]
If I'm not mistaken, that's code that you wrote yourself as part of pull #442, right?
Would it be possible to open another pull request with a patch for this?

**Comment by equeim** [comment]
BTW, why are annotations disabled for setter parameters? 5b70ce94f55b3adeeef06da9f541534bcc667d9f says that it was done to satisfy Generator, but why?

**Comment by saudet** [comment]
Adapters, casts, etc are picked up from the paired getter. We'd need to do something like this for `@AsUtf16` as well:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L3775

**Comment by equeim** [comment]
Fixed with https://github.com/bytedeco/javacpp/commit/656aaecec4c00b436cb572d37f862c4e88a42b23.
