### ISSUE TITLE
Generator still generates try-catch blocks for callbacks when NoException is present

### ISSUE THREAD

**Issue by supergrecko** [bytedeco/javacpp#484]
The Generator class will still produce JNI code with try-catch blocks for callback functions' `_call` function when the `@NoException` annotation is present.

**Reproduction Steps**

1. Create a preset of a library that makes use of callback functions - I've tested with LLVM's C-style function pointers
2. Add the `@NoException` annotation to the InfoMapper preset class
3. Run the JavaCPP generator with the `javacpp.deleteJniFiles` property set to false
4. View the generated JNI code for the callback types

---

Based on mailing list thread: https://groups.google.com/g/javacpp-project/c/zzGRu019BoA

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp/commit/e5495a2a974b16ea68bf590160fc649d61ad0915. Thanks for reporting!

**Comment by supergrecko** [comment]
Great, thank you. I've submitted https://github.com/bytedeco/javacpp-presets/pull/1052 to update the LLVM and Clang presets
