### ISSUE TITLE
Problem with C++ function overloading mapping to the same java type

### ISSUE THREAD

**Issue by egolearner** [bytedeco/javacpp#492]
```
class TestTemplate {
public:
       int test(int *a) {}
       int test(unsigned*a) {}
};
```
JavaCpp will only generate one function
```java
       public native int test(IntPointer a);
       public native int test(IntBuffer a);
       public native int test(int[] a);
```

It does not work by specifying the following
```java
        infoMap.put(new Info("TestTemplate::test(unsigned *)").javaNames("testUnsigned"));
```
or
```java
        infoMap.put(new Info("TestTemplate::test(unsigned*)").javaNames("testUnsigned"));
```

How to help JavaCpp generate both functions? 
Any guide is appreciated.

**Comment by saudet** [comment]
Again that should work. Do you have a complete example that I can try here?

**Comment by egolearner** [comment]
@saudet you can use the code snippet directly which is compilable.
Let me known if there is anything missing.

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp/commit/b4cf59a13697b606efa4deb0f6bd2697abeda6fd. Thanks for reporting!

**Comment by egolearner** [comment]
Problem solved.
Thanks for your help @saudet !
