### ISSUE TITLE
Building JavaCPP library with Maven

### ISSUE THREAD

**Issue by neil-benn** [bytedeco/javacpp#497]
Hello,

  I'm trying to work on a library to access a camera on linux.  I'm trying to get a javacpp test case working.  I've compiled an so with the simple code of:

    #ifndef ARDUGRAB_H_
    #define ARDUGRAB_H_
    #include <iostream>
    
    using namespace std;
    
    namespace ArduGrabLibrary{
  
	class ArduGrab{
	public:
		ArduGrab();
		void initCamera();
		void setSim(bool sim);
		void setDebug(bool debug);
		~ArduGrab();
	private:
		bool debug = false;
		bool sim = false;
	};
    }
    #endif /* ARDUGRAB_H_ */

  The cpp is as follows:

    #include "ardugrab.h"
    
    namespace ArduGrabLibrary
    {
    
	ArduGrab::ArduGrab(){
		std::cout << "IMX298 Constructor" << std::endl;
	}
    
	ArduGrab::~ArduGrab(){
		std::cout << "IMX298 Deconstructor" << std::endl;
	}
    
	void ArduGrab::initCamera(){
		if (this->debug){
			cout << "init camera" << std::endl;
		}
	}
    
	void ArduGrab::setSim(bool sim){
		this->sim = sim;
		if (this->debug){
			cout << "set sim to " << std::boolalpha << this->sim << std::endl;
		}
	}
    
	void ArduGrab::setDebug(bool debug){
		this->debug = debug;
		if (this->debug){
			cout << "set debug to " << std::boolalpha << this->sim << std::endl;
		}
	}
    }
`
  This is then compiled into a an so with : g++ -fPIC -shared -o libardugram.so ardugrab.cpp

The Java code is as follows:

    package com.ziath.ardugrab;
    
    import org.bytedeco.javacpp.Loader;
    import org.bytedeco.javacpp.Pointer;
    import org.bytedeco.javacpp.annotation.Namespace;
    import org.bytedeco.javacpp.annotation.Platform;
    
    @Platform(include = "ardugrab.h")
    @Namespace("ArduGrabLibrary")
    public class ArduGrab extends Pointer {
    
    	static {Loader.load();}
     
    	public ArduGrab() {allocate();}
    	private native void allocate();
     	public native void setSim(boolean sim);
     	public native void setDebug(boolean debug);
    
    	public static void main(String args[]) {
    		ArduGrab ag = new ArduGrab();
    		ag.setDebug(true);
    		ag.close();
    	}
    }

  So I'm then trying to build the JavaCPP library and doing it through maven the POM is as follows:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    	<modelVersion>4.0.0</modelVersion>
    	<groupId>com.ziath</groupId>
    	<artifactId>ardugrabjava</artifactId>
    	<version>0.0.1-SNAPSHOT</version>
    	<dependencies>
    		<dependency>
     			<groupId>org.bytedeco</groupId>
    			<artifactId>javacpp</artifactId>
    			<version>1.5.5</version>
    		</dependency>
    	</dependencies>
    	<build>
    		<plugins>
    			<plugin>
    				<groupId>org.apache.maven.plugins</groupId>
     				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
    					<source>11</source>
    					<target>11</target>
    				</configuration>
    			</plugin>
     			<plugin>
				<groupId>org.bytedeco</groupId>
				<artifactId>javacpp</artifactId>
				<version>1.3</version>
				<configuration>
					<classPath>${project.build.outputDirectory}</classPath>
					<includePath>${project.basedir}/src/main/resources/javacpp</includePath>
					<linkPath>${project.basedir}/src/main/resources/javacpp</linkPath>
				</configuration>
				<executions>
					<execution>
						<id>javacpp.compiler</id>
						<phase>process-classes</phase>
						<goals>
							<goal>build</goal>
						</goals>
						<configuration>
							<classOrPackageName>com.ziath.ardugrab.ArduGrab</classOrPackageName>
							<copyLibs>true</copyLibs>
						  </configuration>
					  </execution>
				  </executions>
			  </plugin>
		  </plugins>
	  </build>
    </project>

  So when I run mvn clean package, this executes just fine.  However when I execute to test this with the following executiion:

    java -cp target/ardugrabjava-0.0.1-SNAPSHOT.jar:javacpp-1.5.5.jar:javacpp-platform.jar:javacpp-linux-arm64.jar com.ziath.ardugrab.ArduGrab

  This then gives me the error of:

    pi@raspberrypi:~/ardugrabjava $ java -cp target/ardugrabjava-0.0.1-SNAPSHOT.jar:javacpp-1.5.5.jar:javacpp-platform.jar:javacpp-linux-arm64.jar com.ziath.ardugrab.ArduGrab
    java: symbol lookup error: /home/pi/.javacpp/cache/ardugrabjava-0.0.1-SNAPSHOT.jar/com/ziath/ardugrab/linux-arm64/libjniArduGrab.so: undefined symbol: _ZN15ArduGrabLibrary8ArduGrabC1Ev`

  I'm not sure what I'm doing wrong; this is the latest incarnation of me trying to get this working for a few days now.  I'm struggling to work out how to build a jar with javacpp.  Any advice on this would be greatly appreciated!

  Thanks.

Regards,

Neil

**Comment by neil-benn** [comment]
After days of experiemntaiotn and then writing the above I found the problem:

    @Platform(link = "ardugrab", include="ardugrab.h")
    @Namespace("ArduGrabLibrary")
    public class ArduGrab extends Pointer {

  All I needed to do was include the header file and the shared library!

  Hope the helps anyone in the same place I was.

Cheers,

Neil

**Comment by saudet** [comment]
Yes, that's documented here: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes
