### ISSUE TITLE
C++ vectors as Java class property

### ISSUE THREAD

**Issue by MohamedRagabAnas** [bytedeco/javacpp#499]
Hey, 

I'm wondering how to map a property of type vector of a c++ class into java.

Consider this c++ class as example:

```cpp
class AdjListGraph{

private:
	std::vector<int> _vec;

public:
	std::vector<int> getVec(){
		return _vec;
	}
	void setVec(std::vector<int> &vec){
		_vec=vec;
	}

};
```

My current approach looks like this:

```java
@platform(include = "AdjListGraph.h")
class AdjListGraph extends Pointer {
    static {
        Loader.load();
    }

    private native void allocate();

    public AdjListGraph() {
        allocate();
    }

    // The goal is to expose the vec method of the AdjListGraph c++ class.
    // By reading examples and documentation, I landed on something like this for accessing this property, but unfortunately doesn't work
    @NoOffset public native @ByVal AdjListGraph vec(VectorInt v);
    public native VectorInt vec (); //getter

    // As a solution, the workaround is with getter and setter, but it's cumbersome
    public native void setVec(VectorInt v);
    public native VectorInt getVec() ;
}

// Vector Class
@name("std::vector<int>")
class VectorInt extends Pointer {
    // ... Loader stuff
    public native void push_back(int x);
}
```

Finally, a demo to show the difference between implementations.

```cpp
class Demo{
    public static void main(String[] args) {
        AdjListGraph l = new AdjListGraph();

        // we want to insert one element in vec.
        l.getVec().push_back(1); // This works
        l.vec().push_back(1); // This doesn't work but we want to use this way
    }
}
```

Thank you.

**Comment by saudet** [comment]
You're probably just missing a `@ByRef` on the getter. Check what the parser gives you with this kind of config:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#defining-wrappers-for-basic-c-containers

**Comment by MohamedRagabAnas** [comment]
Hey, 
I have tried this way I had this log error 

'''
Log using public native Vector.VectorInt _vec():
[INFO] g++ -I/usr/lib/jvm/java-11-openjdk/include -I/usr/lib/jvm/java-11-openjdk/include/linux /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/jniGraph.cpp -L/home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/linux-x86_64 -I/home/jc/ut/project-arr/MQO/src/main/jni -Wl,-rpath,$ORIGIN/ -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/linux-x86_64/libjniGraph.so -lMQOLib 
[INFO] /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/jniGraph.cpp: In function '_jobject* Java_eu_atspace_hash_Graph_00024Vertex_sEquivalentVertexList(JNIEnv*, jobject)':
[INFO] /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/jniGraph.cpp:1500:42: error: no match for call to '(std::vector<int>) ()'
[INFO]  1500 |         rptr = ptr->_vec();
[INFO]       |                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
Log using @ByRef public native Vector.VectorInt sEquivalentVertexList():
[INFO] /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/jniGraph.cpp: In function '_jobject* Java_eu_atspace_hash_Graph_00024Vertex_sEquivalentVertexList(JNIEnv*, jobject)':
[INFO] /home/jc/ut/project-arr/MQO/target/classes/eu/atspace/hash/jniGraph.cpp:1466:43: error: no match for call to '(std::vector<int>) ()'
[INFO]  1466 |         rptr = &ptr->_vec();
[INFO]       |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
'''

**Comment by saudet** [comment]
I don't see where you're defining `_vec()`. If you expect someone to help you, you'll need to provide the actual code that you're trying to get working.

**Comment by 0x7b1** [comment]
Greetings @sauted, let me show you the piece of code we're struggling.

We have a struct definition in C++, `Vertex`.

```cpp
struct Vertex {
    int isClique{};
    std::vector<int> sEquivalentVertexList;
};
```
In particular we want to map the field `sEquivalentVertexList`, since  the field `isClique` works as expected.
The Java class for the `Vertex` struct looks like this:

```java
package eu.atspace.hash;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include = {
        "<vector>",
        "Graph_AdjacenceListsGraph.h"}, link = "MQOLib")
public class Graph {
    @Name("Vertex")
    public static class Vertex extends Pointer {
        static {
            Loader.load();
        }

        private native void allocate();

        public Vertex() {
            allocate();
        }

        private native void allocate(int id, int label);

        public Vertex(int id, int label) {
            allocate(id, label);
        }

        // isClique field works
        @NoOffset
        public native int isClique();
        public native Vertex isClique(int isClique);

        // sEquivalentVertexList yields a pointer error:
        // [INFO] error: no match for call to '(std::vector<int>) ()'
        // [INFO]  1466 |         rptr = &ptr->sEquivalentVertexList();
        @NoOffset @ByRef public native Vector.VectorInt sEquivalentVertexList();
    }
}

```

This is the way how are we testing it.

```java
package eu.atspace.hash;

public static void main(String[] args) {
    Graph.Vertex v = new Graph.Vertex();
    v.isClique(69);

    v.sEquivalentVertexList.push_back(1); // This throws error
}
```

I hope now it's more clear

**Comment by saudet** [comment]
Ok, thanks! Since you're not providing a setter for that variable, we need to annotate the getter with `@MemberGetter`.

**Comment by 0x7b1** [comment]
Great! That's exactly what was missing.
Thank you
