### ISSUE TITLE
Problem with non-array based FloatBuffer

### ISSUE THREAD

**Issue by egolearner** [bytedeco/javacpp#502]
Cpp Function taking float array(i.e. `assign(float*, size_t)`) will auto generate a convenient function taking FloatBuffer.
```java
  public native void assign(@Const FloatBuffer vec, @Cast("size_t") long len);
```
However, the JNI implementation will call `array` directly without checking if the FloatBuffer is array based, leading to core dump. 
```cpp
JNIEXPORT void JNICALL Java_com_mycompany_myproject2_core_FloatNumericalVector_assign__Ljava_nio_FloatBuffer_2J(JNIEnv* env, jobject obj, jobject arg0, jlong arg1) {
    ailego::NumericalVector<float>* ptr = (ailego::NumericalVector<float>*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID));
    if (ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 7), "This pointer address is NULL.");
        return;
    }
    jlong position = env->GetLongField(obj, JavaCPP_positionFID);
    ptr += position;
    float* ptr0 = arg0 == NULL ? NULL : (float*)env->GetDirectBufferAddress(arg0);
    jfloatArray arr0 = NULL;
    jlong offset0 = 0;
    if (arg0 != NULL && ptr0 == NULL) {
        arr0 = (jfloatArray)env->CallObjectMethod(arg0, JavaCPP_arrayMID);
        offset0 = env->CallIntMethod(arg0, JavaCPP_arrayOffsetMID);
        if (env->ExceptionOccurred() != NULL) {
            env->ExceptionClear();
        } else {
            ptr0 = arr0 == NULL ? NULL : env->GetFloatArrayElements(arr0, NULL) + offset0;
        }
    }
    jlong position0 = arg0 == NULL ? 0 : env->GetIntField(arg0, JavaCPP_bufferPositionFID);
    ptr0 += position0;
    ptr->assign((const float*)ptr0, (size_t)arg1);
    if (arr0 != NULL) env->ReleaseFloatArrayElements(arr0, (jfloat*)(ptr0 - position0), JNI_ABORT);
}
```

One option is to add exception checking after calling `array()`.  Maybe people should use `ByteBuffer.allocateDirect()` to allocate buffer for JNI. But when they fail to do that, Exception is better than core dump.
Another option is to create `std::vector` and call `FloatBuffer.get` in a loop. I'm not sure it's feasible or not or if the overhead is acceptable.

The same problems exist for other type of Buffer.

**Comment by saudet** [comment]
If both the address and the array are null, then null gets passed to the function. If that leads to a crash, then that's a problem with the library you're calling, no?

> One option is to add exception checking after calling `array()`.

It's doing that, see in the code that you quoted above. ExceptionOccurred() gets called after array(). Is this failing on your version of the JVM for some reason?

**Comment by egolearner** [comment]
It seems to me that the function should return after ExceptionOccurred() is not NULL.
```cpp
if (env->ExceptionOccurred() != NULL) {
            return
}
```

**Comment by egolearner** [comment]
The problem is not with the library.
> If both the address and the array are null, then null gets passed to the function. If that leads to a crash, then that's a problem with the library you're calling, no?



```cpp
#include <cstdio>
class Float {
public:
    void assign(float *arr, size_t size) {
            fprintf(stderr, "%p\n", arr);
            fprintf(stderr, "%zu\n", size);
        for (size_t i = 0; i < size; i++) {
            fprintf(stderr, "%f\n", arr[i]);
        }
    }
};
```

```java
    public static void main(String[] args) {
        Float f = new Float();
        FloatBuffer fb = ByteBuffer.allocate(32).asFloatBuffer();
        float[] arr = new float[]{1.0F};
        f.assign(FloatBuffer.wrap(arr), 1);
        f.assign(fb, fb.remaining());
    }
```
Native code will get null pointer for the second `assign`.

```
0x7fb46b90f2f0
1
1.000000
0x0
8
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010e700164, pid=31129, tid=0x0000000000000c03
```

**Comment by saudet** [comment]
Hum, ok, it doesn't return the underlying `byte[]` array? How can we do that?

**Comment by saudet** [comment]
It looks like the underlying ByteBuffer in that case is available from a field named `bb`:
https://stackoverflow.com/questions/27492161/convert-floatbuffer-to-bytebuffer
That might be one way to work around that, but it feels like it would be quite the kludge...

**Comment by saudet** [comment]
In the meantime, we can of course rethrow the exception. Please open a pull request with the required changes! Thanks

**Comment by egolearner** [comment]
> In the meantime, we can of course rethrow the exception. Please open a pull request with the required changes! Thanks

Done.
