### ISSUE TITLE
mapping Tuple of Vectors 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [bytedeco/javacpp#505]
Greetings @saudet 

I have a function in c++ that returns a tuple of vectors, here is the class/type tat the function should return at the end of the day

```java
    @Name("std::tuple<std::vector<AdjacenceListsGRAPH>, std::vector<PCM_Node>>")
    public static class TupleGeneratedandPCM extends Pointer {

        static {
            Loader.load();
        }

        public TupleGeneratedandPCM() {
            allocate();
        }
        public native void allocate();
    }
```

Actually, I couldn't find an example with the mapping of tuple functions such as ```size``` and ```get``` and others, like the one you provide for vectors and sets.

Could you please refer me to an online example of what native functions to use with a tuple that I might overlooked? 

Thanks in advance for your great help and support.

**Comment by saudet** [comment]
There's a few in the presets for PyTorch here:
https://github.com/bytedeco/javacpp-presets/blob/master/pytorch/src/main/java/org/bytedeco/pytorch/presets/torch.java#L605
Let me know if it doesn't work for you though! Thanks
