### ISSUE TITLE
compile failures when use Eigen::Matrix

### ISSUE THREAD

**Issue by RTX2080** [bytedeco/javacpp#515]
I write a easy example about Eigen::Martrix
```c++
#include<string>
#include<vector>
#include<Eigen/Dense>
using namespace std;
using namespace Eigen;
double a[]={3,3,2};
Martix<double,1,3> mt; // = Map<Martix<double,1,3> >(a);
```
then I write a Config.java 
```java
import org.bytedeco.javacpp.annotation.*;
import org.bytedeco.javacpp.tools.*;
@Properties(
        value = @Platform(
                includepath = {"/usr/local/Cellar/eigen/3.4.0/include/eigen3"},
                include = {"test.cpp"},
                compiler = {"cpp17"}
        ),
        target = "Main"
)
public class config implements InfoMapper {
    public void map(InfoMap infoMap) {

    }
}
```
and execute 
`java -jar javacpp.jar config.java`
`java -jar javacpp.jar Main.java `
but get these errors
`Main.java:18: 错误: 非法的类型开始
public static native @ByRef Martix<double,1,3> mt(); public static native void mt(Martix<double,1,3> setter); // = Map<Martix<double,1,3> >(a);`

how should I write my config.java,please ？

**Comment by saudet** [comment]
Eigen is a template library, you'll need to create instances of those classes, like this:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#creating-instances-of-c-templates
However, this example with Thrust that doesn't parse header files is probably closer to what you want to do:
https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA
