### ISSUE TITLE
Pointer's nio Buffer initializer doesn't work as expected

### ISSUE THREAD

**Issue by oneengineer** [bytedeco/javacpp#526]
I want to initialize a pointer with data store in a ByteBuffer. However the pointer seems to be created as size of 1 byte.
Here is what I did:
```
      val nioBuffer = ByteBuffer.wrap(data.get)
      val hostData = new Pointer( nioBuffer )  
```

I look up the initializer of the Pointer, it seems the code never goes to `!isNull()`  because the address is initialized as 0.
So that address/position/capacity won't be set as the buffers'.

```
    public Pointer(final Buffer b) {
        if (b != null) {
            allocate(b);
        }
        if (!isNull()) {
            address -= b.position() * sizeof();
            position = b.position();
            limit = b.limit();
            capacity = b.capacity();
            deallocator = new ProxyDeallocator(this, b);
        }
    }
```

**Comment by oneengineer** [comment]
I just checked `BytePointer` works well, not sure the purpose of Pointer's Buffer constructor.

**Comment by saudet** [comment]
If you would like to make it clearer though, please open a pull request with your suggestions. Thanks!

**Comment by oneengineer** [comment]
My bad, I don't what direct refer at the first place. The docs are very clear. Thanks!
