### ISSUE TITLE
how to deal with typedef rename array?

### ISSUE THREAD

**Issue by RTX2080** [bytedeco/javacpp#529]
I use ``typedef double Matrix[3][3]; `` in my code
then I add ``infoMap.put(new Info("std::double [3][3]").pointerTypes("Matrix").define());`` but not work
which code should I add in my infomap,please?

**Comment by saudet** [comment]
We can treat those as pointers to arrays and do something like `rpp_mat` from ARToolKitPlus:
https://github.com/bytedeco/javacpp-presets/blob/master/artoolkitplus/src/main/java/org/bytedeco/artoolkitplus/presets/ARToolKitPlus.java#L61

**Comment by RTX2080** [comment]
Thanks for your valuable reply!
