### ISSUE TITLE
javacpp 1.5.6(7) doubling memory usage

### ISSUE THREAD

**Issue by saduf** [bytedeco/javacpp#555]
Hello, thank you for the great library.
 
I’m  seeing 1.5 - 2 times more memory use (from ~50GB to ~80GB average) with Tesseract 5 + openCV 4.5.5, this is related to a change introduced in javaCPP 1.5.6 to address this issue: [#468](https://github.com/bytedeco/javacpp/issues/468#issuecomment-833161072), currently we are using javaCPP 1.5.5.
 
From the changes introduced: maxPhysicalBytes {the maximum amount of physical memory that should be used}, is increased by a factor of 4, from the previously used 2. 
 
To confirm this I built javaCPP from source reverting back that change to the original value and our measurements  went back to what we used to get before, ~50GB memory use average, please see graphs.
 
Putting some numbers on it: 
m = maxBytes > 0 ? maxBytes + maxMemory : 0;
maxPhysicalBytes = m; 
 
Where: 
maxBytes = Runtime.getRuntime().maxMemory(); 
maxMemory = Runtime.getRuntime().maxMemory(); (From code conditional flow)
Runtime.getRuntime().maxMemory() = Total designated memory, this will equal the configured -Xmx value, as described [here](https://stackoverflow.com/questions/3571203/what-are-runtime-getruntime-totalmemory-and-freememory).

| Previous change:  | After change: |
| ----------- | ----------- |
| m = maxBytes > 0 ? maxBytes + maxMemory : 0; <br />  maxBytes = 6GB (Xmx value) <br /> maxMemory = 6GB <br /> m = 6 > 0 ? 6 + 6 : 0; = 12 (Per pipe) <br /> 5P ~ 60 GB (Matches measurements) <br /> ![javaCPP1 5 7Mr](https://user-images.githubusercontent.com/36648406/154527505-8e7e8249-404c-4314-a7f5-1d784e36aa03.png) | m = maxBytes > 0 ? maxBytes + 3 * maxMemory : 0; <br /> maxBytes = 6GB (Xmx value) <br /> maxMemory = 6GB <br /> m = 6 > 0 ? 6 + 3 * 6 : 0; = 24 (Per pipe) <br /> 5P ~ 120 GB (Close in the metrics) <br /> ![javaCPP1 5 7Rr](https://user-images.githubusercontent.com/36648406/154527527-d98860ae-903a-4894-913a-0a7cddcf3daf.png)| 

I think this change is too rigid and takes the control of the application resources utilization out of your hands, for some cases  this might be a good fit, however for other applications, this change forces us to use from 1.5 - 2 times more memory, when not needed.
 
In my opinion/suggestion, a way to handle this without forcing everyone to use more memory, and adding more granularity, would be to provide a knob to control the amount of physical memory required, i.e:

```angular2html
factor = System.getProperty("org.bytedeco.javacpp.maxphysicalbytesfactor");
factor = factor != null && factor.length() > 0 ? factor : 3;
m = maxBytes > 0 ? maxBytes + factor * maxMemory : 0;
```
Thanks again for your time, I hope this helps.

- Fernando
.

**Comment by saudet** [comment]
That's already there. To get the previous default, you can set "org.bytedeco.javacpp.maxphysicalbytes" to "200%":
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxPhysicalBytes

But if you care about memory usage, you should really be using PointerScope anyway:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/
