### ISSUE TITLE
Difference between javadoc and code wrt org.bytedeco.javacpp.maxphysicalbytes

### ISSUE THREAD

**Issue by mrForce** [bytedeco/javacpp#559]
Hi,

I had the "Physical memory usage is too high: physicalBytes = 2G > maxPhysicalBytes = 1G" error, so, per [this documentation](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html), I set the "org.bytedeco.javacpp.maxPhysicalBytes" system property in the java command line arguments. It didn't work, so I looked in the code of Pointer.java (https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java). It appears to reference "org.bytedeco.javacpp.maxphysicalbytes", not "org.bytedeco.javacpp.maxPhysicalBytes". Shouldn't this be reflected in the documentation?

**Comment by saudet** [comment]
Please upgrade to JavaCPP 1.5.7.

**Comment by devjeonghwan** [comment]
It's not my code, but it seems to be an exception code for the lowercase property. Finally, it is overwritten with `org.bytedeco.javacpp.maxPhysicalBytes`.

```java
m = maxBytes > 0 ? maxBytes + 3 * maxMemory : 0;

// Getting value from `org.bytedeco.javacpp.maxphysicalbytes`. if not exists null
s = System.getProperty("org.bytedeco.javacpp.maxphysicalbytes");

// Getting value from `org.bytedeco.javacpp.maxPhysicalBytes`. if not exists old value(variable s)
s = System.getProperty("org.bytedeco.javacpp.maxPhysicalBytes", s);
```

So, if you set `maxPhysicalBytes` value. use that value regardless of  `maxphysicalbytes` exists.
