### ISSUE TITLE
@opaque

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp#56]
i am halfway through creating presets for another module and so far things are going well but i am running into a tag and i was hoping someone could clear it up for me what the @opaque tag means on the java end and how to replace it with a full featured object definition ...

So I have a struct in the libuvc.h file

    /** UVC streaming interface.
    */
    struct uvc_streaming_interface;
    typedef struct uvc_streaming_interface uvc_streaming_interface_t;

which is defined in libuvc_internal.h

    /** VideoStream interface */
    typedef struct uvc_streaming_interface {
       struct uvc_device_info *parent;
       struct uvc_streaming_interface *prev, *next;
       uint8_t bInterfaceNumber;
       struct uvc_format_desc *format_descs;
       uint8_t bEndpointAddress;
       uint8_t bTerminalLink;
    } uvc_streaming_interface_t;

in my java wrapper this struct maps onto

    @Opaque
    @Name("uvc_streaming_interface")
    public static class UVCStreamingInterface extends Pointer {
        public UVCStreamingInterface() { }
        public UVCStreamingInterface(Pointer p) { super(p); }
    }

this works just fine to get the object, but i cannot access the individual items in the struct. Another similar java definition lacks the @opaque tag and is defined as:

    @Name("timeval")
    public static class TimeVal extends Pointer {
        static { Loader.load(); }
        public TimeVal() { allocate(); }
        public TimeVal(int size) { allocateArray(size); }
        public TimeVal(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(int size);
        public native long tv_sec(); public native TimeVal tv_sec (long tv_sec);
        public native long tv_usec(); public native TimeVal tv_usec(long tv_usec);
    }

on the second I can get my grubby hands on all the individual fields of the struct and I am thinking that the way to solve my pickle is by switching the uvc_streaming-interface from @opaque to the full declaration. unfortunately, i can't find any explanation of the tag and no suggestions on how to change it. my random trial and error attempts have not yielded anything that works. any suggestion greatly appreciated.

when i try to model the definition after another non opaque struct, i get a bunch of errors during mvn compile of the java wrapper like ...

    /usr/local/include/libuvc/libuvc.h:156:10: note: forward declaration of 'uvc_streaming_interface'
       struct uvc_streaming_interface *parent;

**Comment by saudet** [comment]
Just make sure libuvc_internal.h is in the include list of the @Platform
annotation and it should fix that.

**Comment by saudet** [comment]
Discussion moved to #57
