### ISSUE TITLE
FloatBufferIndexer recomputes index(...) for every element in get(...)

### ISSUE THREAD

**Issue by jxtps** [bytedeco/javacpp#560]
Looking at https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/indexer/FloatBufferIndexer.java#L71 the code right now reads: 
```java
    @Override public FloatIndexer get(long i, float[] f, int offset, int length) {
        for (int n = 0; n < length; n++) {
            f[offset + n] = buffer.get((int)index(i) + n);
        }
        return this;
    }
```
But `index(i)` does a fair bit of work. That may get JIT-inlined-etc (and I have yet to actually measure it), but it seems like something along the lines of: 
```java
    @Override public FloatIndexer get(long i, float[] f, int offset, int length) {
        final int idx = (int)index(i); 
        for (int n = 0; n < length; n++) {
            f[offset + n] = buffer.get(idx + n);
        }
        return this;
    }
```
would structurally ensure any overhead is minimized? 

That change also invites factoring out a private helper method: 
```java
    private FloatIndexer getInner(int idx, float[] f, int offset, int length) {
        for (int n = 0; n < length; n++) {
            f[offset + n] = buffer.get(idx + n);
        }
        return this;
    }
```
that can then be called by the family of `get(...)` functions that all have the same structure except for the specific signature used for `index(...)`: 
```java
    @Override public FloatIndexer get(long i, float[] f, int offset, int length) {
        return getInner((int)index(i), float[], offset, length); 
    }
```
Ditto for the `put(...)` methods. 

Thoughts?

**Comment by saudet** [comment]
The compiler does all that by itself, but if you notice any difference in performance, let me know.

**Comment by jxtps** [comment]
Interesting, ran a micro-benchmark and the compiler does indeed optimize it out, which is funny because I have had mixed experiences with varargs in java - another microbenchmark showed that they're cheap but not free.

**Comment by jxtps** [comment]
`tensor.data_ptr_float().get(floatArray);` is >2x faster though. Here's the microbenchmark: 
```java
package misc;

import org.bytedeco.javacpp.indexer.FloatBufferIndexer;
import org.bytedeco.pytorch.AbstractTensor;
import org.bytedeco.pytorch.Tensor;
import java.nio.FloatBuffer;

public class PerfTestFloatBufferIndexer {
    final static private int N = 1000 * 1000;
    final static private float[] f0 = new float[N];
    final static private float[] f1 = new float[N];
    final static private long[] shape = new long[]{N};
    final static private long[] strides = new long[]{1};
    final static private Tensor tensor = AbstractTensor.create(f0, shape);
    final static private FloatBuffer buffer = tensor.createBuffer();
    final static private FloatBufferIndexer fbi = new FloatBufferIndexer(buffer, shape, strides);

    static public void get(long i, float[] f, int offset, int length) {
        int idx = (int) fbi.index(i);
        for (int n = 0; n < length; n++) {
            f[offset + n] = buffer.get(idx + n);
        }
    }

    public static void main(String[] args) {
        long t0;
        for (int iter = 0; iter < 10; iter++) {
            System.out.println("---------  " + iter + "  -----------");

            t0 = System.nanoTime();
            fbi.get(0, f1, 0, f1.length);
            System.out.println(String.format("fbi.get(0, f1): %,9d nanos", System.nanoTime() - t0));

            t0 = System.nanoTime();
            get(0, f1, 0, f1.length);
            System.out.println(String.format("idx get(0, f1): %,9d nanos", System.nanoTime() - t0));

            t0 = System.nanoTime();
            tensor.data_ptr_float().get(f1, 0, f1.length);
            System.out.println(String.format("data_ptr_float: %,9d nanos", System.nanoTime() - t0));
        }
    }
}
```
This prints: 

> ---------  0  -----------
fbi.get(0, f1): 7,136,200 nanos
idx get(0, f1): 5,188,400 nanos
data_ptr_float:   374,900 nanos
---------  1  -----------
fbi.get(0, f1): 5,776,000 nanos
idx get(0, f1): 3,351,800 nanos
data_ptr_float:   161,900 nanos
---------  2  -----------
fbi.get(0, f1):   410,500 nanos
idx get(0, f1):   450,900 nanos
data_ptr_float:   159,100 nanos
---------  3  -----------
fbi.get(0, f1):   413,600 nanos
idx get(0, f1):   449,100 nanos
data_ptr_float:   173,800 nanos
---------  4  -----------
fbi.get(0, f1):   410,500 nanos
idx get(0, f1):   416,900 nanos
data_ptr_float:   159,200 nanos
---------  5  -----------
fbi.get(0, f1):   412,900 nanos
idx get(0, f1):   409,000 nanos
data_ptr_float:   159,800 nanos
---------  6  -----------
fbi.get(0, f1):   414,600 nanos
idx get(0, f1):   406,000 nanos
data_ptr_float:   159,300 nanos
---------  7  -----------
fbi.get(0, f1):   410,300 nanos
idx get(0, f1):   405,100 nanos
data_ptr_float:   159,600 nanos
---------  8  -----------
fbi.get(0, f1):   419,800 nanos
idx get(0, f1):   406,600 nanos
data_ptr_float:   162,100 nanos
---------  9  -----------
fbi.get(0, f1):   409,700 nanos
idx get(0, f1):   403,200 nanos
data_ptr_float:   158,200 nanos

**Comment by saudet** [comment]
Yeah, that's expected. The JDK's compiler isn't getting updated as much as native ones like GCC...

**Comment by jxtps** [comment]
That sounds plausible/reasonable. Added `System.arraycopy` for completeness/reference: 
```
---------  9  -----------
fbi.get(0, f1):   400,100 nanos
idx get(0, f1):   403,800 nanos
data_ptr_float:   161,500 nanos
System.arraycopy: 208,100 nanos
```
