### ISSUE TITLE
Java arg reading issue

### ISSUE THREAD

**Issue by gneusch** [bytedeco/javacpp#564]
Hi javacpp Team,

Thanks for the great work guys! I assume however that there is bug with the below line, when the -D cmd argument is handled. I assume ++i should be passed to the property function?

https://github.com/bytedeco/javacpp/blob/e8aacb2057a3ac0d4d4f319059d878149c983508/src/main/java/org/bytedeco/javacpp/tools/Builder.java#L1398

If I'm wrong, could you please help me out how to use this flag? 
Thanks a lot,
Lóri

**Comment by saudet** [comment]
You're right, it won't work when the "key=value" pair is found in the next argument.
I've fixed that in commit https://github.com/bytedeco/javacpp/commit/b96fcbfeb7be9523f8580561dedce88ceaae9958. Thanks for reporting!
