### ISSUE TITLE
access fields in a struct

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp#57]
This is a slightly different issue than the one i submitted earlier today. so, as i am trying to access the fields of C struct for use in my java wrapper, I decided to pick an easier object and start with that ... the original gets the device but i can't access the fields of the struct. so I changed the c and java code in the hope to make this access work. I again get a functional object, but several lines are not compiling in mvn

ORIGINAL VERSION ...............

defined in libuvc.h

    struct uvc_device;
    typedef struct uvc_device uvc_device_t;

defined in libuvc_internal.h

    struct uvc_device {
      struct uvc_context *ctx;
      int ref;
      libusb_device *usb_dev;
    };

and in the java wrapper

    @Opaque
    @Name("uvc_device")
    public static class UVCDevice extends Pointer {
        public UVCDevice() { }
        public UVCDevice(Pointer p) { super(p);  }
    }

MODIFIED VERSION ...............

defined in libuvc.h

    struct uvc_device;
    typedef struct uvc_device {
      struct uvc_device *prev, *next;
      struct uvc_context *ctx;
      uint32_t ref;
      struct libusb_device *usb_dev;
    } uvc_device_t;

and in the java wrapper

    @Name("uvc_device")
    public static class UVCDevice extends Pointer {
        static { Loader.load(); }
        public UVCDevice() { allocate(); }
        public UVCDevice(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(int size);
    // public native @Cast("uvc_context") int ctx(); public native UVCDevice ctx(int ctx);        
        public native @Cast("uint32_t") int ref(); public native UVCDevice ref(int ref);
    // public native @Cast("libusb_device") int usb_dev(); public native UVCDevice usb_dev(int usb_dev);
    }

this version gives me a functional uvc device ... yeaaah ... but mvn fails to compile the lines commented out. i think i have tried just about every possible version but i cannot come up with access to the uvc_context and libusb_device structs. looks like i am getting pretty close. if someone could flag what i am doing wrong with these two lines, then i'd be very grateful. be well all, and happy new year.

**Comment by saudet** [comment]
Including the original libuvc_internal.h file didn't work?

**Comment by lobsteroh** [comment]
turns out ... this does not solve much in my hands. when i include ibuvc_internal.h with @Platform, it then wants additional header files referenced there and that requires a bunch of manual copying of files around, not a good thing. and most importantly it just gets me to the next set of compile errors at mvn.

same code as above except i am now trying to include the line for uvc_context.

    @Name("uvc_device")
    public static class UVCDevice extends Pointer {
        static { Loader.load(); }
        public UVCDevice() { allocate(); }
        public UVCDevice(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(int size);
        public native @Cast("uvc_context*") int ctx(); public native UVCDevice ctx(int ctx);        
        public native @Cast("size_t") int ref(); public native UVCDevice ref(int ref);
 //       public native @Cast("libusb_device") int usb_dev(); public native UVCDevice usb_dev(int usb_dev);        
   }

gives ...

    /Users/lobsterman/Documents/workspace/jLibuvc-master_RH/target/classes/cl/cc/jlibuvc/jniUVCController.cpp:3414:12: error: cast from pointer to smaller type 'jint' (aka 'int') loses information
    rarg = (jint)rvalue;

    /Users/lobsterman/Documents/workspace/jLibuvc-master_RH/target/classes/cl/cc/jlibuvc/jniUVCController.cpp:3426:16: warning: cast to 'uvc_context *' from smaller integer type 'jint' (aka 'int') [-Wint-to-pointer-cast]
    ptr->ctx = (uvc_context*)arg0;

it just confirms that i fundamentally don't understand how to do this in javacpp. this looks like a powerful technology but i am not finding enough info to understand how this ought to be done correctly. would like to be of use here, but am not at the stage of understanding where I have anything worth sharing.

**Comment by saudet** [comment]
I think the closest example to libuvc is libdc1394. So you could try to base your code on that:
https://github.com/bytedeco/javacpp-presets/tree/master/libdc1394
Yes, we need to include most header files. That's how it works.
