### ISSUE TITLE
Missing method getListColorChecker() in the CCheckerDetector Java class

### ISSUE THREAD

**Issue by JeeDevUser** [bytedeco/javacpp#571]
### Discussed in https://github.com/bytedeco/javacpp/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **JeeDevUser** May  9, 2022</sup>
Hi,

Just tried a fresh snapshot, the method 
**getListColorChecker()**
https://docs.opencv.org/4.x/d9/d53/classcv_1_1mcc_1_1CCheckerDetector.html#a035f9ea8c21a9e7d160b622ca94c71f2

seems to be missing from the CCheckerDetector Java class:

http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_mcc/CCheckerDetector.html

Can anyone check that?

</div>

**Comment by JeeDevUser** [comment]
> Thanks for reporting, but please open issues about the presets over there and not here!

-Sorry for that, I'm still a little confused, I'm new to this, there's a lot of material :-(
Just to ask, whether the change is already visible in snapshots?
Or I have to somehow refresh maven, in order to see change?

**Comment by saudet** [comment]
The builds here are complete, so they are now available as snapshots, yes:
https://github.com/bytedeco/javacpp-presets/actions/runs/2294747634

**Comment by JeeDevUser** [comment]
Thanks a lot!

Should I change something in the pom.xml,  in relation to the example from
http://bytedeco.org/builds/

?

**Comment by saudet** [comment]
That sample pom.xml file is going to get you OpenCV, among other things, but that's fine.
