### ISSUE TITLE
Missing constructors (or static methods returning class instance) in ColorCorrectionModel Java class?

### ISSUE THREAD

**Issue by JeeDevUser** [bytedeco/javacpp#572]
Hi,
In the fresh snapshot, constructors in the Java class **ColorCorrectionModel** 
 seem to be missing:
https://docs.opencv.org/4.x/df/d38/classcv_1_1ccm_1_1ColorCorrectionModel.html

In any case, there is no way to initialize ColorCorrectionModel in, for example, that way:

https://docs.opencv.org/4.x/df/d38/classcv_1_1ccm_1_1ColorCorrectionModel.html#aac53feabaac74da5edd9ade5e4163cd0

**Comment by saudet** [comment]
Sure it's there: https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/gen/java/org/bytedeco/opencv/opencv_mcc/ColorCorrectionModel.java#L54

And please ask your questions about the presets over there, not here!
