### ISSUE TITLE
How to handle varargs

### ISSUE THREAD

**Issue by ReneHollander** [bytedeco/javacpp#59]
Hello!

I am a bit stuck on how to handle varargs (...). I am using javacpp to create bindings for a pure C library.

Thanks,
Rene Hollander

**Comment by saudet** [comment]
Varargs are usually used by functions like `printf()` to format strings. Since we can pass any strings we want from Java, this isn't usually an issue.

Could you provide more details about your current needs? Thanks

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that my answer was clear enough, but please let me know if you still have issues. Thanks!
