### ISSUE TITLE
Could not find or load main class: org.bytedeco.javacpp.tools.Builder

### ISSUE THREAD

**Issue by benshiffman** [bytedeco/javacpp#592]
Due to some installation restrictions on my work machine, I'm having to run javacpp in Powershell. After following the example on the Mapping Recipes page, the application is failing on the first run.

When I try to parse the headers I've included (in recursive order as directed), I get an error:
Error: Could not find or load main class org.bytedeco.javacpp.tools.Builder    
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.tools.Builder

I'm bewildered as to what may be causing this. Everything under org.bytedeco.javacpp.tools.* seems to import correctly, but after running java from PS, Builder can't be found....

**Comment by saudet** [comment]
That sounds like a problem with the JDK? Have you tried to execute other classes?

**Comment by benshiffman** [comment]
Actually just switched over to WSL, having much better luck here as a sudoer. I'm getting much further over here with adding a test library to javacpp-presets. Once I get this working I'll grab a different jdk.
Thanks!
