### ISSUE TITLE
Do I have to redefine the macro for a type definition macro like #define BOOL int ?

### ISSUE THREAD

**Issue by lancewoo** [bytedeco/javacpp#593]
For such a macro like :
```C++
#define BOOL int

inline BOOL sayHello(BOOL it) {
    return it;
}
```
, if I don't do anything for the config Java, it gets translated as:
```Java
public static final int BOOL = int;

@NoException public static native int sayHello(int it);
```
in the target Java class. Obviously wrong.

But if I redefine the macro in the config Java file like 
```java
                infoMap.put(new Info("BOOL").cppText("#define BOOL int"));
```
, it works well as it will be commented out and replaced correctly like:
```Java
// #define BOOL int

@NoException public static native int sayHello(int it);
```
I didn't see any difference of this macro definition in between.
So, anything neglected in the Parser?

**Comment by saudet** [comment]
Add a line like this instead, it should do what you need:
```java
    infoMap.put(new Info("BOOL").annotations().cppTypes().translate(false));
```

**Comment by saudet** [comment]
You're getting the same effect by setting `cppText` probably because you're also not setting any `annotations` or `cppTypes`.

**Comment by lancewoo** [comment]
Right, the same effect. I just didn't quite get the concatenating effects of the combination.
And finally I made it by commenting out the macro and using a typedef like:
```C++
typedef  int  BOOL;
```
Thanks.

**Comment by lancewoo** [comment]
It also works with:
```Java
    infoMap.put(new Info("BOOL").cppTypes().translate(false));
```
