### ISSUE TITLE
Linker Issue: cannot find shared library

### ISSUE THREAD

**Issue by benshiffman** [bytedeco/javacpp#594]
Cross-posting this here, since I've discovered the issue is with JavaCPP, not just JavaCPP Presets.
[Original issue on JavaCPP Presets forum](https://github.com/bytedeco/javacpp-presets/issues/1202)

Hello,

Upon running "mvn clean install -Djavacpp.platform.host" to attempt to build a simple test library named "shared," I am getting an error stating, "/usr/bin/ld: cannot find -llibshared.so". I've checked to make sure that libshared.so is in fact in the linked directory, has the correct name, that ld and g++ are both up to date.

Has anyone encountered this before?

For reference, I'm running this on Ubuntu through WSL 1.

Please find command output [here](https://github.com/bytedeco/javacpp-presets/files/9184072/output.txt).

Edit:
Interestingly, I'm getting the exact same error when using the method on JavaCPP's [Mapping Recipes](https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes) page.

**Comment by saudet** [comment]
What's the input?

**Comment by benshiffman** [comment]
> What's the input?

It's a very simple library (containing one function only) that I'm compiling and wrapping with these commands.
$ gcc -c -Wall -Werror -fPIC shared.cpp
$ gcc -shared -o libshared.so shared.o
$ java -jar javacpp.jar SharedLibraryConfig.java
$ java -jar javacpp.jar SharedLibrary.java

I'm getting the error on the last command.

I'm including the library source files, the .so, and SharedLibraryConfig.java.
[input.zip](https://github.com/bytedeco/javacpp/files/9192089/input.zip)

**Comment by benshiffman** [comment]
Agh, I'm embarrassed now.

Issue was in SharedLibraryConfig.java:
Everything worked after I replaced link = {"libshared.so"} with link = {"shared"}.

Thank you, @saudet, for being so active!
