### ISSUE TITLE
OSX 10.10 + Java 8 issue loading native libraries

### ISSUE THREAD

**Issue by ffcsoftware** [bytedeco/javacpp#6]
I have an applet with JavaCV running fine in all operating systems (Win32, Win64, OSX 10.9, 10.8, 10.7) but recently I've detected the following error in OSX 10.10 (yosemite) running with Java8 (the only runtime available for this OSX version):

```
./libopencv_core.2.4.dylib: malformed mach-o image: load command #12 length (0) too small in ./libopencv_core.2.4.dylib
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1083)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
    ... 12 more
```

Anyone else with this problem? Any suggestion?

Thanks in advance!

**Comment by Nonnis-M** [comment]
It could be possible that the last version of complied libs is affected from the same issue? On Yosemite 10.10.3 I get the same error:
libopencv_core.2.4.dylib: malformed mach-o image: load command #12 length (0) too small in ...

I'm using the JavaCV 1.0 binary and sources archives.

**Comment by saudet** [comment]
@Nonnis-M JavaCV 1.0 doesn't link with OpenCV 2.4, so you're probably not using 1.0.

**Comment by Nonnis-M** [comment]
I'm using the JavaCV 1.0 binary archive linked on the JavaCV README which use OpenCV 3.0
