### ISSUE TITLE
Shutdown hook throws exception on windows in JavaFX application

### ISSUE THREAD

**Issue by JLLeitschuh** [bytedeco/javacpp#60]
We are running your library as part of a bundled JavaFX application. JavaFX bundles the JRE in the `runtime` folder so you don't need to have java installed to run the application.

I tried the given command on a windows machine. If I try entering the command that the runtime hook is trying to create into the windows command prompt it fails because `/bin/java` does not exist. However, it when I append `.dll` to the end of the command (`/bin/java.dll`).

I replaced the user's home directory with %HOME% to preserve anonymity of the users machine I'm using.

``` java
java.lang.RuntimeException: java.io.IOException: Cannot run program "%HOME%\AppData\Local\GRIP\runtime/bin/java": CreateProcess error=2, The system cannot find the file specified
    at org.bytedeco.javacpp.Loader$2.run(Loader.java:645)
Caused by: java.io.IOException: Cannot run program "$HOME\AppData\Local\GRIP\runtime/bin/java": CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at org.bytedeco.javacpp.Loader$2.run(Loader.java:643)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
    at java.lang.ProcessImpl.start(ProcessImpl.java:137)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 1 more
```

<img width="916" alt="screen shot 2016-01-09 at 4 25 25 pm" src="https://cloud.githubusercontent.com/assets/1323708/12218461/bdefbf48-b6ed-11e5-9295-7648b1c9ba67.png">

**Comment by saudet** [comment]
I see, does this mean we can't rely on the `java` executable being usable in the case of JavaFX applications?

In any case, @cypof is working on something that will allow us to do without this shutdown hook (pull https://github.com/bytedeco/javacpp/pull/43) so I'll assign him to this issue as well. :)

**Comment by JLLeitschuh** [comment]
Correct. You can't rely on the `java` executable being present.

**Comment by saudet** [comment]
Actually, it's just occurred to me that we've already got a way to work around this. We can specify a cache dir via the "org.bytedeco.javacpp.cachedir" property:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Loader.html#getCacheDir--
When this is set, the DLLs are extracted there and not deleted, so we don't need a shutdown hook on Windows. You could just set it to the cache directory of your application, for example, and you'd be set. How does that sound?

**Comment by henroth** [comment]
First, thanks for an awesome project, it's been super helpful. Second, I've been having a similar problem. The framework I'm using requires that I package my dependencies in a jar of jars, so the shutdown hook ends up throwing this.
```
05 May 2016 11:34:34,649 ERROR [Thread-68] (FrameworkHandler:14) - Thread unexpectedly terminated with exception: Thread-68, URI is not hierarchical
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at org.bytedeco.javacpp.Loader$2.run_aroundBody0(Loader.java:640)
	at org.bytedeco.javacpp.Loader$2$AjcClosure1.run(Loader.java:1)
	at framework.api.aspects.ContextClassLoaderInstaller.ajc$around$framework_api_aspects_ContextClassLoaderInstaller$1$4ab09a32proceed(ContextClassLoaderInstaller.aj:46)
	at framework.api.aspects.ContextClassLoaderInstaller.ajc$around$framework_api_aspects_ContextClassLoaderInstaller$1$4ab09a32(ContextClassLoaderInstaller.aj:59)
	at org.bytedeco.javacpp.Loader$2.run(Loader.java:632)
```
The work around you suggested does work, so thank you for posting it.  But because other people might not know to set the cache directory I think you could change the shutdown hook to the following because it only runs for windows
```
    // So, let's use a shutdown hook to delete all the files
    static {
        if (getPlatform().startsWith("windows")) {
            Runtime.getRuntime().addShutdownHook(new Thread() {
                @Override public void run() {
                    if (tempDir == null) {
                        return;
                    }
                    try {
                        // ... to launch a separate process ...
                        List<String> command = new ArrayList<String>();
                        command.add("RMDIR");
                        command.add("/S");
                        command.add("/Q");
                        command.add(tempDir.getAbsolutePath());
                        new ProcessBuilder(command).start();
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            });
        }
    }
```
Admittedly I am not a windows expert so I don't know the full implications of using a windows call instead of the java version, but it might be something to consider

**Comment by saudet** [comment]
Interesting, we would have to do that in a loop though, because it might take a couple of seconds for the JVM process to actually exit.

**Comment by JLLeitschuh** [comment]
Has this been resolved?

**Comment by saudet** [comment]
With this commit we can say that it has been resolved:
https://github.com/bytedeco/javacpp/commit/076fd04173bf305eed39d8a64da79acbd5105ef2
Not released yet, but if you could test it and make sure, that would great! :)

**Comment by JLLeitschuh** [comment]
Can someone from @WPIRoboticsProjects/grip test this to see if it works?

**Comment by saudet** [comment]
JavaCPP 1.3 now extracts libraries into a cache, and does not delete them, so we no longer need a shutdown hook and it has been removed. Enjoy!
