### ISSUE TITLE
Duplicate code generated

### ISSUE THREAD

**Issue by 243826** [bytedeco/javacpp#61]
I am not able to pinpoint what I am doing wrong. I have a class (CPPOutputPort) which is referenced from 2 different java classes. I see that the CPPOutputPort class has repeated definitions for peer cpp code in the generated cpp file (target/jni/CandidApex.cpp). 

You need mvn installed in order to build the project using the following  command. Alternately the pipeline/pom.xml shows how it's invoking javacpp.

```
unzip pipeline.zip && cd pipeline && mvn package
```

[pipeline.zip](https://github.com/bytedeco/javacpp/files/86515/pipeline.zip)

**Comment by 243826** [comment]
On the flip side, if I spell out the 2 classes underneath the routing package instead of package glob, then the definition for Javacpp_CPPOutputPort is completely omitted.

**Comment by saudet** [comment]
The archive is missing a few header files, so it's hard to test out. What are the repeated definitions that you get? I see a couple of them around `JavaCPP_CPPOutputPort`, is that all or is there more?

**Comment by 243826** [comment]
The missing header file is needed to compile the generated code. You can generate the code without it though. The problem is with the code generation. The generated code has repeated declaration and definition for JavaCPP_CPPOutputPort. That's all. Please look at my pull request.

**Comment by 243826** [comment]
when do you close the issue? After release or after merge?

**Comment by saudet** [comment]
I tend to close issues that have remained opened after a release, as a sort of review, but people who are already satisfied anyway close issues by themselves right away after it's in master, your choice. :)

**Comment by saudet** [comment]
Released in version 1.2! Thanks for the bug report
