### ISSUE TITLE
Memory leak Indexers

### ISSUE THREAD

**Issue by AMoly66** [bytedeco/javacpp#616]
I am stuck with an indexer memory leak that I can not understand.

Small code example :

`public static void main (String[] args) throws InterruptedException {

        System.out.println("in Start Program ");
        System.out.println(Pointer.physicalBytes());

            int flag = 0;
            while (flag < 200) {
                MatExpr testExp = Mat.ones(1048, 1048, opencv_core.CV_64F);
                Mat test = testExp.asMat();
                double[] testrowMajor = toDoubleArray(test);
                testrowMajor=null;
                test.release();
                testExp.deallocate();
                System.out.println(Pointer.physicalBytes());
            }
}

    public static double[] toDoubleArray(final Mat data) {

        int m = data.rows();
        int n = data.cols();
        double[] output = new double[m * n];

        try(PointerScope scope = new PointerScope()){
            Indexer idx = data.createIndexer();

                int sd = m, ld = n;
                for (int sdi = 0; sdi < sd; ++sdi) {
                    for (int ldi = 0; ldi < ld; ++ldi) {
                        double value = idx.getDouble(sdi, ldi);
                        output[(sdi * ld) + ldi] = value;
                    }
                }
           

            idx.release();
            Pointer.deallocateReferences();
        }

        return output;
    }
`

Such code return me a Pointer.physicalBytes() which increasing by step :

324325376
329728000
329990144
330223616
330334208
340000768
340000768
340000768
340000768
340000768
340000768
350650368
350650368
350650368
350650368
350650368
350650368
351174656
392806400
436600832
480665600
524460032
568524800
609603584
609603584
609603584
609603584
609603584
609603584
609603584
609603584
609603584
609603584
609603584
609603584
618790912
618790912
618790912
618790912
618790912
618790912
618790912
618790912
618790912
618790912
618790912
618790912
640409600
684204032
728268800
772063232
816128000
859922432
903987200
947781632
991846400
1035640832
1079705600
1123500032
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149403136
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1149673472
1159397376
1203191808
1247256576
1291051008
1335115776
1378910208
1422974976
1466769408
1510834176
1554628608
1598693376
1642487808
1686552576
1730347008
1774411776
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776455680
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504
1776533504

Is there any issue with my code ? I can not understand such bump of memory ? 
Thank you for your help.

I am using the last version of the available libs.

**Comment by saudet** [comment]
The data is stored in the Mat. If you want that memory back, you'll need to deallocate the Mat.

**Comment by AMoly66** [comment]
Thank you for your answer, the release of the Mat in the main method is not sufficient ? Thank you

**Comment by AMoly66** [comment]
Moreover adding a data.release() in the toDoubleArray method does not change the weird memory behavior.

**Comment by saudet** [comment]
Instead of trying to figure out manually what we need to deallocate, I would recommend using PointerScope:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by saudet** [comment]
If you're still getting a "leak" even when using PointerScope though, please let me know!

**Comment by AMoly66** [comment]
I am still having some memory leak. However, I will need more investigation on my side to be sure that this is due to pointer Score and indexers. At the moment where I am sure that the issue is coming from the PointerScope, I let you know.
Thank you, Best

**Comment by devjeonghwan** [comment]
`Pointer.physicalBytes()` returns the total memory usage of the current process. (Including JVM memory usage)

So, I added `System.gc();` before `System.out.println(Pointer.physicalBytes());` and run 6 hours.

### Memory Usage
![image](https://user-images.githubusercontent.com/13144936/196309593-dafafe45-7a62-4f91-ae80-f7bde6a95527.png)

### Maximum amount of memory used (excluding peak)
![image](https://user-images.githubusercontent.com/13144936/196309775-38585f51-cec4-417d-9dbe-c08b15d77518.png)

There doesn't seem to be a memory leak.

**Comment by AMoly66** [comment]
Thank you for your help, I guess the mistake come from somewhere else.
Sorry for the question.

Best
