### ISSUE TITLE
Use external dependent c++ lib (protobuf)

### ISSUE THREAD

**Issue by ValentinaBaranova** [bytedeco/javacpp#621]
I'm trying to plugin protobuf library as dependency like it was done in other javacpp presets, but I've got an error when I try to use created jar:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniTelemetryd in java.library.path
...
Caused by: java.lang.UnsatisfiedLinkError: /Users/valentina.baranova/.javacpp/cache/telemetryd-0.0.2-macosx-x86_64.jar/com/arrival/mobility/telemetryd/macosx-x86_64/libjniTelemetryd.dylib: dlopen(/Users/valentina.baranova/.javacpp/cache/telemetryd-0.0.2-macosx-x86_64.jar/com/arrival/mobility/telemetryd/macosx-x86_64/libjniTelemetryd.dylib, 0x0001): symbol not found in flat namespace '__ZN6google8protobuf5Arena19CallDestructorHooksEv'
```
Here is my cppbuild.sh:
```
#!/bin/zh
PROTO=3.7.1
rm -rf ../../src/gen/java

if [[ ! -f "protobuf-cpp-$PROTO.tar.gz" ]]; then
  wget https://github.com/google/protobuf/releases/download/v$PROTO/protobuf-cpp-$PROTO.tar.gz
fi

cd "$PLATFORM$EXTENSION"
INSTALL_PATH=`pwd`

if [[ ! -d "protobuf-$PROTO" ]]; then
  echo "Decompressing archives..."
  tar --totals -xf ../protobuf-cpp-$PROTO.tar.gz
fi

cd protobuf-$PROTO
./configure "--prefix=$INSTALL_PATH" --disable-shared
make -j $MAKEJ
make install
cd ..

if [[ ! -d $INSTALL_PATH/include/google ]]; then
  cp -r protobuf-$PROTO/src/google $INSTALL_PATH/include/google
fi
```
Here is config:
```
@Properties(
    global = "com.arrival.mobility.telemetryd.global.Telemetryd",
    value = {
            @Platform(
                    value = { "macosx-x86_64" },
                    compiler = "cpp17",
                    define = {"SHARED_PTR_NAMESPACE std", "UNIQUE_PTR_NAMESPACE std"},
                    include = {
                            "google/protobuf/arena.h",
                            "test_functions.h"
                    },
                    resource = {"include", "lib"}, linkresource = "lib"
            )
    }
)
```
My test-javacpp-library compiled without errors (you need `mvn clean install` in main folder and the same in platform folder),
but I've got an error when I run main in test-client-library.
[test-client-library-protobuf.tar.gz](https://github.com/bytedeco/javacpp/files/9811686/test-client-library-protobuf.tar.gz)
[test-javacpp-library-protobuf.tar.gz](https://github.com/bytedeco/javacpp/files/9811706/test-javacpp-library-protobuf.tar.gz)

What I'm doing wrong?

**Comment by saudet** [comment]
I'm not seeing any "link" or "preload" for protobuf. You might need to add those. It's also possible it's trying to map functions that are not actually defined. You'll need to filter those out like this:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#defining-macros-and-controlling-their-blocks

**Comment by ValentinaBaranova** [comment]
Ok, I will try. In my real code I'm writing javacpp adapters for our library, which was builded with protobuf (our lib was build with BUILD_SHARED_LIBS=ON option). As I understand I need to provide protobuf sources for javacpp library, but I'm not sure that I need build protobuf again during cppbuild step. When I look into existed "onnx" preset in javacpp-presets, I don't see "preload" or link to "protobuf" lib, but I see static lib file "libprotobuf.a" inside cppbuild folder - not sure that it is used by javacpp because as I understand only "dylib" suffix is used.
Unfortunately, I cannot completely check this preset because when I build main and platform artifacts and try to run sample and got similar error:
```
java.lang.UnsatisfiedLinkError: no jnionnx in java.library.path: /Users/valentina.baranova/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.

Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/valentina.baranova/.javacpp/cache/onnx-1.12.0-1.5.8-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/onnx/macosx-x86_64/libjnionnx.dylib
```

**Comment by ValentinaBaranova** [comment]
I've double checked code with our library, which was builded with protobuf, and looks like it works, I don't understand reason of previous problem yet.
