### ISSUE TITLE
Mention Nalim in Readme

### ISSUE THREAD

**Issue by LifeIsStrange** [bytedeco/javacpp#627]
https://github.com/apangin/nalim
It has some constraints but achieve maximal performance hence a worth mentioning approach in the trade-off space.

**Comment by saudet** [comment]
It's more an alternative to JNI than JavaCPP. It's something that JavaCPP could use, but it doesn't do anything that JavaCPP does.

**Comment by LifeIsStrange** [comment]
Do as you wish, you're the expert :)

**Comment by saudet** [comment]
Although it does looks like he intends to provide mapping for structs: https://github.com/apangin/nalim/commit/6ade575ad72d319f326eae239e9ad41de2168754

Please open a pull request with an updated README.md file. Thank you!
