### ISSUE TITLE
Tool to get the address of a DirectByteBuffer

### ISSUE THREAD

**Issue by calvertdw** [bytedeco/javacpp#628]
I don't know if it is safe or a good idea, but I'm often wanting to get the address of a direct ByteBuffer that I already have in order to setup a JavaCPP Pointer to point there. Currently, we are able to do this by creating a `new Pointer(ByteBuffer)`, however, in realtime and high performance settings, we don't want to allocate a new Pointer each time.

I think the way it's done internally is using `env->GetDirectBufferAddress`.
https://github.com/bytedeco/javacpp/blob/81252dd2822d2bee3555bb4c094a78e94796b4db/src/main/java/org/bytedeco/javacpp/tools/Generator.java#L2333

Maybe we could have some static method available that just allows us to utilize `GetDirectBufferAddress`?

**Comment by saudet** [comment]
You could easily add a mapping for GetDirectBufferAddress() in your library, after all that's JavaCPP is for :)

But if we were to add something to the Pointer class, what about a `protected static native long Pointer.getDirectBufferAddress(Buffer b)`? Could you open a pull request to that effect?

**Comment by calvertdw** [comment]
It seems generally valuable for each preset to have available and in most places we are using the provided presets anyway. I like the idea of a static method in Pointer.

I'm going to see if @ds58 has time for this. He's been helping our lab use JavaCPP to it's full potential. We've wrapped a few custom things already and it's been a huge success.
