### ISSUE TITLE
if the target c++ file generates a.A library, how to use Javacpp?

### ISSUE THREAD

**Issue by xujingzhou** [bytedeco/javacpp#631]
hi, How can I use javacpp to dynamically generate jni's.so library if the target c++ file generates a.A library?

**Comment by saudet** [comment]
Sure, anything supported by your C++ compiler will work.

**Comment by xujingzhou** [comment]
I have a.a lib and some *.h files now. How can I generate jni libraries supported by android? Any examples?

**Comment by saudet** [comment]
The zlib sample you were looking at does that. What's missing from it?
