### ISSUE TITLE
timing issue between java thread and calls to c library

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp#64]
hi all, not sure where i am going wrong but my timing is all off between java and C code ... still playing with libuvc and my java initialization code depends on some c initialization code in that library. something like 

    {
        initializeStuffInCLibrary();
        //Thread.sleep(1000);
        doSomeMoreInitStuffThatDependsCInit();
    }

in most instances the call to doSomeMoreInitStuffThatDependsCInit() gets called before the previous one has had a chance to finish, but on rare occasions it does work just fine. i am getting a bit unhappy about having to start my app 20 times until i get one proper alignment of the stars. i had hoped that if i delay continued processing with thread.sleep, it will give more time for completion of the C Initialization, but adding this line appears to make no difference, the c stuff seems to wait also. Do you have any recommendations for how i can up my chances of things completing in the right order? any way i can give the first call more time before calling the second one? much obliged

**Comment by saudet** [comment]
You sure it's not a problem with your driver? I often get that behavior
with any app on Linux, although these days it's better...

**Comment by lobsteroh** [comment]
Hmmmh, not sure how i could handle this ... this is on mac osx 10.11.3. are you talking about the built in uvc driver in the OS? do you think it would an acceptable approac to put the c initialization into its own thread, then wait with the main thread until it is certain that the first thread has completed. am puzzled on how to find a workaround ... any suggestions?

**Comment by saudet** [comment]
Oh, this is on Mac? There shouldn't be any problems with the driver then.

What do people do when using libuvc from C then?

**Comment by lobsteroh** [comment]
i am not much of a C programmer, but when i play with the order there it
does not give me this situation where subsequent lines of code get
execurted out of sync. this seems to get introduced with the java to C
bridge, looks like to me.

havent heard any reasons not to try putting it into a separate thread. time
at startup is not critical. i can wait a second or two. here is what i
tried as a workaround ...


On Tue, Jan 26, 2016 at 7:49 PM Samuel Audet <notifications@github.com>
wrote:

> Oh, this is on Mac? There shouldn't be any problems with the driver then.
>
> What do people do when using libuvc from C then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bytedeco/javacpp/issues/64#issuecomment-175316734>.
>
-- 

Robert
------------------------------------------------------------------

Robert Huber, PhD
Helen Putnam Fellow, Radcliffe Institute for Advanced Study
Harvard University, Cambridge, MA 02138
Professor, Biological Sciences,  BGSU
Associate Editor - Acta Ethologica
Associate Editor - Frontiers in Physiology
Email: rh.bgsu@gmail.com

------------------------------------------------------------------

**Comment by saudet** [comment]
The functions don't behave differently just because we call them from Java or from C. There's most likely something else that is different that you haven't noticed yet.

**Comment by lobsteroh** [comment]
Wanted to report that the workaround via separate thread works even on the
faster Mac systems that had been most susceptible.

On Wed, Jan 27, 2016, 07:55 Samuel Audet <notifications@github.com> wrote:

> The functions don't behave differently just because we call them from Java
> or from C. There's most likely something else that is different that you
> haven't noticed yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bytedeco/javacpp/issues/64#issuecomment-175604213>.
>
-- 

Robert
------------------------------------------------------------------

Robert Huber, PhD
Helen Putnam Fellow, Radcliffe Institute for Advanced Study
Harvard University, Cambridge, MA 02138
Professor, Biological Sciences,  BGSU
Associate Editor - Acta Ethologica
Associate Editor - Frontiers in Physiology
Email: rh.bgsu@gmail.com

------------------------------------------------------------------
