### ISSUE TITLE
How do load a static link library

### ISSUE THREAD

**Issue by feng-for** [bytedeco/javacpp#665]
Hi!
Thank you very much for your help! I want to confirm one thing about javacpp. Can javacpp load a static Library? Such as  myFunction.lib file. If can, how do set it up?

**Comment by saudet** [comment]
Sure, you can find examples of that in the presets, for example:
https://github.com/bytedeco/javacpp-presets/tree/master/artoolkitplus

**Comment by feng-for** [comment]
> Sure, you can find examples of that in the presets, for example: https://github.com/bytedeco/javacpp-presets/tree/master/artoolkitplus

Thanks for your help. Let me look at this example first
