### ISSUE TITLE
javacpp resource loading exception in springboot application

### ISSUE THREAD

**Issue by huazai023** [bytedeco/javacpp#683]
Error: When the springboot application depends on javacpp, the javacpp loader cannot extract the required files

Reason: When javacpp is integrated into the springboot application, the path for the loader class to obtain resources becomes jar:file:/aa.jar!/BOOT-INF/lib/bb.jar!/com/bb/test.txt
This path will cause resource loading exceptions in the Loader class

Solution: Change line 809 in the loader class from URL u = new URL(s.substring(0, s.indexOf("!/") + 2) + entryName); to: URL u = new URL(s.substring (0, s. lastIndexOf("!/") + 2) + entryName);

**Comment by saudet** [comment]
Sounds good, please open a pull request with this change! Thanks

**Comment by huazai023** [comment]
I've opened a pull request, link: https://github.com/bytedeco/javacpp/pull/685

**Comment by huazai023** [comment]
Hello: Can you provide cpython's Android platform compilation script?

**Comment by saudet** [comment]
Ah, I see, that's what you were asking about in https://github.com/bytedeco/javacpp-presets/issues/1363. I've reopened it

**Comment by saudet** [comment]
Fix released with JavaCPP 1.5.9! Thanks for the contribution
