### ISSUE TITLE
is there any module similar to opencv imgcodecs?

### ISSUE THREAD

**Issue by Thiago-Santos-SI** [bytedeco/javacpp#692]
in my android project, I had an old version of java (I believe) and inside it there was a cpp module, in which I could use several cpp methods.

![Captura de tela de 2023-07-04 13-46-07](https://github.com/bytedeco/javacpp/assets/44899195/68d98c7f-3c23-4596-a355-2c2cd6336e3a)

I'm updating everything to the current versions and I realize that this cpp module no longer exists.

I researched recent projects and noticed that in some cases developers are using the imports below to import the methods I'm looking for.

**import static org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage;**
or
**import static org.bytedeco.javacpp.opencv_imgproc.*;**

![Captura de tela de 2023-07-04 13-49-10](https://github.com/bytedeco/javacpp/assets/44899195/b1a030a2-c8a8-4ce4-bcea-d70a4f58b854)

however I am not able to find any version that syncs with my android and that actually has these modules
below is the versions and dependency in my android project.

![Captura de tela de 2023-07-04 13-49-31](https://github.com/bytedeco/javacpp/assets/44899195/11621c8a-1a5a-4c9f-8690-79ab7f793e14)

**Comment by saudet** [comment]
cvLoadImage() is still available here: http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/helper/opencv_imgcodecs.html#cvLoadImage-java.lang.String-

**Comment by Thiago-Santos-SI** [comment]
> cvLoadImage() is still available here: http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/helper/opencv_imgcodecs.html#cvLoadImage-java.lang.String-

it worked for me, thanks!
