### ISSUE TITLE
Wiki Information Out of Date?

### ISSUE THREAD

**Issue by VestOfHolding** [bytedeco/javacpp#698]
I noticed a few of the wiki tutorial/documentation pages haven't been updated in years. Does the info on these pages still represent the best way to do things and generally best info?

Examples:
* Basic Architecture page: Last updated Sep 2018.
* Build Script page: Last updated Mar 2015.
* Examples page: Last updated Mar 2015 (more recent edits were solely to destroy and recreate the page).
* Java Code page: Last updated Mar 2015.
* Maven page: Almost all relevant info last updated May 2016.

And those March 2015 "updates" were just migrating the pages from Google Code. 

If not these pages, are there better places where documentation/tutorials are stored?

**Comment by cartel1** [comment]
@VestOfHolding Good question. I've recently found out about this project and the first thing I noticed is the old and possibly outdated docs.

**Comment by saudet** [comment]
Contributions are welcome! And if you have more specific questions, instead of just complaining, please do ask

**Comment by cartel1** [comment]
@saudet Why would you use the term "complaining" for someone just discovering your project?  It sounds somewhat aggressive and dismissive.

So for an opensource project, people should just highlight issues with the source code and not mention anything they notice about the associated documentation which is the first point of contact for new users trying to get details about an opensource project?

**Comment by VestOfHolding** [comment]
> Contributions are welcome! And if you have more specific questions, instead of just complaining, please do ask

Yikes dude. Framing what I'm pointing out as just complaining is pretty wild. I'm looking at implementing my first project with the library and don't have near the expertise to contribute documentation/tutorial changes, and thinking someone like me might be able to is also very strange.

Frankly, politely asking if the current documentation can be up to date, or where else to look for the best help, shouldn't be something that garners that type of reaction.

**Comment by TesseractLaboratories** [comment]
I could see something like "this documentation isn't helpful" as "just" complaining, but a bulleted list along with a follow-up acknowledging the possibility of better documentation elsewhere... feels pretty specific to me?

I wonder if this is a culture disconnect.  I can see there are a couple of Q&A posts under the Discussions tab, is it possible that would be a more receptive forum for these questions?  If so, that feels like both a good candidate for a README, and a good redirect for a new user reaching out.

**Comment by saudet** [comment]
The README fille is up-to-date, but that's about the extent that I can afford to maintain myself. If you want other pages written by other people to be up-to-date, like I keep saying contributions are welcome!
