### ISSUE TITLE
'jni.h' file not found

### ISSUE THREAD

**Issue by shuaidan0412** [bytedeco/javacpp#715]
'jni.h' file not found
mac: 12.5

**Comment by saudet** [comment]
You'll need to install the JDK

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1417

**Comment by shuaidan0412** [comment]
have jdk.

`
evindeMacBook-Air:include devin$ pwd
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/include
devindeMacBook-Air:include devin$ ll
total 384
drwxr-xr-x   9 root  wheel    288 10  6  2018 ./
drwxr-xr-x  15 root  wheel    480 10 12 16:52 ../
-rw-r--r--   1 root  wheel  20128 10  6  2018 classfile_constants.h
drwxr-xr-x   4 root  wheel    128 10  6  2018 darwin/
-rw-r--r--   1 root  wheel   8690 10  6  2018 jawt.h
-rw-r--r--   1 root  wheel   6407 10  6  2018 jdwpTransport.h
-rw-r--r--   1 root  wheel  73701 10  6  2018 jni.h
-rw-r--r--   1 root  wheel  77428 10  6  2018 jvmti.h
-rw-r--r--   1 root  wheel   3774 10  6  2018 jvmticmlr.h
devindeMacBook-Air:include devin$ pwd
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/include
devindeMacBook-Air:include devin$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home

`

**Comment by shuaidan0412** [comment]
java.home   return   "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre"

**Comment by saudet** [comment]
That means you're using the JRE. That won't work. Like I said, you need to use the JDK.
