### ISSUE TITLE
std::unique_ptr fields

### ISSUE THREAD

**Issue by HGuillemet** [bytedeco/javacpp#717]
```c++
#include <memory>

struct S {
  std::unique_ptr<int> p;
};
```
parses to this getter and setter:
```Java
  public native @UniquePtr IntPointer p(); public native S p(IntPointer setter);

```
Compiling the JNI triggers:
```
error: ambiguous overload for 'operator=' (operand types are 'std::unique_ptr<int>' and 'UniquePtrAdapter<int>')
 1178 |     ptr->p = adapter0;
```
`=` for `unique_ptr` has 2 overloads : one taking a `std::unique_ptr &&` and another taking a `const std::unique_ptr &`. And the adapter has cast overloads for both.

What's the best way to handle this ?

(case seen in Pytorch 2.1)

**Comment by saudet** [comment]
I guess either one work, but give it a try with a `@Cast` like there already are for SharedPtrAdapter.

**Comment by HGuillemet** [comment]
i don't think `@Cast` works on fields setter.

**Comment by saudet** [comment]
I'm sure it does, try with the third element.

**Comment by HGuillemet** [comment]
Ok, it seems to work with this info:
```Java
new Info("S::p").annotations("@UniquePtr", "@Cast({\"\", \"\", \"std::unique_ptr<int>&&\"})")
```
The `@Cast` is put on the getter only, but it affects the generation of the setter JNI, somehow.

Thanks, closing this issue.
