### ISSUE TITLE
Function pointer returning shared_ptr

### ISSUE THREAD

**Issue by HGuillemet** [bytedeco/javacpp#720]
```c++
#include <memory>

struct S {
  int x;
};

std::shared_ptr<S> (*f)();
```

The JNI cannot compile with:
```
error: invalid conversion from 'std::shared_ptr<S> (*)()' to 'S* (*)()' [-fpermissive]
  628 |     if (rptr != NULL) rptr->ptr = f;
```
Because the generated class:
```C++
struct JavaCPP_hidden JavaCPP_j_S_1F {
    JavaCPP_j_S_1F() : ptr(NULL), obj(NULL) { }
    S* operator()();
    S* (*ptr)();
    jobject obj; static jmethodID mid;
};
```
has a function returning `S*` instead of `std::shared_ptr<S>`.

**Comment by saudet** [comment]
JavaCPP needs a FunctionPointer peer class

**Comment by HGuillemet** [comment]
Sure. The problem, if I understood well, is the `@SharedPtr` annotation not taken into account by the Generator when generating the peer class.

**Comment by saudet** [comment]
Right, so where is that FunctionPointer class?

**Comment by HGuillemet** [comment]
```Java
@Properties(inherit = presets.P.class)
public class S_F extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    S_F(Pointer p) { super(p); }
    protected S_F() { allocate(); }
    private native void allocate();
    public native @SharedPtr S call();
}
```
That's the class automatically generated by the parser from the C++ code above.

**Comment by saudet** [comment]
You'll need to add at least a `@Cast` to that...

**Comment by HGuillemet** [comment]
`public native @Cast({"", "std::shared_ptr<S>"}) @SharedPtr S call();`

seems to work. Thanks.

Do we close this issue or keep it open in case there is something to fix to avoid this `@Cast` ?

**Comment by saudet** [comment]
We need to specify the type somehow. As I've mentioned somewhere before, think of the `@Cast` as if it were named `@As` instead.

**Comment by HGuillemet** [comment]
`@SharedPtr` already means that the function returns a `shared_ptr` of `S`. For a normal function, that calls a native function of the object pointed by the `Pointer` instead of the native function directly pointed by the `Pointer`, we don't need the `@Cast`.

**Comment by saudet** [comment]
No, it doesn't, for example, see issue https://github.com/bytedeco/javacpp/issues/717

**Comment by HGuillemet** [comment]
In #717 the `@Cast` is to disambiguate between 2 overloads of `unique_ptr.operator=`. The `@Cast` doesn't change the type of the field.
