### ISSUE TITLE
Skip #include from a header file

### ISSUE THREAD

**Issue by zaki699** [bytedeco/javacpp#760]
Is it possible to skip an include file from a header file?

the include is actually throwing a file not found during compilation because the file does not exist.

I tried with linePatterns but it did not work. 

Thx

**Comment by saudet** [comment]
You can patch the header file in the build script, that's pretty much the only way.

**Comment by zaki699** [comment]
Yes I figured it was an issue from Shaka Packager. It is fixed on their side. I did not want to make a patch or modify any files locally as it would probably break the next releases.

Thanks for your help.
