### ISSUE TITLE
How do I convert a javacv Frame fetched from FrameGrabber to a opencv.core.Mat object

### ISSUE THREAD

**Issue by wweverma1** [bytedeco/javacpp#765]
Hello! First of all thanks to the author for building such an amazing library 👏

Can someone please help me with this-
I am working on a project where I have to retrieve frames from a RTSP stream and then convert it to `opencv.core.Mat` for further processing. 
Currently I'm using `FFmpegFrameGrabber` to get the frames. then converting that frame into a bitmap using `AndroidFrameConverter` followed by creating a `opencv.core.Mat` object and populating it with the bitmap using `Utils.bitmapToMat` further processing it to RGB.

Is there any easy way to directly get to my requirement without these intermediate steps to optimize my code.

Current Implementation-

```
val converter = AndroidFrameConverter()
val img = Mat()
val Frame: Frame?
frame = grabber.grabImage() ?: break
val bitmap = converter.convert(frame)
val orgImg = Mat(bitmap.height, bitmap.width, CvType.CV_8UC3)
Utils.bitmapToMat(bitmap, orgImg)
Imgproc.cvtColor(org, img, Imgproc.COLOR_BGR2RGB)

//doing further processing with img
```

Any help will be appreciated :)

**Comment by saudet** [comment]
We can use OpenCVFrameConverter.ToOrgOpenCvCoreMat for that:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.ToOrgOpenCvCoreMat.html

**Comment by wweverma1** [comment]
Thanks @saudet for the heads up, 
One more thing will the Mat object received from OpenCVFrameConverter.ToOrgOpenCvCoreMat have RGB or BGR color scheme??

**Comment by saudet** [comment]
OpenCV is usually BGR, if that's what you're asking

**Comment by wweverma1** [comment]
Got it, thanks for taking out your time :)
