### ISSUE TITLE
Error when running cppbuild.bash file 

### ISSUE THREAD

**Issue by EAOZONE** [bytedeco/javacpp#770]
When running a cppbuild.bash for our java wrapped repo we get this error error: no matching function for call to ‘franka::Robot::control(JavaCPP_us_ihmc_libfranka_libfrankaConfig_00024ControlCallback&, bool, jdouble&)’ We believe it has something to do with our definition of our class 
'public static class ControlCallback extends FunctionPointer { 
static { Loader.load(); } 
public    ControlCallback(Pointer p) { super(p); } 
protected ControlCallback() { allocate(); } 
private native void allocate(); 
public native Torques call(@ByRef @Const RobotState robotState, Duration duration);}' is there anything particuarly wrong that is obvious? We are wrapping libfranka(https://github.com/frankaemika/libfranka/tree/0.9.2) and are having trouble with the callbacks

**Comment by saudet** [comment]
Please try to use the Parser to see how it maps it

**Comment by saudet** [comment]
Duplicate of #771
