### ISSUE TITLE
Ignoring parts of typedef statements

### ISSUE THREAD

**Issue by benbarkay** [bytedeco/javacpp#772]
Hi there,

I'm attempting to map libqmi, which unfortunately also requires me to map some portions of glib.

I'm stuck mapping the following native code:
```c
#endif /* !G_LITTLE_ENDIAN && !G_BIG_ENDIAN */

typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);

struct _GTimeVal
{
  glong tv_sec;
  glong tv_usec;
} GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
```

It maps to the following in Java:
```java
// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package mypackage;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static mypackage.LibQmi.*;

// #endif /* !G_LITTLE_ENDIAN && !G_BIG_ENDIAN */

@Convention("_GTimeVal") @Properties(inherit = mypackage.LibQmiConfig.class)
public class GLIB_DEPRECATED_TYPE_IN_2_62_FOR extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    GLIB_DEPRECATED_TYPE_IN_2_62_FOR(Pointer p) { super(p); }
    protected GLIB_DEPRECATED_TYPE_IN_2_62_FOR() { allocate(); }
    private native void allocate();
    public native @ByVal GTimeVal call(@ByVal GDateTime arg0);
}
```

So in this line:
```
typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
```

It appears that javacpp takes `GLIB_DEPRECATED_TYPE_IN_2_62_FOR` to be the structure name, rather than `GTimeVal`.

How would one either correct this, or skip this mapping altogether?

**Comment by saudet** [comment]
Do you mean something like this?
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#ignoring-attributes-and-macros

Or like this maybe?
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#redefining-the-code-of-a-macro

**Comment by benbarkay** [comment]
> Do you mean something like this? https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#ignoring-attributes-and-macros
> 
> Or like this maybe? https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#redefining-the-code-of-a-macro

I've tried this before:
```java
infoMap.put(new Info("GLIB_DEPRECATED_TYPE_IN_2_62_FOR").skip());
```
As well as playing with all of the options in `info` (i.e. `cppTypes().annotations()`, `cppText()`, etc), but the class continued to be generated.

Now that I've tried this again, seems like it did ignore it.
Maybe the gradle plugin didn't clean up classes from previous run...

Anyhow, closing this for now... I'll reopen a narrower issue once I figure out why the mappings kept the class.
