### ISSUE TITLE
how to define the java class if the c++ file does not have a class?

### ISSUE THREAD

**Issue by shekmun** [bytedeco/javacpp#92]
I've read this: [https://github.com/bytedeco/javacpp/wiki/Examples](https://github.com/bytedeco/javacpp/wiki/Examples) and I can make it work.
But what if my c++ file does not contain a definition of class:
test.h
```c++
int get();
```
test.cpp
```c++
#include "test.h"
int get() {
    return 4;
}
```
What annotations should I use in the java file? FunctionPointer? FunctionCall? ... Please if there is an simple example. Thanks.

**Comment by saudet** [comment]
Just use a static method. There's an example of this here:
https://github.com/bytedeco/javacpp#optimizing-code-performance

**Comment by shekmun** [comment]
I got an error:
```
/home/shekmun/android/workspace/IWatcher/svm/src/main/jni/jniname.cpp: In function 'jint Java_com_ict_hci_svm_name_get(JNIEnv*, jclass)':
/home/shekmun/android/workspace/IWatcher/svm/src/main/jni/jniname.cpp:1082:22: error: 'name' has not been declared
         int rvalue = name::get();
```
and this is my java file ```name.java```
```
@Platform(include = {"test.h", "test.cpp"})
public class name extends Pointer {
    static { Loader.load(); }
    public static native int get();
}
```
The test.h and test.cpp is same as the first comment.

**Comment by saudet** [comment]
Sorry, you need to make sure that the class does **NOT** extend `Pointer`.
