### ISSUE TITLE
Maven plugin documentation

### ISSUE THREAD

**Issue by dtracers** [bytedeco/javacpp#95]
Is there a maven plugin that removes the need to run the javaCpp jar manually so this can be done cleanly with maven instead?

**Comment by saudet** [comment]
Yes: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/BuildMojo.html

But we need to update the wiki page: https://github.com/bytedeco/javacpp/wiki/Maven

Would you be interested in contributing an updated page?

**Comment by dtracers** [comment]
I saw this but was very confused at how the mojo file translates into the
pom plugin.  If I understood that then I can update the wiki page for you.

**Comment by saudet** [comment]
It's used by the presets for example:
https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml
Sure, let me know if you have any questions! Thanks

**Comment by dtracers** [comment]
I updated with wiki let me know if this is correct

**Comment by saudet** [comment]
@dtracers Great, thanks! If that was enough to get you started, then that's good start for the documentation. :+1:
