### ISSUE TITLE
How do i package resources for javacpp ?

### ISSUE THREAD

**Issue by ymolists** [bytedeco/javacpp#97]
Hi All

1) I am trying to package the shared library built by javacpp in a jar file. Unfortunately there is no information on how the magic of Loader.load() works. So i am left with reading the code and piecing the info of where it expects to find the .so files. There is mention of it being located and searched in the resources directory but not exactly how without taking a look at the code. It would be helpful to get an explanation on where to put the generated .so library for 64/32 bit platform for example as well as all the library that the .so depends on. I figured the gradle script[1] for generating the .so i need to package it in a jar now and put it in the correct resources location.

2) The closest info for loading the library in the wiki is mentioned in https://github.com/bytedeco/javacpp/wiki/Examples. But this seems deprecated ??  I am using version 1.1 of the javacpp library Loader.loadLibrary takes 2 arguments ! and the usage explained in the wiki is maybe from an old version ??? What ami supposed to pass as URLs ?

[1]

``` groovy
task jniGen(type: JavaExec) {
    //outputs.dir outputDir
    //inputs.dir inputDir

    println ("-----"+file('.').canonicalPath)

    def targetDir = "${buildDir}/jni"

    def myJni4j = "../myJni/src/myJni4j"
    def myJni4jLib = "../myJni/${myJniSrcDir}/${myJniVersion}"

    main = 'org.bytedeco.javacpp.tools.Builder'
    classpath = sourceSets.main.runtimeClasspath

    args = [ '-d' , targetDir
             //, '-o', 'myJni4j'
             , '-Xcompiler', '-x'
             , '-Xcompiler', 'c++'
             , '-Xcompiler', '-std=c++0x'
             , '-Xcompiler', "-I${myJni4j}"
             , '-Xcompiler', "-I${myJni4jLib}"
             , 'mypkg.mylib.mypath.MyJni4JClass'
    ]
}
```

**Comment by saudet** [comment]
If you use the Builder class either directly or through the command line interface to compile the libraries for you, it will put them along side the .class files in the subdirectory it expects to load them from. To load them, just call `Loader.load()`, no arguments needed.

So, my question to you is, are you having problems using the Builder to compile the libraries? If so, could you explain what these issues are?

**Comment by ymolists** [comment]
The problem is that i am trying to compile the generated c++ code with gradle (not builder) so all i need the Builder class is to generate the actual c++ code and not compile/link the generated code. It would be helpful to know how the Builder class is generating the actual jar file. 

At the beginning (as you can see from above) i was passing the "-d" option to Builder and the .so was getting generated in a local target directory. This what was causing the initial problem. Correct me if i am wrong but i don't think  Loader.load() handles the case when the user passes -d to builder ? once i removed the -o option i figured that the .so was getting placed in the same location as the .class file )))
 
Thank you so much for pointing this out to me ))) 

Regards

**Comment by saudet** [comment]
Just put the library file in the same location as where Builder would put
it using the same filename. Run the samples from the README.md file and
check where they end up and under what name. Do the same and Loader will be
able to load them from there.

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
